usr/src/tools/env/omnios-illumos-omnios.sh
The existing method of retrieving the current branch name fails if more than one branch has been previously checked out and results in a VERSION string that contains embedded newlines. This breaks the build.
This change uses `git symbolic-ref` to retrieve the branch.
=> Fix branch detection in illumos-omnios.env

usr/src/man/man5/lx.5, usr/src/man/man7d/zfd.7d
These are cleanups to the lx.5 and zfd.7d man pages to fix warnings produced by the new lint in gate.
The only fixes are to move sentences so that they start on a new line.
mail_msg:
```
==== Nightly distributed build started:   Thu Jul  6 11:02:05 UTC 2017 ====
==== Nightly distributed build completed: Thu Jul  6 11:47:56 UTC 2017 ====
real    0:45:50
/usr/bin/uname
SunOS build 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc
primary: …
```
=> Cleanup man pages to fix lint warnings

usr/src/cmd/svc/svcs/svcs.c
backport candidates:
- fbc3b3a OS-569 svcs -Z should not emit an error message for zones without SMF
- 55371c7 OS-601 svcs -Z in GZ should skip zones in ready state
- 20f2d84 OS-1634 svcs -ZL does not work when a pattern is specified
not a critical fix but i think it could still be backported as it is very unlikely it will break anything nor requires a reboot. opinions?
before:
```
hadfl@mars:~$ sudo svcs -Z
svcs: Could not bind to repository server for zone ubuntu-16: repository server unavailable
ZONE             STATE          STIME    FMRI
[...]
```
after:
```
SunOS mars 5.11 omnios-upstream-joyent-merge-2017070501-20f2d84f9a i86pc i386 i86pc
hadfl@mars:~$ sudo svcs -Z
ZONE             STATE          STIME    FMRI
[...]
```
mail_msg:
```
==== Nightly distributed …
```
=> Joyent merge/2017070501

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/autofs/lx_autofs.c, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_misc.c, usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_brand.h, usr/src/uts/common/brand/lx/syscall/lx_fcntl.c, usr/src/uts/common/brand/lx/syscall/lx_futex.c, usr/src/uts/common/brand/lx/syscall/lx_getpid.c, usr/src/uts/common/brand/lx/syscall/lx_ioctl.c, usr/src/uts/common/brand/lx/syscall/lx_pipe.c
This PR merges latest LX-related changes from Joyent.
I suggest backporting:
* OS-6202 fdisk -l core dumps in CentOS 7
Comments on the others?
mail_msg:
```
==== Nightly distributed build started:   Wed Jul  5 14:05:11 UTC 2017 ====
==== Nightly distributed build completed: Wed Jul  5 14:48:29 UTC 2017 ====
real    0:43:18
/usr/bin/uname
SunOS build 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc …
```
=> Joyent merge/2017070502

usr/src/cmd/svc/svcs/svcs.c
reference upstream PR: https://github.com/omniosorg/illumos-omnios/pull/5
```
SunOS mars 5.11 omnios-r151022-backport-2017070701-09d3973947 i86pc i386 i86pc
hadfl@mars:~$ sudo svcs -Z
ZONE             STATE          STIME    FMRI
[...]
```
mail_msg:
```
==== Nightly distributed build started:   Fri Jul  7 19:14:13 CEST 2017 ====
==== Nightly distributed build completed: Fri Jul  7 19:53:25 CEST 2017 ====
real    0:39:11
/usr/bin/uname
SunOS mars 5.11 …
```
=> r151022 backport/2017070701

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/mount.c, usr/src/lib/brand/lx/lx_brand/common/mount_nfs.c, usr/src/uts/common/brand/lx/os/lx_acct.c, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/sys/lx_brand.h, usr/src/uts/common/brand/lx/sys/lx_syscalls.h, usr/src/uts/common/brand/lx/syscall/lx_aio.c, usr/src/uts/common/brand/lx/syscall/lx_lseek.c, usr/src/uts/common/brand/lx/syscall/lx_miscsys.c, usr/src/uts/common/brand/lx/syscall/lx_mount.c, usr/src/uts/common/brand/sn1/sn1_brand.c, usr/src/uts/common/brand/solaris10/s10_brand.c, usr/src/uts/common/os/acct.c, usr/src/uts/common/os/exit.c, usr/src/uts/common/sys/acct.h, usr/src/uts/common/sys/brand.h, usr/src/uts/intel/Makefile.files, usr/src/uts/intel/lx_brand/Makefile
This PR merges latest lx-related changes from Joyent and an updated last commit in `README.OmniOS`
I suggest backporting:
- OS-6222 lxbrand lseek32 mishandles negative offsets
Possible other backport candidates (open for discussion):
- ~~OS-6223 lxbrand aio failures under ltp~~
- OS-5028 mount -t nfs4 not working
```
SunOS mars 5.11 omnios-joyent-upstream-2017071301-8d6929d204 i86pc i386 i86pc
hadfl@mars:~$ zoneadm list -v
```
mail_msg:
```
==== Nightly distributed build started:   Thu Jul 13 20:20:46 CEST 2017 ====
==== Nightly distributed …
```
=> Joyent upstream/2017071301

usr/src/lib/brand/lx/lx_brand/common/mount.c, usr/src/lib/brand/lx/lx_brand/common/mount_nfs.c, usr/src/lib/libsocket/inet/getifaddrs.c, usr/src/uts/common/brand/lx/syscall/lx_lseek.c, usr/src/uts/common/brand/lx/syscall/lx_mount.c
reference upstream PR: https://github.com/omniosorg/illumos-omnios/pull/12 https://github.com/omniosorg/illumos-omnios/pull/14
```
hadfl@mars-stable:~$ uname -a
SunOS mars-stable 5.11 omnios-r151022-backport-2017071401-57b4c3978e i86pc i386 i86pc
```
mail_msg:
```
==== Nightly distributed build started:   Fri Jul 14 14:38:11 CEST 2017 ====
==== Nightly distributed build completed: Fri Jul 14 15:19:34 CEST 2017 ====
real    0:41:22
/usr/bin/uname
SunOS mars-stable 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc …
```
=> r151022 backport/2017071401

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/sys/lx_syscalls.h, usr/src/uts/common/brand/lx/syscall/lx_miscsys.c
backport candidates: none
should make a note about OS-6230, however. if users report problems for r151022.
=> illumos-joyent merge/2017072001

usr/src/cmd/dlmgmtd/dlmgmt_door.c
This reverts commit b2519362c825a494fb6e93549e2e32a425011563.
cf. #18 
Requires more investigation.
=> Revert "8437 dlmgmt_setzoneid() doesn't enforce uniqueness"

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/sysv_ipc.c, usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
Upstream merge from Joyent. No backport candidates here.
mail_msg:
```
==== Nightly distributed build started:   Thu Jul 27 22:11:24 UTC 2017 ====
==== Nightly distributed build completed: Thu Jul 27 23:12:12 UTC 2017 ====
real    1:00:48
/usr/bin/uname
SunOS build 5.11 omnios-r151022-5e982daae6 i86pc i386 i86pc
openjdk full version "1.7.0_101-b00"
/usr/bin/as
as: Sun Compiler …
```
=> Joyent merge/2017072701

usr/src/uts/common/io/mr_sas/mr_sas_tbolt.c
8395 mr_sas: sizeof on array function parameter will return size of pointer
This will be backported so that is ready for the next reboot-required update to r151022 but may not necessarily be included in this week's update.
=> Backport mr_sas fix to r151022 branch.

usr/src/uts/common/brand/lx/syscall/lx_sched.c, usr/src/uts/common/os/acct.c, usr/src/uts/intel/Makefile
This commit fixes/suppresses the lint warnings in the bloody build, see https://github.com/omniosorg/illumos-omnios/issues/20
Grepping out the specific warning for `iwn/if_iwn.c.*E_FUNC_RET_MAYBE_IGNORED2` isn't ideal but I can't find any other way to avoid this other than to pepper the code with (void) casts which would complicate keeping up-to-date with upstream. Any other suggestions for this one would be appreciated!
This gets us back to a build that succeeds cleanly.
=> Fix lint warnings

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/os/lx_pid.c, usr/src/uts/common/brand/lx/syscall/lx_aio.c
Upstream merge from `illumos-joyent`.
* OS-6238 panic in lxpr\_access
```
SunOS mars 5.11 omnios-joyent-merge-2017080301-aaae3d8be9 i86pc i386 i86pc
ID NAME             STATUS     PATH                           BRAND    IP    
1 ubuntu-16        running    /zones/ubuntu-16               lx       excl  
```
```
==== Nightly distributed build started:   Thu Aug  3 18:25:36 CEST 2017 ====
==== Nightly distributed build completed: Thu Aug  3 19:06:48 CEST 2017 ====
real    0:41:12
/usr/bin/uname
SunOS mars 5.11 omnios-master-79a0d1a8fc i86pc i386 i86pc
number of …
```
=> Joyent merge/2017080301

usr/src/lib/nsswitch/ldap/common/getgrent.c, usr/src/uts/common/brand/lx/os/lx_pid.c
backporting:
- 8543 nss_ldap crashes handling a group with no gidnumber attribute
- OS-6238 panic in lxpr_access
reference PR: https://github.com/omniosorg/illumos-omnios/pull/27, https://github.com/omniosorg/illumos-omnios/pull/28
~~still no feedback on testing (cf. https://github.com/omniosorg/illumos-omnios/issues/26), might leave this open until saturday.~~
=> Backport 20170803

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_aio.c
Weekly merge from `illumos-joyent`.
* none
```
SunOS mars 5.11 omnios-joyent-merge-2017081001-9d5345697f i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Aug 10 16:56:30 CEST 2017 ====
==== Nightly distributed build completed: Thu Aug 10 17:37:44 CEST 2017 ====
real    0:41:13
/usr/bin/uname
SunOS mars 5.11 omnios-master-79a0d1a8fc i86pc i386 i86pc …
```
=> Joyent merge/2017081001

usr/src/lib/brand/lx/lx_support/Makefile, usr/src/lib/brand/lx/zone/Makefile
A `dmake clobber` leaves some lx-related .po files behind:
```
?? usr/src/lib/brand/lx/lx_support/lx_support.po
?? usr/src/lib/brand/lx/zone/lx_boot.po
?? usr/src/lib/brand/lx/zone/lx_boot_zone_busybox.po
?? usr/src/lib/brand/lx/zone/lx_boot_zone_debian.po
?? usr/src/lib/brand/lx/zone/lx_boot_zone_redhat.po
?? usr/src/lib/brand/lx/zone/lx_boot_zone_ubuntu.po
?? usr/src/lib/brand/lx/zone/lx_install.po
?? usr/src/lib/brand/lx/zone/lx_zone.po
```
=> dmake clobber leaves lx brand objects behind

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_pipe.c
None
```
==== Nightly distributed build started:   Thu Aug 24 14:22:46 UTC 2017 ====
==== Nightly distributed build completed: Thu Aug 24 15:32:57 UTC 2017 ====
real    1:10:11
/usr/bin/uname
SunOS build 5.11 omnios-r151022-5e982daae6 i86pc i386 i86pc
openjdk full version "1.7.0_101-b00"
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009
/usr/ccs/bin/ld
ld: …
```
=> Joyent merge/2017082401

usr/src/Makefile.master, usr/src/tools/scripts/onu.sh.in
This change makes `illumos-omnios` publish packages using the `omnios` publisher instead of `on-nightly`.
This means that the post-processing step of changing the publisher can be avoided in `omnios-build` - see https://github.com/omniosorg/omnios-build/pull/169.
ONU is also smoother since all that changes is the origin of the `omnios` publisher and the signature policy.
This also fixes a small bug in `onu` where the brand check did not work.
Example output showing bug:
```
/opt/onbld/bin/onu[128]: [: ']' missing
WARNING: Use of onu(1) will prevent use of zone attach in the new BE
See onu(1)
Updating zone alpine
pkg: No image rooted at '/tmp/onu.g_aW53/data/zone/alpine/root'
pkg: No image rooted at '/tmp/onu.g_aW53/data/zone/alpine/root'
```
=> Use omnios as the default package publisher

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/syscall/lx_ioctl.c, usr/src/uts/common/brand/lx/syscall/lx_pipe.c
Upstream merge from `illumos-joyent`.
* none
```
SunOS mars 5.11 omnios-joyent-merge-2017083101-a9d1b8e6ee i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Aug 31 16:00:44 CEST 2017 ====
==== Nightly distributed build completed: Thu Aug 31 16:42:54 CEST 2017 ====
real    0:42:10
/usr/bin/uname
SunOS mars 5.11 omnios-master-d667e00233 i86pc i386 i86pc
32-bit …
```
=> Joyent merge/2017083101

README.OmniOS, usr/src/uts/common/brand/lx/io/lx_netlink.c, usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/brand/lx/syscall/lx_pipe.c, usr/src/uts/common/fs/fifofs/fifosubr.c, usr/src/uts/common/fs/fifofs/fifovnops.c, usr/src/uts/common/fs/proc/prvnops.c, usr/src/uts/common/sys/fs/fifonode.h
None
```
==== Nightly distributed build started:   Thu Sep  7 20:39:31 UTC 2017 ====
==== Nightly distributed build completed: Thu Sep  7 21:41:32 UTC 2017 ====
real    1:02:00
/usr/bin/uname
SunOS build 5.11 omnios-r151022-5e982daae6 i86pc i386 i86pc
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009
/usr/ccs/bin/ld
ld: …
```
=> Joyent merge/2017090701

usr/src/pkg/manifests/system-library.mf
Used by pkg(5) to handle the hardware capability mounts.
Without this attribute, `pkg verify` always detects a problem in libc.so.1 and `pkg repair` always creates a new BE.
```
% pkg verify system/library
PACKAGE                                                                 STATUS
pkg://omnios/system/library                                              ERROR
file: lib/libc.so.1
ERROR: ELF content hash: aca8a62ca6198278c21c57931632d504d95d05f6 should be aab836b8552af9e009dbddffdb303881626222c1
```
=> Add mountpoint=true attribute to /lib/libc.so.1

usr/src/pkg/manifests/system-library.mf
Nightly failed..
`pkgfmt: error: manifests/system-library.mf is not in pkgfmt form`
=> Keys must be in alphabetical order

README.OmniOS, usr/src/lib/brand/lx/lx_init/lxinit.c, usr/src/lib/smbsrv/libsmb/common/smb_kmod.c, usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/fs/smbclnt/netsmb/smb_conn.h, usr/src/uts/common/fs/smbclnt/netsmb/smb_dev.c, usr/src/uts/common/fs/smbsrv/smb_init.c, usr/src/uts/common/smbsrv/smb_ioctl.h
Weekly joyent merge
* OS-6298 SMB client assumes serialized ioctls …
* OS-6297 SMB server ioctls should be appropriately sized … 
* OS-6319 Fix for OS-6297 forgot smb_ioc_svcenum_t …
```
SunOS bloody 5.11 omnios-joyent_merge-2017092101-1fe1b1faaf i86pc i386 i86pc
```
```
bloody% pfexec zlogin alpine
[Connected to zone 'alpine' pts/2]
_|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
|__|   `--'  `-' `;-| `-' '  ' `-'
/  ;  Instance (Alpine Linux 3.5 20170303)
`-'   https://docs.joyent.com/images/container-native-linux
localhost:~#
```
## mail_msg
```
==== Nightly distributed build started:   Thu Sep 21 16:57:42 UTC 2017 ====
==== Nightly distributed build completed: Thu Sep 21 17:21:17 UTC 2017 ====
==== Total build time …
```
=> Joyent merge/2017092101

usr/src/lib/brand/lx/lx_init/lxinit.c
this fixes the following lint warning:
`"lxinit.c", line 813: warning: non-constant initializer: op "U&" (E_NON_CONST_INIT)`
similar to how it has been done here:
https://github.com/omniosorg/illumos-omnios/blob/dbbdc0c68668ec9f0d8710905eb02ef10aa8d818/usr/src/lib/brand/lx/lx_init/lxinit.c#L211-L220
=> fix lint warning

usr/src/tools/scripts/onu.sh.in
ONU currently prints an error message and fails to update any zones in the new BE:
```
...
Activated successfully
Unmounted successfully
zoneadm: root path must be a directory.
```
because the BE is unmounted too early.
=> Fix zone update during onu

usr/src/lib/libscf/common/error.c, usr/src/lib/libscf/common/lowlevel.c
See also https://www.illumos.org/issues/8688
This is a bug fix for two broken behaviours in `svcadm` that were introduced in https://www.illumos.org/issues/5021
These are:
* svcadm no longer accepts multiple partial FMRI arguments (this has also been reported under https://www.illumos.org/issues/5593);
* If a wildcard FMRI is specified as an argument, then other arguments containing partial FMRIs are permitted to match multiple services.
```
==== Nightly distributed build started:   Tue Oct  3 09:09:29 UTC 2017 ====
==== Nightly distributed build completed: Tue Oct  3 09:36:22 UTC 2017 ====
real    0:26:52
/usr/bin/uname
number of …
```
=> 8688 svcadm does not handle multiple partial FMRI arguments

README.OmniOS, usr/src/cmd/mdb/common/modules/genunix/genunix.c, usr/src/cmd/mdb/common/modules/genunix/thread.c, usr/src/cmd/mdb/common/modules/genunix/thread.h, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_misc.h, usr/src/uts/common/brand/lx/sys/lx_syscalls.h, usr/src/uts/common/brand/lx/syscall/lx_prctl.c, usr/src/uts/common/brand/lx/syscall/lx_rw.c, usr/src/uts/common/brand/lx/syscall/lx_socket.c, usr/src/uts/common/brand/lx/syscall/lx_splice.c, usr/src/uts/common/disp/thread.c, usr/src/uts/common/fs/fifofs/fifovnops.c, usr/src/uts/common/sys/fs/fifonode.h, usr/src/uts/common/sys/thread.h, usr/src/uts/common/vm/seg.h, usr/src/uts/intel/Makefile.files
Weekly Joyent merge.
Commit 7eadfb6 is noteworthy as it's a tiny bit of the stack clash mitigation that was committed to Joyent this week. We're not taking that commit but are taking just enough of it to ensure that our lx brand does not break once this lands in gate. This will also be backported to r151022 as we will want to backport the stack clash fix once it comes in.
*  Add S_HOLE vm segment flag & hole skip in lx - 7eadfb6
```
==== Nightly distributed build started:   Thu Oct  5 17:31:23 UTC 2017 ====
==== Nightly distributed build completed: Thu Oct  5 18:31:55 UTC 2017 ====
real    1:00:31
/usr/bin/uname
number of …
```
=> Joyent merge/2017100501

usr/src/tools/env/omnios-illumos-gate.sh
Change required to the template file for anyone that wants to build stock illumos-gate on bloody (and on r151024 once it's released).
=> Update perl version in template nightly gate.env

usr/src/cmd/auditrecord/audit_record_attr.txt, usr/src/lib/libbsm/audit_event.txt
backporting so the updated `sudo` (see https://github.com/omniosorg/omnios-build/pull/271) works
=> 8309 libbsm should support AUE_sudo audit event

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/lx_brand.c, usr/src/lib/brand/lx/lx_brand/common/signal.c, usr/src/lib/brand/lx/lx_brand/common/time.c, usr/src/lib/brand/lx/lx_brand/sys/lx_syscall.h, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_misc.c, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_syscalls.h, usr/src/uts/common/brand/lx/sys/lx_userhz.h, usr/src/uts/common/brand/lx/syscall/lx_time.c, usr/src/uts/intel/Makefile.files
* none
```
SunOS mars 5.11 omnios-joyent_merge-2017101201-93ef14efe7 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct 12 17:36:08 CEST 2017 ====
==== Nightly distributed build completed: Thu Oct 12 18:35:21 CEST 2017 ====
real    0:59:12
/usr/bin/uname
SunOS mars 5.11 omnios-master-5975598b2d i86pc i386 i86pc …
```
=> Joyent merge/2017101201

usr/src/pkg/manifests/consolidation-man-man-incorporation.mf, usr/src/pkg/manifests/driver-network-llc2.mf, usr/src/pkg/manifests/service-network-snmp-mibiisa.mf, usr/src/pkg/manifests/source-network-pppdump.mf, usr/src/pkg/manifests/source-security-tcp-wrapper.mf, usr/src/pkg/manifests/system-library-storage-scsi-plugin.mf, usr/src/pkg/manifests/system-management-snmp-sea.mf, usr/src/pkg/manifests/system-manual.mf
There are a 25 obsoleted packages in `illumos-omnios` but 8 of those use an old ONNV build number in their package version which causes them to be thrown away due to the integrity checking performed by `pkgmgr`.
Fixing this for bloody & r151024. We may stop publishing these altogether in a future release
(I've put it on the project board for r151026 so we think about it then).
=> Publish obsoleted packages with correct ONNV build number

usr/src/pkg/manifests/consolidation-man-man-incorporation.mf, usr/src/pkg/manifests/system-library-storage-scsi-plugin.mf
Changing the obsolete package build numbers shortened the version lines and now `pkgfmt` is unhappy!
=> Remove continuation lines that upset pkgfmt

usr/src/cmd/mdb/common/modules/genunix/genunix.c, usr/src/cmd/mdb/common/modules/genunix/zone.c, usr/src/cmd/mdb/common/modules/genunix/zone.h, usr/src/cmd/zoneadmd/vplat.c, usr/src/cmd/zoneadmd/zoneadmd.c, usr/src/cmd/zoneadmd/zoneadmd.h, usr/src/head/zone.h, usr/src/lib/libc/port/sys/zone.c, usr/src/man/man1m/zoneadm.1m, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/zone.h
This completes a feature that is partially merged from Joyent into OmniOS, a non-changing ID for zones (a debug ID). It also fixes the `zoneadm` man page to reflect the extra field that is (already) shown in parseable output on OmniOS versus vanilla illumos.
It looks like Joyent had a couple of ideas here. Zone IDs are arbitrary and change between reboots and other operations, so they first tried to make the zone ID persistent across reboots (OS-180) but reverted this fairly quickly (OS-192) and created a persistent non-changing ID attached to each zone, the _debug zone id_. With OS-192 this was derived from the zone's location within the `/etc/zones/index` file but as of OS-200 this is stored in the zone's XML configuration file with the _debugid_ tag and the last assigned ID is stored …
=> Use debug zone ID.

usr/src/tools/scripts/nightly.sh
This bit of build output changes on each build and is unnecessary noise in the mail_msg.
There are lots of existing output exclusions in `nightly` - add this one.
=> Exclude maximum offset changes from build noise

usr/src/cmd/mdb/common/modules/genunix/memory.c, usr/src/uts/common/Makefile.files, usr/src/uts/common/exec/elf/elf.c, usr/src/uts/common/fs/proc/prioctl.c, usr/src/uts/common/fs/proc/prsubr.c, usr/src/uts/common/os/exec.c, usr/src/uts/common/os/grow.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/proc.h, usr/src/uts/common/sys/zone.h, usr/src/uts/common/vm/seg_hole.c, usr/src/uts/common/vm/seg_hole.h, usr/src/uts/common/vm/vm_as.c, usr/src/uts/i86pc/vm/vm_machdep.c
This is a merge of the stack-clash mitigation from Joyent. I've also taken a small earlier change of theirs which adds an absolute limit on user-space segments in a process address space; in addition to being a good enhancement, it makes the following merge cleaner.
I expect them to upstream the stack-clash mitigation in due course but I want to get this into bloody early so we can get experience with it prior to considering any back porting. It is a potential security vulnerability after all.
Since we regularly perform full builds in bloody, it will get some good exercise there.
```
==== Nightly distributed build started:   Wed Oct 18 13:05:57 UTC 2017 ====
==== Nightly distributed build completed: Wed Oct 18 14:08:02 UTC 2017 ====
real    1:02:05
==== Build …
```
=> Stack-clash mitigation

usr/src/man/man1m/zoneadm.1m
partial backport of: https://github.com/omniosorg/illumos-omnios/pull/80
although `debugid` is not used in r151024, it should still be documented since it is part of `zoneadm list -p` output.
=> Update man page to include information on the debug zone ID

README.OmniOS, usr/src/cmd/prstat/prstat.c, usr/src/cmd/prstat/prstat.h, usr/src/cmd/prstat/prutil.c, usr/src/cmd/zoneadmd/mcap.c, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/man/man1m/prstat.1m, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_misc.h, usr/src/uts/common/brand/lx/syscall/lx_prctl.c, usr/src/uts/common/brand/lx/syscall/lx_rlimit.c, usr/src/uts/common/brand/lx/syscall/lx_sysinfo.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/vm_usage.h, usr/src/uts/common/sys/zone.h, usr/src/uts/common/syscall/sysconfig.c, usr/src/uts/common/vm/page.h, usr/src/uts/common/vm/vm_usage.c, usr/src/uts/i86pc/os/startup.c, usr/src/uts/i86pc/vm/hment.c, usr/src/uts/sfmmu/vm/hat_sfmmu.c
additionally cherry-picked two commits that were missing:
- OS-1024 sysconfig(_CONFIG_AVPHYS_PAGES) extremely slow inside zones
- OS-987 vmu_calculate_proc() impeding page faults for thousands of sec…
in addition to being a good enhancemen, it makes the following merge clean.
* none
* all
```
SunOS mars 5.11 omnios-joyent_merge-2017101901-a3f17c1781 i86pc i386 i86pc
hadfl@mars:~$ sudo zlogin ubuntu-16
[Connected to zone 'ubuntu-16' pts/2]
Last login: Thu Oct 19 19:51:46 UTC 2017 from zone:global on pts/3
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.3.0 x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
_| …
```
=> Joyent merge/2017101901

usr/src/lib/libscf/common/error.c, usr/src/lib/libscf/common/lowlevel.c, usr/src/man/man1m/svcadm.1m, usr/src/man/man7d/i40e.7d, usr/src/pkg/manifests/driver-network-i40e.mf, usr/src/pkg/manifests/driver-storage-mpt_sas.mf, usr/src/uts/common/io/i40e/i40e_main.c, usr/src/uts/common/io/i40e/i40e_sw.h, usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_impl.c, usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_init.c, usr/src/uts/common/sys/scsi/adapters/mpt_sas/mptsas_var.h, usr/src/uts/common/xen/io/xnf.c, usr/src/uts/common/xen/io/xnf.h, usr/src/uts/i86pc/os/startup.c
Backports from weekly upstream merge.
```
==== Nightly distributed build started:   Thu Oct 19 19:28:18 UTC 2017 ====
==== Nightly distributed build completed: Thu Oct 19 20:32:30 UTC 2017 ====
real    1:04:12
/usr/bin/uname
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 …
```
=> Backports/20171019 (r151024)

usr/src/uts/common/io/vioblk/vioblk.c, usr/src/uts/common/io/virtio/virtio.c, usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/os/pc_hvm.c, usr/src/uts/i86pc/sys/pc_hvm.h
in order to be able to build the latest `illumos-kvm` we need to support HVM exclusion lock:
- OS-6400 want HVM exclusion lock
additionally cherry-picked:
- OS-6389 buffer freed to wrong cache in virtio_register_intx
- OS-6405 vioblk attach doesn't always fail when it should
verified that the latest `illumos-kvm` builds successfully.
- all
```
SunOS mars 5.11 omnios-hvm-0b3669d64a i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Oct 20 15:51:51 CEST 2017 ====
==== Nightly distributed build completed: Fri Oct 20 16:55:03 CEST 2017 ====
real    1:03:12
/usr/bin/uname
SunOS mars 5.11 omnios-master-00b591cca2 i86pc i386 i86pc
number of concurrent …
```
=> HVM exclusion lock

usr/src/cmd/prstat/prstat.c, usr/src/cmd/prstat/prstat.h, usr/src/cmd/prstat/prutil.c, usr/src/cmd/zoneadmd/mcap.c, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/man/man1m/prstat.1m, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_misc.h, usr/src/uts/common/brand/lx/syscall/lx_prctl.c, usr/src/uts/common/brand/lx/syscall/lx_rlimit.c, usr/src/uts/common/brand/lx/syscall/lx_sysinfo.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/vm_usage.h, usr/src/uts/common/sys/zone.h, usr/src/uts/common/syscall/sysconfig.c, usr/src/uts/common/vm/page.h, usr/src/uts/common/vm/vm_usage.c, usr/src/uts/i86pc/os/startup.c, usr/src/uts/i86pc/vm/hment.c, usr/src/uts/sfmmu/vm/hat_sfmmu.c
Backports from weekly `illumos-joyent` merge (see https://github.com/omniosorg/illumos-omnios/pull/84)
```
hadfl@r151024:~$ uname -a
SunOS r151024 5.11 omnios-backports-20171019_lx-fb6df6b1e2 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct 19 23:48:59 CEST 2017 ====
==== Nightly distributed build completed: Fri Oct 20 00:51:45 CEST 2017 ====
real    1:02:46
/usr/bin/uname
SunOS r151024 5.11 omnios-r151024-a65cbf9c46 i86pc i386 i86pc
cw version 1.30 (SHADOW …
```
=> Backports/20171019_lx (r151024)

usr/src/uts/common/io/vioblk/vioblk.c, usr/src/uts/common/io/virtio/virtio.c, usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/os/pc_hvm.c, usr/src/uts/i86pc/sys/pc_hvm.h
backport for https://github.com/omniosorg/illumos-omnios/pull/89
```
hadfl@r151024:~$ uname -a
SunOS r151024 5.11 omnios-hvm_r24-9e8b38e55d i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Oct 20 17:55:44 CEST 2017 ====
==== Nightly distributed build completed: Fri Oct 20 18:56:15 CEST 2017 ====
real    1:00:30
/usr/bin/uname
SunOS r151024 5.11 omnios-r151024-a65cbf9c46 i86pc i386 i86pc
gcc …
```
=> HVM exclusion lock (r151024)

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/os/lx_misc.c
`OS-6338 panic from kvm_load_gs` to r151024
```
==== Nightly distributed build started:   Thu Oct 26 18:35:44 UTC 2017 ====
==== Nightly distributed build completed: Thu Oct 26 19:37:48 UTC 2017 ====
real    1:02:04
/usr/bin/uname
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 …
```
=> Joyent merge/2017102601

usr/src/uts/common/brand/lx/os/lx_misc.c
OS-6338 panic from kvm_load_gs
Backport from weekly merge
#92
=> Joyent backports (r151024)

usr/src/uts/common/io/comstar/port/iscsit/iscsit.c, usr/src/uts/common/io/comstar/port/iscsit/iscsit.h, usr/src/uts/common/io/idm/idm_so.c
Weekly upstream for backport/2017103002
I've only tested basic iSCSI target functionality with this change but it has been reviewed and incorporated into gate so should be safe for r151022.
```
==== Nightly distributed build started:   Mon Oct 30 23:00:02 UTC 2017 ====
==== Nightly distributed build completed: Tue Oct 31 00:06:19 UTC 2017 ====
real    1:06:16
/usr/bin/uname
primary: …
```
=> Upstream merge backport/2017103002

README.OmniOS
'8648 Fix range locking in ZIL commit codepath' will be part of `r151022y`
=> remove pending zfs patches to README.OmniOS

usr/src/boot/lib/libstand/Makefile.inc, usr/src/boot/lib/libstand/ip.c, usr/src/boot/lib/libstand/net.h, usr/src/boot/lib/libstand/udp.c, usr/src/cmd/fm/dicts/DISK.dict, usr/src/cmd/fm/dicts/DISK.po, usr/src/cmd/fm/eversholt/files/common/disk.esc, usr/src/cmd/fm/modules/common/disk-monitor/disk_monitor.c, usr/src/cmd/fm/modules/common/disk-monitor/diskmon_conf.h, usr/src/cmd/fm/modules/common/disk-transport/disk-transport.conf, usr/src/cmd/fm/modules/common/disk-transport/disk_transport.c, usr/src/cmd/fm/modules/common/zfs-retire/zfs-retire.conf, usr/src/cmd/fm/modules/common/zfs-retire/zfs_retire.c, usr/src/cmd/mdb/common/modules/zfs/zfs.c, usr/src/lib/fm/libdiskstatus/common/ds_impl.h, usr/src/lib/fm/libdiskstatus/common/ds_scsi.c, usr/src/lib/fm/libdiskstatus/common/ds_scsi.h, usr/src/lib/fm/libdiskstatus/common/libdiskstatus.c, usr/src/uts/common/sys/fm/io/disk.h, usr/src/uts/common/sys/fm/io/scsi.h
* none
```
SunOS mars 5.11 omnios-upstream_merge-2017110201-eab15b66eb i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Nov  2 09:52:44 CET 2017 ====
==== Nightly distributed build completed: Thu Nov  2 10:54:09 CET 2017 ====
real    1:01:25
/usr/bin/uname
SunOS mars 5.11 omnios-master-f81a14270f i86pc i386 i86pc …
```
=> Upstream merge/2017110201

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_socket.c
Weekly upstream for joyent_merge/2017110201
* none
```
SunOS mars 5.11 omnios-joyent_merge-2017110201-8f066370cd i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Nov  2 11:30:35 CET 2017 ====
==== Nightly distributed build completed: Thu Nov  2 12:32:06 CET 2017 ====
real    1:01:30
/usr/bin/uname
SunOS mars 5.11 omnios-master-f81a14270f i86pc i386 i86pc …
```
=> Upstream merge joyent_merge/2017110201

usr/src/boot/lib/libstand/nfs.c, usr/src/boot/sys/boot/common/bootstrap.h, usr/src/boot/sys/boot/common/disk.c, usr/src/boot/sys/boot/common/multiboot2.c, usr/src/boot/sys/boot/efi/include/efi.h, usr/src/boot/sys/boot/efi/libefi/efipart.c, usr/src/boot/sys/boot/efi/loader/copy.c, usr/src/boot/sys/boot/i386/libi386/Makefile, usr/src/boot/sys/boot/i386/libi386/i386_copy.c, usr/src/boot/sys/boot/i386/libi386/libi386.h, usr/src/boot/sys/boot/i386/loader/main.c, usr/src/boot/sys/boot/zfs/zfs.c, usr/src/lib/fm/libdiskstatus/common/ds_scsi.c, usr/src/man/man3ext/sendfile.3ext, usr/src/man/man3ext/sendfilev.3ext, usr/src/man/man5/pxeboot.5, usr/src/pkg/manifests/driver-network-iwh.mf, usr/src/pkg/manifests/driver-network-iwn.mf, usr/src/uts/common/fs/zfs/dsl_pool.c, usr/src/uts/common/fs/zfs/zfs_ioctl.c, usr/src/uts/common/io/myri10ge/drv/myri10ge.c, usr/src/uts/common/io/myri10ge/drv/myri10ge_lro.c
Weekly upstream for upstream_merge/2017110801
None
```
SunOS bloody 5.11 omnios-upstream_merge-2017110801-8f6134fa70 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Nov  8 14:19:30 GMT 2017 ====
==== Nightly distributed build completed: Wed Nov  8 15:59:53 GMT 2017 ====
real    1:40:22
/usr/bin/uname
SunOS bloody 5.11 omnios-master-f81a14270f i86pc i386 i86pc …
```
=> Upstream merge upstream_merge/2017110801

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_prctl.c, usr/src/uts/i86pc/io/pcplusmp/apic_common.c, usr/src/uts/i86pc/os/cpuid.c, usr/src/uts/intel/sys/x86_archext.h
Weekly upstream for joyent_merge/2017112401
I've also back-ported support for enabling MSI-X when running as a guest under bhyve.
None
```
SunOS bloody 5.11 omnios-joyent_merge-2017112401-a3deab6af3 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Nov 24 09:14:50 GMT 2017 ====
==== Nightly distributed build completed: Fri Nov 24 10:42:40 GMT 2017 ====
real    1:27:50
/usr/bin/uname
SunOS bloody 5.11 omnios-master-0e8f6280a5 i86pc i386 i86pc
cw …
```
=> Upstream merge joyent_merge/2017112401

usr/src/boot/lib/libstand/bootp.c, usr/src/boot/lib/libstand/bootp.h, usr/src/boot/lib/libstand/net.h, usr/src/boot/sys/boot/common/dev_net.c, usr/src/tools/scripts/nightly.sh, usr/src/uts/common/dtrace/dtrace.c
forgot these bits when doing the weekly upstream from `illumos-gate`
* TBD
```
SunOS mars 5.11 omnios-upstream_merge-2017113002-64edc34206 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Nov 30 22:29:48 CET 2017 ====
==== Nightly distributed build completed: Thu Nov 30 23:30:57 CET 2017 ====
real    1:01:09
/usr/bin/uname
SunOS mars 5.11 omnios-master-0e8f6280a5 i86pc i386 i86pc
primary: …
```
=> Upstream merge/2017113002

usr/src/uts/common/dtrace/dtrace.c
backporting `8880 improve DTrace error checking`
see: https://github.com/omniosorg/illumos-omnios/pull/111
=> 8880 improve DTrace error checking (r22)

usr/src/uts/common/dtrace/dtrace.c
backporting `8880 improve DTrace error checking`
see: https://github.com/omniosorg/illumos-omnios/pull/111
=> 8880 improve DTrace error checking (r24)

usr/src/pkg/manifests/SUNWcs.mf
`mailwrapper` can be installed optionally on OmniOS but is not required.
see: https://github.com/omniosorg/omnios-build/pull/428
=> mailwrapper is optional; not required for OmniOS

README.OmniOS, usr/src/lib/brand/lx/testing/ltp_skiplist, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_ptrace.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
* none
```
builder@omniosce:~$ uname -a
SunOS omniosce 5.11 omnios-joyent_merge-2017120701-bd1642d264 i86pc i386 i86pc
... lx test pending
```
```
==== Nightly distributed build started:   Thu Dec  7 18:30:36 CET 2017 ====
==== Nightly distributed build completed: Thu Dec  7 19:58:54 CET 2017 ====
real    1:28:17
/usr/bin/uname
SunOS omniosce 5.11 omnios-master-d10da2a236 i86pc i386 i86pc
primary: …
```
=> Joyent merge/2017120701

README.OmniOS, usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/syscall/lx_mount.c, usr/src/uts/common/brand/lx/sysfs/lx_syssubr.c
Weekly upstream for joyent_merge/2017121401
None.
```
SunOS bloody 5.11 omnios-joyent_merge-2017121401-8d2a72fdf4 i86pc i386 i86pc
```
Before:
```
[Connected to zone 'alpine' pts/2]
_|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
|__|   `--'  `-' `;-| `-' '  ' `-'
/  ;  Instance (Alpine Linux 3.5 20170303)
`-'   https://docs.joyent.com/images/container-native-linux
localhost:~# cat /proc/mounts
/dev/zfsds0 / zfs rw 0 0
devtmpfs /dev devtmpfs rw 0 0
proc /proc proc rw 0 0
tmpfs /run tmpfs rw 0 0
tmpfs /dev/shm tmpfs rw 0 0
/native/usr /native/usr zfs ro 0 0
```
After:
```
localhost:~# cat /proc/mounts
/dev/zfsds0 / zfs rw,nodevices,setuid,nonbmand,exec,atime 0 0
devtmpfs /dev devtmpfs rw 0 0
proc /proc proc rw,nodevices …
```
=> Upstream merge joyent_merge/2017121401

usr/src/man/man1/adb.1, usr/src/man/man1/kmdb.1, usr/src/man/man1/mdb.1, usr/src/man/man1m/kadb.1m, usr/src/man/man3malloc/umem_alloc.3malloc, usr/src/man/man3malloc/umem_debug.3malloc, usr/src/pkg/manifests/system-test-zfstest.mf, usr/src/test/zfs-tests/tests/functional/slog/slog_015_neg.ksh, usr/src/uts/common/fs/zfs/sys/zil.h, usr/src/uts/common/fs/zfs/sys/zil_impl.h, usr/src/uts/common/fs/zfs/sys/zio.h, usr/src/uts/common/fs/zfs/zfs_znode.c, usr/src/uts/common/fs/zfs/zil.c, usr/src/uts/common/fs/zfs/zio.c, usr/src/uts/i86pc/io/amd_iommu/amd_iommu_acpi.h
* none
* 8909 8585 can cause a use-after-free kernel panic
* 8930 zfs_zinactive: do not remove the node if the filesystem is readonly 
```
SunOS mars 5.11 omnios-upstream_merge-2017122101-a47903e951 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Dec 21 10:32:41 CET 2017 ====
==== Nightly distributed build completed: Thu Dec 21 11:33:40 CET 2017 ====
real    1:00:59
/usr/bin/uname
SunOS mars 5.11 omnios-master-9e595b51c7 i86pc i386 i86pc
64-bit …
```
=> Upstream merge/2017122101

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/clone.c, usr/src/lib/brand/lx/lx_brand/common/fork.c, usr/src/lib/brand/lx/lx_brand/common/signal.c, usr/src/lib/brand/lx/lx_brand/sys/lx_misc.h, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_ptrace.c, usr/src/uts/common/brand/lx/sys/lx_brand.h, usr/src/uts/common/os/sig.c
* none
```
SunOS mars 5.11 omnios-joyent_merge-2017122101-bbcfab8708 i86pc i386 i86pc
hadfl@mars:~$ sudo zlogin ubuntu-16
[Connected to zone 'ubuntu-16' pts/2]
Last login: Thu Dec 14 16:48:23 UTC 2017 from zone:global on pts/3
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.3.0 x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
_|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
|__|   `--'  `-' `;-| `-' '  ' `-'
/  ;  Instance (Ubuntu 16.04 20161213)
`-'   https://docs.joyent.com/images/container-native-linux
```
```
==== Nightly distributed build started:   Thu Dec 21 18:55:20 CET 2017 ==== …
```
=> Joyent merge/2017122101

usr/src/cmd/init/init.c, usr/src/uts/common/os/logsubr.c
Adding the OmniOSce copyright to the boot messages for GZ & NGZ.
(FI :In illumos-joyent they've also removed the Oracle copyright messages entirely but let's keep them in here)
=> Include OmniOSce in copyright output

usr/src/boot/lib/libstand/bootp.c, usr/src/boot/lib/libstand/bootp.h, usr/src/boot/sys/boot/common/dev_net.c, usr/src/boot/sys/boot/efi/boot1/boot1.c, usr/src/boot/sys/boot/efi/include/efiapi.h, usr/src/boot/sys/boot/efi/include/efidevp.h, usr/src/boot/sys/boot/efi/include/efilib.h, usr/src/boot/sys/boot/efi/libefi/libefi.c, usr/src/boot/sys/boot/efi/loader/Makefile, usr/src/boot/sys/boot/efi/loader/efi_main.c, usr/src/lib/libzfs/common/libzfs_dataset.c, usr/src/lib/libzfs/common/libzfs_pool.c, usr/src/man/man1m/zfs.1m, usr/src/man/man1m/zpool.1m, usr/src/man/man5/pxeboot.5, usr/src/pkg/manifests/driver-network-cxgbe.mf, usr/src/tools/btxld/btxld.c, usr/src/uts/common/fs/smbsrv/smb_kshare.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/smbsrv/smb_ioctl.h, usr/src/uts/i86pc/io/mp_platform_common.c
* none
* 8935 SMB ioctl fixes incomplete
```
SunOS mars 5.11 omnios-upstream_merge-2018010401-5ccbc88aa8 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jan  4 10:59:29 CET 2018 ====
==== Nightly distributed build completed: Thu Jan  4 12:00:49 CET 2018 ====
real    1:01:19
/usr/bin/uname
SunOS mars 5.11 omnios-master-9e595b51c7 i86pc i386 i86pc
primary: …
```
=> Upstream merge/2018010401

usr/src/cmd/svc/milestone/initial-boot, usr/src/cmd/svc/milestone/initial-boot.xml
* Become a dependency of milestone/sysconfig rather than single-user
since sysconfig is designed to collect anything which modifies system
configuration, including IP addresses.
* Do not disable the service immediately following execution, but rather
wait for the next boot.
These changes fix a problem where console-login occasionally fails
to start on the first boot following a fresh installation.
Also removing legacy caiman timezone-setting support since caiman is gone.
=> Update initial-boot service:

usr/src/lib/libdtrace/common/dt_link.c
cherry-picking this dtrace fix from joyent. see:
- https://www.illumos.org/issues/6653
- https://smartos.org/bugview/OS-5946
in order to allow us to update `binutils` post 2.25.x
The fix seems to have originated in FreeBSD - here's their commit message:
> dtrace converts pairs of consecutive underscores in a probe name to dashes.
When dtrace -G processes relocations corresponding to USDT probe sites, it
performs this conversion on the corresponding symbol names prior to looking
up the resulting probe names in the USDT provider definition. However, in
so doing it would actually modify the input object's string table, which
breaks the string suffix merging done by recent binutils. Because we don't
care about the symbol name once the probe site is recorded, just perform the
probe lookup …
=> libdtrace fix

usr/src/uts/common/fs/zfs/spa.c
vdev_alloc() checks the pool version to make sure that the requested parity level is supported. It does this via spa_version() which looks at spa->spa_ubsync.ub_version.
The spa created in spa_import_rootpool() does not currently have the version set which results in vdev_alloc() returning ENOTSUP for parity > 1.
With this fix I've verified booting OmniOS with a raidz, raidz2 & raidz3 root pool.
Pull request opened against OpenZFS - https://github.com/openzfs/openzfs/pull/526
=> 8969 Cannot boot from RAIDZ with parity > 1

README.OmniOS, usr/src/uts/common/fs/zfs/spa.c, usr/src/uts/common/inet/ip/ip.c
Clean build & ONU.
```
==== Nightly distributed build started:   Thu Jan 18 14:38:35 UTC 2018 ====
==== Nightly distributed build completed: Thu Jan 18 15:42:17 UTC 2018 ====
real    1:03:42
/usr/bin/uname
SunOS build 5.11 omnios-r151024-c2a1589567 i86pc i386 i86pc
openjdk full version "1.7.0_151-b01"
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009 …
```
=> Backports 20180118

README.OmniOS, usr/src/uts/common/fs/ufs/ufs_vnops.c, usr/src/uts/common/vm/as.h, usr/src/uts/common/vm/seg_dev.c, usr/src/uts/common/vm/seg_dev.h, usr/src/uts/common/vm/seg_hole.c, usr/src/uts/common/vm/seg_hole.h, usr/src/uts/common/vm/seg_spt.c, usr/src/uts/common/vm/seg_spt.h, usr/src/uts/common/vm/seg_umap.c, usr/src/uts/common/vm/seg_umap.h, usr/src/uts/common/vm/seg_vn.c, usr/src/uts/common/vm/seg_vn.h, usr/src/uts/common/vm/vm_as.c, usr/src/uts/i86xpv/vm/seg_mf.c, usr/src/uts/i86xpv/vm/seg_mf.h
side pull from Joyent to fix an issue with OS-6323.
```
SunOS mars 5.11 omnios-joyent_merge-2018012701-f884b4a5d3 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sat Jan 27 00:02:20 CET 2018 ====
==== Nightly distributed build completed: Sat Jan 27 00:51:49 CET 2018 ====
real    0:49:28
/usr/bin/uname
SunOS mars 5.11 omnios-master-9330622831 i86pc i386 i86pc …
```
=> Joyent merge/2018012701

usr/src/cmd/cmd-inet/usr.lib/wanboot/p12split/p12split.c, usr/src/common/net/wanboot/boot_http.c, usr/src/lib/libkmf/plugins/kmf_openssl/common/openssl_spi.c
This re-synchronises some files with illumos-gate where the only differences are in lint override statements. This will make the openssl 1.1 change branches easier to manage.
still clean:
```
==== Nightly distributed build started:   Wed Jan 31 09:20:44 UTC 2018 ====
==== Nightly distributed build completed: Wed Jan 31 10:11:36 UTC 2018 ====
real    0:50:52
/usr/bin/uname
SunOS build 5.11 omnios-r151024-32f54f0308 i86pc i386 i86pc
primary: …
```
=> Re-synchronise lint overrides to match those in gate.

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_mem.c, usr/src/uts/common/os/grow.c
Weekly upstream for joyent_merge/2018020101
None - the commit is a fix for `OS-6407 lx: move mmap and mremap support in-kernel` which is only in bloody.
Worked and lx zone booted.
```
==== Nightly distributed build started:   Thu Feb  1 23:18:23 GMT 2018 ====
==== Nightly distributed build completed: Fri Feb  2 00:34:59 GMT 2018 ====
real    1:16:35
/usr/bin/uname
SunOS bloody 5.11 omnios-upstream_merge-2018020101-2d34a01d24 i86pc i386 i86pc …
```
=> Upstream merge joyent_merge/2018020101

README.OmniOS, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/sys/lx_userhz.h, usr/src/uts/common/fs/zfs/zfs_zone.c, usr/src/uts/common/os/vm_pageout.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/zone.h, usr/src/uts/common/vm/vm_usage.c
additionally picking:
- `OS-6540 zonehash_lock is hot under a heavy ZFS IO load`
- `OS-6588 zfs_zone IO throttle assertion failure`
* none
```
SunOS mars 5.11 omnios-joyent_merge-2018020801-aed757fb75 i86pc i386 i86pc
hadfl@mars:~$ sudo zlogin ubuntu-16
[Connected to zone 'ubuntu-16' pts/3]
Last login: Thu Jan  4 16:19:22 UTC 2018 from zone:global on pts/2
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.3.0 x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
_|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
|__|   `--'  `-' `;-| `-' '  ' `-'
/  ;  Instance (Ubuntu 16.04 20161213)
`-' …
```
=> Joyent merge/2018020801

README.OmniOS
Weekly upstream for joyent_merge/2018021501
No commits picked this week, just updating last commit hash.
=> Upstream merge joyent_merge/2018021501

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/clone.c, usr/src/lib/brand/lx/lx_brand/common/signal.c, usr/src/lib/brand/lx/lx_brand/common/stack.c, usr/src/pkg/manifests/system-header.mf, usr/src/uts/common/Makefile.files, usr/src/uts/common/fs/dev/sdev_plugin.c, usr/src/uts/common/fs/dev/sdev_subr.c, usr/src/uts/common/fs/dev/sdev_vfsops.c, usr/src/uts/common/io/pciex/pcie.c, usr/src/uts/common/sys/Makefile, usr/src/uts/common/sys/fs/sdev_impl.h, usr/src/uts/common/sys/fs/sdev_plugin.h, usr/src/uts/common/sys/pcie.h, usr/src/uts/common/sys/pcie_impl.h, usr/src/uts/common/vm/vm_page.c, usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/io/apix/apix.c, usr/src/uts/i86pc/io/pcplusmp/apic.c, usr/src/uts/i86pc/io/pcplusmp/apic_common.c, usr/src/uts/i86pc/io/psm/uppc.c, usr/src/uts/i86pc/os/mp_machdep.c, usr/src/uts/i86pc/sys/apic_common.h, usr/src/uts/i86pc/sys/psm_types.h, usr/src/uts/i86pc/sys/smp_impldefs.h, usr/src/uts/i86pc/vm/seg_vmm.c, usr/src/uts/i86pc/vm/seg_vmm.h, usr/src/uts/i86xpv/io/psm/xpv_psm.c, usr/src/uts/i86xpv/io/psm/xpv_uppc.c, usr/src/uts/intel/dev/Makefile
Weekly upstream for joyent_merge/2018022101
None
```
SunOS bloody 5.11 omnios-joyent_merge-2018022101-cb8946e3da i86pc i386 i86pc
bloody% pfexec mdb -k
> sdev_plugin_list::walk sdev_plugin | ::print sdev_plugin_t sp_name
sp_name = [ "rlofi" ]
sp_name = [ "lofi" ]
sp_name = [ "ipnet" ]
sp_name = [ "net" ]
sp_name = [ "zcons" ]
sp_name = [ "zvol" ]
sp_name = [ "vt" ]
sp_name = [ "pts" ]
```
```
==== Nightly distributed build started:   Wed Feb 21 18:40:03 GMT 2018 ====
==== Nightly distributed build completed: Wed Feb 21 19:48:08 GMT 2018 ====
real    1:08:04
/usr/bin/uname
SunOS bloody 5.11 omnios-master-4e54e9404d i86pc i386 i86pc
32-bit …
```
=> Upstream merge joyent_merge/2018022101

usr/src/tools/scripts/nightly.sh
`omni build_world` only shows the start of nightly log message lines so it is not possible to determine which build is in progress. (c.f. the packaging log lines which already include the token near to the start)
=> Move DEBUG/non-DEBUG label to aid "omni bw"

exception_lists/copyright, usr/src/Makefile, usr/src/Makefile.master, usr/src/cmd/cmd-crypto/tpmadm/main.c, usr/src/cmd/fdisk/fdisk.c, usr/src/cmd/sendmail/src/tls.c, usr/src/data/hwdata/Makefile, usr/src/data/hwdata/THIRDPARTYLICENSE.efifixes.descrip, usr/src/data/hwdata/THIRDPARTYLICENSE.efifixes.tmpl, usr/src/data/hwdata/efi.fixes, usr/src/lib/krb5/plugins/preauth/pkinit/pkinit_crypto_openssl.c, usr/src/lib/krb5/plugins/preauth/pkinit/pkinit_crypto_openssl.h, usr/src/lib/libefi/Makefile.com, usr/src/lib/libefi/common/rdwr_efi.c, usr/src/lib/libipsecutil/common/ipsec_libssl_setup.c, usr/src/lib/libkmf/plugins/kmf_openssl/Makefile.com, usr/src/lib/libkmf/plugins/kmf_openssl/common/compat.c, usr/src/lib/libkmf/plugins/kmf_openssl/common/compat.h, usr/src/lib/libkmf/plugins/kmf_openssl/common/openssl_spi.c, usr/src/lib/pkcs11/pkcs11_tpm/Makefile.com, usr/src/lib/pkcs11/pkcs11_tpm/common/tpm_specific.c, usr/src/lib/pkcs11/pkcs11_tpm/common/tpmtok_int.h, usr/src/man/man1m/fdisk.1m, usr/src/man/man3ext/efi_alloc_and_init.3ext, usr/src/pkg/manifests/system-data-hardware-registry.mf, usr/src/tools/scripts/nightly.sh
Integrating a number of changes which are pending upstream. These have been well tested within OmniOS branches but would benefit from soak time in bloody before we have to freeze for r151026.
I've left the individual commits for OpenSSL to aid tracking - these will be squashed when they go upstream.
This branch builds cleanly with openssl 1.0 & 1.1. The below _mail_msg_ is with 1.1 but immediately followed a build with 1.0, hence the library dependency differences in the log.
```
==== Nightly distributed build started:   Mon Feb 26 00:18:03 GMT 2018 ====
==== Nightly distributed build completed: Mon Feb 26 01:28:31 GMT 2018 ====
real    1:10:27
/usr/bin/uname
SunOS bloody 5.11 omnios-pmbr-440a72baca i86pc i386 i86pc …
```
=> Integrate PMBR & OpenSSL 1.1 changes.

usr/src/lib/libbe/common/libbe_priv.h, usr/src/tools/scripts/onu.sh.in
`vm` is a further cut-down version of the sparse `brand` that was experimented with early in this bloody cycle. It is now not going to be used.
=> Remove "vm" brand

usr/src/lib/brand/lx/zone/platform.xml
Tested with debian, ubuntu and alpine zones..
Only difference is that any filesystems mounted under /usr (for example) are no longer accessible (present as an empty directory in the zone).
=> Use nodevices,nosub for lx zone native mounts

usr/src/cmd/prtvtoc/prtvtoc.c, usr/src/man/man1m/prtvtoc.1m, usr/src/uts/common/sys/vtoc.h
=> Add -e flag to prtvtoc to show extended information for EFI

README.OmniOS, usr/src/lib/scsi/plugins/ses/ses2/common/ses2_element.c
Reviewed by: C Fraire <cfraire@me.com>
Reviewed by: Ken Mays <maybird1776@yahoo.com>
Reviewed by: Igor Kozhukhov <igor@dilos.org>
=>  9317 FMD crashes with zero-length allocation (r151024)

usr/src/cmd/bhyve/pci_virtio_block.c
By default, bhyve sets a virtio-blk disk device serial number (and hence device ID) to BHYVE followed by the first 12 digits of the md5 checksum of the backing store. This is much better than what KVM did which was to set a blank serial number, causing problems for things such as the enumeration framework used by `diskinfo`. Recent versions of kvmadm set a serial number based on the disk index by default but allow it to be overridden.
e.g.
```
bhyve% echo '/dev/zvol/rdsk/rpool/hdd-omnios\c' | digest -a md5 | cut -c1-12
a61dba9b18ef
root@omniosce:~# iostat -En | grep Block
Vendor: Virtio Product: Block Device Revision: 0000 Serial No: BHYVE-A61D-BA9B-18EF
root@omniosce:~# prtconf -v /dev/dsk/c3t0d0 | grep -A1 devid
name='devid' type=string items=1
value='id1,kdev@ABHYVE-A61D-BA9B-18EF'
``` …
=> Want option to explicitly set bhyve disk serial number

usr/src/uts/common/io/vioif/vioif.c
Taking an old Joyent commit that stops vioif from putting unecessary messages on the console during boot.
=> OS-4948 vioif should not log to the console on boot, or ever

usr/src/uts/common/io/vioif/vioif.c
Taking an old Joyent commit that stops vioif from putting unecessary messages on the console during boot.
Backport for #189
=> OS-4948 vioif should not log to the console on boot, or ever (r151026)

usr/src/cmd/cmd-inet/usr.bin/netstat/netstat.c, usr/src/cmd/smbsrv/smbd/server.xml, usr/src/man/man1m/netstat.1m, usr/src/tools/scripts/bldenv.sh, usr/src/uts/common/sys/pci.h, usr/src/uts/common/sys/pci_impl.h, usr/src/uts/i86pc/io/vmm/amd/svm.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/intel/vmx.h, usr/src/uts/i86pc/io/vmm/io/ppt.c, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/sys/vmm.h, usr/src/uts/intel/io/pci/pci_boot.c, usr/src/uts/intel/io/pci/pci_pci.c
Backports for r151026 from weekly upstream merge.
* `SUNWcs` - netstat
* `system/kernel` - PCI changes
* `system/kernel/platform` - CTF due to PCI changes
* `service/file-system/smb` - oplocks default to false
* `developer/build/onbld` - bldenv
* `system/bhyve`
```
==== Nightly distributed build started:   Wed Apr 11 13:35:43 GMT 2018 ====
==== Nightly distributed build completed: Wed Apr 11 14:52:54 GMT 2018 ====
real    1:17:11
/usr/bin/uname
SunOS r151026 5.11 omnios-r151026-dff7dcea85 i86pc i386 i86pc
/data/omnios-build/omniosorg/r151026/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW MODE …
```
=> Upstream merge r151026 backports

usr/src/cmd/mdb/i86pc/modules/unix/i86mmu.c, usr/src/cmd/zdb/zdb.c, usr/src/cmd/ztest/ztest.c, usr/src/lib/libzfs/common/libzfs_pool.c, usr/src/lib/libzpool/common/llib-lzpool, usr/src/test/os-tests/doc/README, usr/src/uts/common/fs/autofs/auto_subr.c, usr/src/uts/common/fs/smbclnt/smbfs/smbfs.h, usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vfsops.c, usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vnops.c, usr/src/uts/common/fs/zfs/dsl_scan.c, usr/src/uts/common/fs/zfs/metaslab.c, usr/src/uts/common/fs/zfs/spa.c, usr/src/uts/common/fs/zfs/spa_misc.c, usr/src/uts/common/fs/zfs/sys/vdev_removal.h, usr/src/uts/common/fs/zfs/sys/zio.h, usr/src/uts/common/fs/zfs/vdev.c, usr/src/uts/common/fs/zfs/vdev_indirect.c, usr/src/uts/common/fs/zfs/vdev_label.c, usr/src/uts/common/fs/zfs/vdev_mirror.c, usr/src/uts/common/fs/zfs/vdev_removal.c, usr/src/uts/common/fs/zfs/zio.c
Weekly upstream for upstream_merge/2018041901
To r151026:
* 9434 Speculative prefetch is blocked by device removal code
* 9441 kmdb should stash %cr3 in kdiregs (from last week's merge)
* 9452 ptable_dcmd() needs a little cleanup
* 9462 panic in smbfs_delmap_callback
```
SunOS bloody 5.11 omnios-upstream_merge-2018041901-f072fac1a0 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Apr 19 08:38:48 GMT 2018 ====
==== Nightly distributed build completed: Thu Apr 19 09:50:22 GMT 2018 ====
real    1:11:33
/usr/bin/uname
SunOS bloody 5.11 omnios-master-acb2e0e30f i86pc i386 i86pc …
```
=> Upstream merge upstream_merge/2018041901

usr/src/cmd/zoneadm/svc-zones
The current script attempts to avoid trying to shut down lx zones cleanly, when that will work fine. However the logic is broken (checks wrong field) so that we are already doing shutdown for lx - this PR just cleans up the logic.
In future we should ensure that all new brands support clean shutdown or revisit this file.
=> Fix zone shutdown script

usr/src/cmd/bhyve/pci_passthru.c, usr/src/cmd/boot/bootadm/bootadm.c, usr/src/uts/common/io/nvme/nvme.c, usr/src/uts/i86pc/io/viona/viona.c, usr/src/uts/i86pc/io/vmm/io/ppt.c
- driver/storage/nvme
- SUNWcs
- system/bhyve 
```
==== Nightly distributed build started:   Wed Apr 25 12:46:04 UTC 2018 ====
==== Nightly distributed build completed: Wed Apr 25 15:04:55 UTC 2018 ====
real    2:18:51
/usr/bin/uname
SunOS r151026-build 5.11 omnios-r151026-e80cb0301a i86pc i386 i86pc
gcc …
```
=> Backport 20180425 r26

README.OmniOS, usr/src/cmd/bhyve/pci_passthru.c, usr/src/uts/i86pc/io/viona/viona.c, usr/src/uts/i86pc/io/vmm/io/ppt.c
Weekly upstream from `illumos-joyent`
* BHYVE: OS-6815 viona should pad short frames
* BHYVE: OS-6738 bhyve ppt should not use /dev/mem
* none
```
SunOS mars 5.11 omnios-joyent_merge-2018042501-c0629d90db i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Apr 25 14:25:40 CEST 2018 ====
==== Nightly distributed build completed: Wed Apr 25 15:19:57 CEST 2018 ====
real    0:54:17
/usr/bin/uname
SunOS mars 5.11 omnios-master-acb2e0e30f i86pc i386 i86pc …
```
=> Joyent merge/2018042501

usr/src/uts/i86pc/os/mp_startup.c
=> Prevent logging INVPCID in-use when KPTI is disabled (r151026)

usr/src/uts/i86pc/os/mp_startup.c
When KPTI is disabled, the `x86_use_invpcid` variable remains set to -1 which makes the logging code output:
`May  2 11:27:54 omniosce unix: [ID 551322 kern.info] KPTI disabled (PCID disabled, INVPCID in use)`
Test non-debug build done, requires backport to r151026.
=> Prevent logging INVPCID in-use when KPTI is disabled

usr/src/tools/scripts/nightly.sh
This allows for building older versions of illumos-omnios with the latest `nightly`.
=> Do not consider a missing openssl-version target a compiler failure

README.OmniOS, usr/src/uts/i86pc/io/vmm/intel/vtd.c, usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Weekly upstream for joyent_merge/2018060801
None
```
SunOS bloody 5.11 omnios-joyent_merge-2018060801-260ec7f002 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jun  7 10:12:47 GMT 2018 ====
==== Nightly distributed build completed: Thu Jun  7 11:41:46 GMT 2018 ====
real    1:28:58
/usr/bin/uname
SunOS bloody 5.11 omnios-master-9b1f5bc1cf i86pc i386 i86pc
/data/omnios-build/omniosorg/bloody/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc
/data/omnios-build/omniosorg/bloody/illumos/usr/src/tools/proto …
```
=> Upstream merge joyent_merge/2018060801

usr/src/cmd/mdb/i86pc/modules/unix/amd64/Makefile, usr/src/cmd/mdb/i86pc/modules/unix/sec.c, usr/src/cmd/mdb/i86pc/modules/unix/sec.h, usr/src/cmd/mdb/i86pc/modules/unix/unix.c, usr/src/cmd/mdb/i86xpv/modules/unix/amd64/Makefile
Add ::sec command to mdb to summarise protection against processor security vulnerabilities.
```
% pfexec mdb -ke ::sec
= Meltdown (CVE-2017-5754)
Status: NOT PROTECTED
KPTI is disabled
PCID is not supported by this processor
INVPCID is not supported by this processor
= Lazy FPU (CVE-2018-3665)
Status: PROTECTED
System is using eager FPU register restore
```
```
% pfexec mdb -ke '::sec -p'
meltdown:CVE-2017-5754:not-protected
lazy fpu:CVE-2018-3665:protected
```
```
% pfexec mdb -ke '::help sec'
NAME
sec - print security patch summary
SYNOPSIS
[ addr ] ::sec [-p]
DESCRIPTION
Prints information about the status of kernel protection
against processor vulnerabilities.
-p    Output information in a format suitable for parsing
ATTRIBUTES
Target: kvm
Module: unix
Interface Stability: Unstable …
```
=> Add ::sec command to mdb

usr/src/cmd/grep/grep.c
Backport from bloody, fixes https://github.com/omniosorg/illumos-omnios/issues/229
Before:
```
reaper# prtconf -v | grep -A 1 d@n5000c5007f0373b7
value='id1,sd@n5000c5007f0373b7/a'
name='keyboard-layout' type=string items=1
--
value='id1,sd@n5000c5007f0373b7'
name='inquiry-revision-id' type=string items=1
zsh: broken pipe                       prtconf -v |
zsh: segmentation fault (core dumped)  grep -A 1 d@n5000c5007f0373b7
```
After:
```
reaper# prtconf -v | /data/zone/build/root/data/omnios-build/omniosorg/r151026/illumos/usr/src/cmd/grep/grep -A 1 d@n5000c5007f0373b7
value='id1,sd@n5000c5007f0373b7/a'
name='keyboard-layout' type=string items=1
--
value='id1,sd@n5000c5007f0373b7'
name='inquiry-revision-id' type=string items=1
```
=> grep segfaults when you ask for context (r151026)

usr/src/cmd/boot/bootadm/bootadm.c, usr/src/cmd/boot/scripts/create_ramdisk.ksh
9628 UFS boot archives are too large
This is pending RTI but I would like to get it into bloody ready for the next build. It will speed up boot archive creation/update and also reduce the size of the UFS boot archives.
At present, if a system has `cdrtools` installed, then an HSFS boot archive is created, otherwise a UFS one.
UFS archives have some drawbacks including that it is necessary to create them via lofi and to estimate their size before populating them - also all files are compressed as they are copied in, increasing the time taken to build them. In the future, we may want to look at moving to cpio archives (Unleashed have done this but by stripping the HSFS code out of `bootadm` and modifying the fallback script; we may not want to do it in the same way)
In-progress review for …
=> 9627 No longer need 32-bit boot_archive

usr/src/cmd/boot/bootadm/Makefile, usr/src/cmd/boot/bootadm/bootadm.c, usr/src/cmd/boot/scripts/create_ramdisk.ksh, usr/src/cmd/svc/milestone/boot-archive.xml, usr/src/man/man1m/bootadm.1m, usr/src/uts/common/krtld/bootrd.c, usr/src/uts/common/krtld/bootrd_cpio.c, usr/src/uts/intel/Makefile.files
This is a feature by Josef 'Jeff' Sipek (@jeffpc) to add support for cpio format boot archives. The kernel component is taken from his code in Unleashed with a few minor modifications. The rest (userland + man page) is mine.
At the moment we have the strange situation where boot archives are in UFS format by default unless you have the `cdrtools` package installed at which point they will be HSFS. The UFS archives are actually uncompressed but all of the files within them (apart from unix itself) are compressed with gzip.
Creating a UFS archive is quite slow since it involves estimating the required size, making an empty file, formatting it, mounting through `lofi` then copying the files across. Creating an HSFS archive requires the third-party `mkisofs` utility and also requires that the …
=> Add support for CPIO boot archives

README.OmniOS, usr/src/cmd/mdb/common/modules/genunix/ctxop.c, usr/src/cmd/mdb/common/modules/genunix/ctxop.h, usr/src/compat/freebsd/sys/time.h, usr/src/uts/common/brand/lx/io/lx_netlink.c, usr/src/uts/common/brand/lx/os/lx_audit.c, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/sys/lx_audit.h, usr/src/uts/common/brand/lx/sys/lx_brand.h, usr/src/uts/common/disp/thread.c, usr/src/uts/common/sys/thread.h, usr/src/uts/i86pc/io/vmm/io/ppt.c, usr/src/uts/i86pc/io/vmm/io/vatpit.c, usr/src/uts/i86pc/io/vmm/io/vatpit.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c, usr/src/uts/i86pc/ml/offsets.in, usr/src/uts/i86pc/os/cpuid.c, usr/src/uts/i86pc/os/microcode.c, usr/src/uts/i86pc/os/mlsetup.c, usr/src/uts/i86pc/os/mp_startup.c, usr/src/uts/intel/Makefile.files, usr/src/uts/intel/sys/x86_archext.h
Weekly upstream for joyent_merge/2018070601. Work by @hadfl, lint fix-up by me. 
In particular, please review https://github.com/omniosorg/illumos-omnios/pull/236/commits/a61e4505c38f2bcb12e6948bd5f8a754ae9da28e#diff-1d8f65082d9bd11ff531df25daf21926L1807 - the basic problem is the assignment of a 32-bit value to a 16-bit value within the struct and there are a number of ways to fix the lint warning. I've elected for this as the simplest which should still allow simple merging of any further upstream fixes.
None
```
SunOS bloody 5.11 omnios-joyent_merge-2018070601-861a08c186 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Jul  9 08:48:15 UTC 2018 ====
==== Nightly distributed build completed: Mon Jul  9 09:49:45 UTC 2018 ====
==== Total build time …
```
=> Upstream merge joyent_merge/2018070601

usr/src/cmd/boot/scripts/boot-archive-update.ksh
Now that we only have 64-bit boot archives, we can remove any 32-bit ones from disk during startup.
=> Clean up old 32-bit boot archives

usr/src/lib/libvmmapi/common/vmmapi.c, usr/src/uts/common/brand/lx/io/lx_netlink.c, usr/src/uts/i86pc/io/viona/viona.c, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/intel/kdi/kdi_asm.s, usr/src/uts/intel/kdi/kdi_idt.c
Weekly upstream for joyent_merge/2018071901. Straightforward, no conflicts.
None
```
SunOS bloody 5.11 omnios-joyent_merge-2018071901-de5bff4a2f i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jul 19 08:23:35 GMT 2018 ====
==== Nightly distributed build completed: Thu Jul 19 10:08:49 GMT 2018 ====
real    1:45:13
/usr/bin/uname
SunOS bloody 5.11 omnios-master-01856b5361 i86pc i386 i86pc
/data/omnios-build/omniosorg/bloody/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc …
```
=> Upstream merge joyent_merge/2018071901

usr/src/cmd/mdb/i86pc/modules/unix/unix.c, usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.h, usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.s, usr/src/pkg/manifests/system-test-ostest.mf, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/i386/Makefile, usr/src/test/os-tests/tests/i386/badseg.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/ml/kpti_trampolines.s, usr/src/uts/i86pc/ml/locore.s, usr/src/uts/intel/ia32/os/desctbls.c, usr/src/uts/intel/sys/x86_archext.h
see: https://github.com/omniosorg/illumos-omnios/pull/248
``` 
==== Nightly distributed build started:   Sun Aug 12 15:31:48 UTC 2018 ====
==== Nightly distributed build completed: Sun Aug 12 18:14:47 UTC 2018 ====
real    2:42:58
/usr/bin/uname
SunOS r151026-build 5.11 omnios-r151026-b6848f4455 i86pc i386 i86pc
primary: …
```
=> Backports r26

usr/src/cmd/mdb/i86pc/modules/unix/unix.c, usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.h, usr/src/cmd/mdb/i86pc/modules/unix/unix_sup.s, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/i386/Makefile, usr/src/test/os-tests/tests/i386/badseg.c, usr/src/uts/i86pc/ml/kpti_trampolines.s, usr/src/uts/i86pc/ml/locore.s, usr/src/uts/intel/ia32/os/desctbls.c, usr/src/uts/intel/sys/x86_archext.h
see: https://github.com/omniosorg/illumos-omnios/pull/248
```
==== Nightly distributed build started:   Sun Aug 12 17:56:20 CEST 2018 ====
==== Nightly distributed build completed: Sun Aug 12 18:44:27 CEST 2018 ====
real    0:48:07
/usr/bin/uname
SunOS r151022 5.11 omnios-r151022-89f6242508 i86pc i386 i86pc
/usr/bin/as
as: Sun Compiler Common …
```
=> Backports r22

usr/src/uts/common/fs/zfs/vdev.c
Simple back-port, required to fix https://github.com/omniosorg/kayak/issues/72 for r151026.
=> 9194 mechanism to override ashift at pool creation time

usr/src/pkg/manifests/developer-dtrace.mf
As per https://github.com/omniosorg/omnios-build/issues/991
=> dtrace requires cpp(1) for -C option

README.OmniOS, usr/src/cmd/bhyve/block_if.c, usr/src/cmd/bhyve/block_if.h, usr/src/cmd/bhyve/pci_virtio_block.c, usr/src/cmd/bhyve/pci_virtio_viona.c, usr/src/cmd/bhyve/uart_emul.c, usr/src/compat/freebsd/sys/mutex.h, usr/src/uts/common/disp/thread.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/intel/vmx.h, usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Weekly upstream for joyent_merge/2018081501
* L1TF: OS-7222 thread_create() should ensure ->t_cpu is set 
```
SunOS mars 5.11 omnios-joyent_merge-2018091401-d5ba6e167b i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sat Sep 15 00:22:07 CEST 2018 ====
==== Nightly distributed build completed: Sat Sep 15 01:18:29 CEST 2018 ====
real    0:56:21
/usr/bin/uname
SunOS mars 5.11 omnios-master-36eb49126f i86pc i386 i86pc …
```
=> Joyent merge/2018091401

usr/src/uts/common/sys/ucode.h
Before this commit:
```
omni# ucodeadm -v | head -2
CPU     Microcode Version
0       0x710
```
and after:
```
omni# ucodeadm -v | head -2
CPU     Microcode Version
0       0x714
```
=> 8450 UCODE_MAX_SIZE is too small for modern microcode

README.OmniOS, usr/src/uts/i86pc/io/viona/viona.c
Weekly upstream for joyent merge/2018092701
None
```
SunOS mars 5.11 omnios-joyent_merge-2018092701-a052c517ba i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Sep 27 21:34:01 CEST 2018 ====
==== Nightly distributed build completed: Thu Sep 27 22:24:52 CEST 2018 ====
real    0:50:51
/usr/bin/uname
SunOS mars 5.11 omnios-master-edcaba7bd3 i86pc i386 i86pc
/build/illumos-omnios/usr/src/tools/proto/root_i386-nd/opt/onbld …
```
=> Joyent merge/2018092701

README.OmniOS, usr/src/lib/brand/lx/lx_brand/common/signal.c, usr/src/lib/brand/lx/lx_brand/sys/lx_misc.h, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/sys/lx_brand.h, usr/src/uts/common/brand/lx/syscall/lx_poll.c, usr/src/uts/i86pc/io/viona/viona.c
Weekly upstream for joyent_merge/2018100401
To r151028:
* BHYVE: OS-7255 viona should ignore zero-length descrs  …
* LX: OS-7121 lx vfork and signal handling still racey  …
```
SunOS bloody 5.11 omnios-joyent_merge-2018100401-c6cc2b6b38 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct  4 08:13:15 GMT 2018 ====
==== Nightly distributed build completed: Thu Oct  4 09:53:14 GMT 2018 ====
real    1:39:58
/usr/bin/uname
SunOS bloody 5.11 omnios-master-98a7b6c321 i86pc i386 i86pc
/data/omnios-build/omniosorg/bloody/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc
cw version 1.30 (SHADOW …
```
=> Upstream merge joyent_merge/2018100401

usr/src/cmd/svc/milestone/fs-local, usr/src/cmd/svc/milestone/local-fs.xml, usr/src/lib/libzfs/common/libzfs_mount.c
Adding an escape hatch to disable parallel ZFS mounts in case of any problems for users upgrading to r151028. This /should/ be fixed through #286, but just in case...
=> Add config/parallel to svc:/system/filesystem/local

usr/src/tools/env/omnios-illumos-gate.sh, usr/src/tools/env/omnios-illumos-omnios.sh
We have additional template env files in our tree - `omnios-build-omnios.sh` and `omnios-build-gate.sh`. These have diverged a fair amount from the standard `illumos.sh` including a couple of recent updates to enable shadow compilation with newer gcc versions.
This re-syncs the files and restructures them so that the OmniOS-specific bits are at the bottom.
=> Update template env files following upstream changes

usr/src/lib/libc/port/mapfile-vers
=> New thread-name APIs should be exposed under ILLUMOS_0.28 (r151028)

usr/src/lib/libc/port/mapfile-vers
So that binaries that require these APIs have the correct libc dependency too.
=> New thread-name APIs should be exposed under ILLUMOS_0.28

usr/src/uts/common/io/sata/adapters/ahci/ahci.c
There are several cases where the ahci driver must handle errors and ends up calling the `ahci_mop_commands()` function to mop up pending commands. However, in error cases, the slot_status returned by the driver has bits set for empty slots resulting in a panic due to unreferenced memory access. The reason for the bad slot status is currently unknown, but this change changes ahci_mop_commands() so that empty slots are just ignored.
Here are two different stack traces showing ahci_mop_commands calling ahci_add_doneq with a NULL packet.
```
ffffff00ac8da9c0 ahci_add_doneq+0x14(ffffff17eb3e5000, 0, 1)
ffffff00ac8daa60 ahci_mop_commands+0x148(ffffff17eb3dde40, ffffff17eb3e5000, 0, 1, 0, 0, ffffff0000000000)
ffffff00ac8dab00 ahci_fatal_error_recovery_handler+0x241(ffffff17eb3dde40, …
```
=> 7075 ahci: NULL pointer dereference in ahci_add_doneq()

usr/src/cmd/svc/common/manifest_hash.c
When seeding an SMF database, the paths to the imported manifests end up stored in two places within the repository database:
* The manifestfiles property of the imported service;
* A per-service tree within the `smf/manifest` service.
For example:
```
bloody% cp /lib/svc/seed/global.db /tmp
bloody% export SVCCFG_REPOSITORY=/tmp/global.db
bloody% export SVCCFG_CHECKHASH=1
bloody% svccfg import /kayak_image/r151029/lib/svc/manifest/network/ntp.xml
bloody% svccfg -s ntp listprop manifestfiles
manifestfiles                                                       framework
manifestfiles/kayak_image_r151029_lib_svc_manifest_network_ntp_xml  astring  /kayak_image/r151029/lib/svc/manifest/network/ntp.xml
bloody% svccfg -s manifest listprop | grep ntp …
```
=> Honour PKG_INSTALL_ROOT when building hash filename

usr/src/Makefile.master, usr/src/boot/sys/boot/efi/libefi/delay.c, usr/src/boot/sys/boot/i386/libi386/biosdisk.c, usr/src/boot/sys/boot/i386/loader/main.c, usr/src/lib/cfgadm_plugins/ib/common/cfga_ib.c, usr/src/lib/cfgadm_plugins/sata/common/cfga_sata.c, usr/src/lib/cfgadm_plugins/usb/common/cfga_usb.c, usr/src/uts/Makefile.uts, usr/src/uts/common/io/hook.c, usr/src/uts/intel/asm/cpu.h
* 9941 Noise from cfgadm plugins
None
```
SunOS mars 5.11 omnios-upstream_merge-2018110801-4ab1a7613b i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Nov  8 21:09:06 CET 2018 ====
==== Nightly distributed build completed: Thu Nov  8 22:25:47 CET 2018 ====
real    1:16:41
/usr/bin/uname
SunOS mars 5.11 omnios-master-a55edc60f2 i86pc i386 i86pc
cw version 3.0
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```
=> Upstream merge/2018110801

usr/src/uts/intel/gld/Makefile
Followup to 45166ac4ddc51e436ef237c0470cb5bb5fd00fea adding missing dependency to the `gld` module.
Before:
```
can't load module: Invalid argument
Nov 12 11:15:05 bloody genunix: [ID 819705 kern.notice] /kernel/misc/amd64/gld: undefined symbol
Nov 12 11:15:05 bloody genunix: [ID 826211 kern.notice]  'mac_hcksum_set'
Nov 12 11:15:05 bloody genunix: [ID 819705 kern.notice] /kernel/misc/amd64/gld: undefined symbol
Nov 12 11:15:05 bloody genunix: [ID 826211 kern.notice]  'mac_hcksum_get'
Nov 12 11:15:05 bloody genunix: [ID 472681 kern.notice] WARNING: mod_load: cannot load module 'gld'
```
After:
```
257 fffffffff8054000   c400   -   1  gld (Generic LAN Driver (v2))
```
=> Add missing dependency to gld

usr/src/pkg/manifests/system-header.mf, usr/src/uts/i86pc/sys/Makefile
This header is currently not provided under /usr/platform/i86pc/include/sys/ but is needed for integrating Virtualbox with the HMA framework.
=> Ship sys/hma.h header

usr/src/cmd/pyzfs/Makefile, usr/src/cmd/pyzfs/pyzfs.py, usr/src/pkg/manifests/system-file-system-zfs.mf
and stop shipping the python compiled version. It will still run without it and if run as root the cache file will be created automatically. This avoids the complication of having to ship both python 2 and python 3 compiled versions and reconciling both versions delivering pyzfs.py.
Following this, dependencies in the zfs package no longer include the python2 modules:
```
% pkg contents -mg . zfs | egrep '^depend.*python'
depend fmri=pkg:/runtime/python-35@3.5.6-151029.0 type=require
depend fmri=pkg:/system/library/python/solaris-35@0.5.11-151029.0 type=require
depend fmri=pkg:/system/library/python/zfs-35@0.5.11-151029.0 type=require
depend fmri=system/library/python/zfs-35 type=require
```
=> Switch /usr/lib/zfs/pyzfs.py to python3

usr/src/uts/common/sys/cpu_uarray.h
Fixes
`"/usr/include/sys/cpu_uarray.h", line 63: null dimension: cu_vals`
when building g11n and openjdk.
Build is clean with this change.
=> cpu_array.h - use pointer in place of null dimension array

usr/src/boot/sys/boot/efi/boot1/Makefile.com, usr/src/boot/sys/boot/i386/libi386/pxe.c, usr/src/cmd/mdb/intel/kmdb/kctl/kctl_isadep.c, usr/src/man/man1m/eeprom.1m, usr/src/uts/common/io/consconfig_dacf.c, usr/src/uts/common/os/space.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/consconfig_dacf.h, usr/src/uts/common/sys/consdev.h, usr/src/uts/common/sys/consplat.h, usr/src/uts/common/sys/cpu_uarray.h, usr/src/uts/common/sys/zone.h, usr/src/uts/i86pc/boot/boot_console.c, usr/src/uts/i86pc/dboot/dboot_startkern.c, usr/src/uts/i86pc/io/consplat.c
None
```
SunOS mars 5.11 omnios-upstream_merge-2018112201-ed4add1461 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Nov 22 18:38:42 CET 2018 ====
==== Nightly distributed build completed: Thu Nov 22 19:55:14 CET 2018 ====
real    1:16:32
/usr/bin/uname
SunOS mars 5.11 omnios-master-6ff672c9ac i86pc i386 i86pc
cw version 3.0
shadow: …
```
=> Upstream merge/2018112201

README.OmniOS, usr/src/cmd/bhyve/uart_emul.c
Weekly upstream for joyent merge/2018111601
* BHYVE: OS-7369 full UART FIFO can send bhyve into a spin
None
```
SunOS mars 5.11 omnios-joyent_merge-2018112801-dd5e87d929 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Nov 28 22:07:46 CET 2018 ====
==== Nightly distributed build completed: Wed Nov 28 23:08:32 CET 2018 ====
real    1:00:46
/usr/bin/uname
SunOS mars 5.11 omnios-master-6ff672c9ac i86pc i386 i86pc
cw version 3.0
warranty; not even …
```
=> Joyent merge/2018112801

README.OmniOS, usr/src/cmd/bhyve/block_if.c, usr/src/cmd/bhyve/block_if.h, usr/src/cmd/bhyve/fwctl.c, usr/src/cmd/bhyve/gdb.c, usr/src/cmd/bhyve/pci_ahci.c, usr/src/cmd/bhyve/pci_nvme.c, usr/src/cmd/bhyve/pci_virtio_block.c, usr/src/uts/i86pc/io/vmm/vm/vm_glue.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c, usr/src/uts/i86pc/io/vmm/vmm_zsd.c, usr/src/uts/i86pc/sys/vmm_impl.h
Weekly upstream for joyent merge/2018120701
* BHYVE: OS-7300 bhyve should not sync IO unless necessary
* BHYVE: OS-7397 reduce lock contention in bhyve instr emul 
None
```
SunOS mars 5.11 omnios-joyent_merge-2018120701-12a57e74f2 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Dec  7 19:30:35 CET 2018 ====
==== Nightly distributed build completed: Fri Dec  7 20:31:46 CET 2018 ====
real    1:01:10
/usr/bin/uname
SunOS mars 5.11 omnios-master-02fa6a4e60 i86pc i386 i86pc
cw version 3.0
This is free software; see the …
```
=> Joyent merge/2018120701

usr/src/uts/common/io/scsi/targets/sd.c, usr/src/uts/common/sys/scsi/generic/inquiry.h, usr/src/uts/common/sys/scsi/targets/sddef.h
Here are a couple of fixes from Joyent to fix problems with some hard drive/HBA combinations that mishandle a START STOP UNIT command when using power conditions.
As usual, great overview and writeup in the Joyent bugs:
https://smartos.org/bugview/OS-5709
https://smartos.org/bugview/OS-7313
I've experienced this on a server with an LSI3108 card and some 15K Seagate drives - lots of errors along the form of:
```
Dec  7 15:43:48 xxx genunix: [ID 353554 kern.warning] WARNING: Device /pci@0,0/pci8086,2f02@1/pci1028,1f49@0/sd@d,1 failed to power up.
```
although the disks show up in `diskinfo` and the HBA says everything is fine and spun up.
Confirmed that this fix resolves the problem there, and the commits have been in SmartOS for a couple of years and a month respectively.
Requires …
=> sd fixes for misbehaving drives

usr/src/Makefile.master
Following https://github.com/omniosorg/omnios-build/pull/1186 - illumos needs configuring to build with java 8.
=> Update build to work with openjdk8

README.OmniOS, usr/src/uts/common/fs/zfs/metaslab.c, usr/src/uts/common/fs/zfs/sys/metaslab_impl.h, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
Weekly upstream for joyent_merge/2018121901
To r151028:
* OS-7151 ZFS loading and unloading metaslabs at audible frequency
```
==== Nightly distributed build started:   Wed Dec 19 12:09:05 UTC 2018 ====
==== Nightly distributed build completed: Wed Dec 19 12:57:47 UTC 2018 ====
real    0:48:41
/usr/bin/uname
SunOS bloody 5.11 omnios-master-6968c44d5a i86pc i386 i86pc
cw version 3.0
gcc …
```
=> Upstream merge joyent_merge/2018121901

usr/src/cmd/svc/seed/Makefile
This is based on:
https://repo.or.cz/unleashed.git/commitdiff/ca1ec97eb45c5f608efb2e3b0f87b3c
by Lauri Tirkkonen <lotheac@iki.fi>
The current system imports each manifest to a seed repository in turn, setting up and tearing down a svc.configd process with each. This change imports them in one step.
It also uses /tmp to build the databases since sqlite2 is heavy on sync() activity.
Timings before (serial build of seed databases):
```
make  7.46s user 4.78s system 79% cpu 15.459 total
make  7.46s user 4.83s system 79% cpu 15.483 total
make  7.42s user 4.70s system 78% cpu 15.343 tota
```
and after:
```
make  4.51s user 2.24s system 94% cpu 7.155 total
make  4.62s user 2.34s system 94% cpu 7.386 total
make  4.66s user 2.36s system 94% cpu 7.456 total
```
Not a big gain, but worth having. The …
=> Build SMF seed databases in one go and in tmpfs

usr/src/pkg/manifests/system-bhyve.mf, usr/src/pkg/manifests/system-library-bhyve.mf
Now that `mdb` is linked against libvmm.so and libvmmapi.so, system/bhyve and its dependencies (system/bhyve/firmware and developer/acpi) have become mandatory packages and we would prefer them to remain optional to minimise reboots for servers which do not run bhyve.
Splitting the bhyve libraries and header files to `system/library/bhyve` makes those required (through the auto-detected dependency in `mdb`) whilst leaving the rest of bhyve optional.
```
developer-debug-mdb.res:depend fmri=pkg:/system/library/bhyve@0.5.11-151029.0 type=require
```
`make check` in `/usr/src/pkg` passes.
=> Split system/bhyve package

usr/src/uts/common/io/vioif/vioif.c, usr/src/uts/common/os/zone.c, usr/src/uts/i86pc/os/cmi_hw.c, usr/src/uts/i86pc/os/cpuid.c
Weekly upstream for joyent_merge/2019012001
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019012001-80bdaa963c i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sun Jan 20 18:06:28 UTC 2019 ====
==== Nightly distributed build completed: Sun Jan 20 18:57:24 UTC 2019 ====
real    0:50:55
/usr/bin/uname
SunOS bloody 5.11 omnios-master-59a2989e81 i86pc i386 i86pc
cw version 3.0 …
```
=> Upstream merge joyent_merge/2019012001

usr/src/Targetdirs, usr/src/cmd/boot/bootadm/bootadm.c, usr/src/cmd/boot/filelist/i386/filelist.ramdisk, usr/src/cmd/nsadmin/system, usr/src/man/man4/system.4, usr/src/pkg/manifests/SUNWcs.mf, usr/src/uts/common/os/modctl.c, usr/src/uts/common/os/modsysfile.c, usr/src/uts/common/sys/modctl.h
```
==== Nightly distributed build started:   Tue Jan 29 13:40:24 UTC 2019 ====
==== Nightly distributed build completed: Tue Jan 29 14:45:16 UTC 2019 ====
real    1:04:52
/usr/bin/uname
SunOS bloody 5.11 omnios-master-1fd9c3fe3d i86pc i386 i86pc
cw version 3.0
gcc (OmniOS 151029/7.4.0-il-1) 7.4.0 …
```
=> 9696 add /etc/system.d support

README.OmniOS, usr/src/uts/i86pc/io/viona/viona.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c
Weekly upstream for joyent_merge/2019013101
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019013101-f719003b01 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jan 31 10:38:28 UTC 2019 ====
==== Nightly distributed build completed: Thu Jan 31 11:27:32 UTC 2019 ====
real    0:49:04
/usr/bin/uname
SunOS bloody 5.11 omnios-systemd-432efba439 i86pc i386 i86pc
cw version 3.0 …
```
=> Upstream merge joyent_merge/2019013101

usr/src/tools/env/omnios-illumos-omnios.sh
We need to exclude the trailing weekly release part of /etc/os-release:VERSION
=> Exclude weekly release component

usr/src/cmd/dlmgmtd/dlmgmt_door.c, usr/src/cmd/zoneadm/zoneadm.c, usr/src/man/man1m/zonecfg.1m
Most of the work to support on-demand VNICs for zones is already in OmniOS from the lx port. This hooks up the small number of missing bits.
See https://gist.github.com/citrus-it/767a42755825d9dde6d0e8dfb331791f
See associated change in https://github.com/omniosorg/pkg5/pull/114
=>  Support on-demand VNICs

README.OmniOS, exception_lists/packaging, usr/src/cmd/mdb/i86pc/modules/unix/amd64/Makefile, usr/src/cmd/mdb/i86pc/modules/unix/unix.c, usr/src/cmd/mdb/i86xpv/modules/unix/amd64/Makefile, usr/src/cmd/mdb/intel/Makefile.kmdb, usr/src/cmd/mdb/intel/amd64/Makefile.kmdb, usr/src/cmd/mdb/intel/amd64/mdb/Makefile, usr/src/cmd/mdb/intel/mdb/mdb_bhyve.c, usr/src/cmd/mdb/intel/mdb/mdb_x86util.c, usr/src/cmd/mdb/intel/mdb/mdb_x86util.h, usr/src/lib/libvmm/libvmm.c, usr/src/lib/libvmm/libvmm.h, usr/src/pkg/manifests/system-bhyve-tests.mf, usr/src/pkg/manifests/system-bhyve.mf, usr/src/pkg/manifests/system-library-bhyve.mf, usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/io/vmm/vm/vm_glue.h, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/io/vmm/vmm_sol_ept.c, usr/src/uts/i86pc/io/vmm/vmm_sol_vm.c, usr/src/uts/i86pc/os/gipt.c, usr/src/uts/i86pc/sys/gipt.h
Weekly upstream for joyent_merge/2019021401
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019021401-f18934bf4d i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Feb 14 21:48:42 UTC 2019 ====
==== Nightly distributed build completed: Thu Feb 14 22:38:45 UTC 2019 ====
real    0:50:02
/usr/bin/uname
SunOS bloody 5.11 omnios-master-a7bf5f222a i86pc i386 i86pc
cw version 4.0 …
```
=> Upstream merge joyent_merge/2019021401

usr/src/cmd/dlmgmtd/Makefile, usr/src/cmd/dlmgmtd/dlmgmt_door.c
The fix imported from illumos-joyent to fix breakage caused by duplicate VNICs was wrong. This reverts it and applies the correct fix which is also being upstreamed in parallel.
Refer to https://www.illumos.org/issues/10001 for more details and testing notes, but I've verified that this works as expected on bloody.
=> Fix duplicate VNIC handling

usr/src/cmd/cmd-inet/usr.sbin/ipadm/ipadm.c, usr/src/cmd/dladm/dladm.c
The `ipadm` and `dladm` commands currently show a usage message if invoked without arguments. They should default to a sensible command showing information (as Solaris does).
=> Want default actions for ipadm/dladm

README.OmniOS, usr/src/lib/fm/topo/modules/common/disk/disk_common.c, usr/src/lib/fm/topo/modules/common/ses/ses.c
Backport from bloody to fix a problem with device enumeration being experienced by an OmniOS user, see https://illumos.topicbox.com/groups/omnios-discuss/T0b1dfc4dfcdd6957-M9aee25acf7b46245e33de563/solaris-fault-manager-fmd-maintenance-issue
User's stack trace, node that the third argument to disk_tnode_create - dnode - is NULL.
```
0803bdf8 ses.so`disk_tnode_create+0x31d(8767630, 9240de0, 0, fdd908e6, 0, 803be2c)
0803be48 ses.so`disk_declare+0x3b(8767630, 9240de0, 0, 803be98)
0803be68 ses.so`disk_declare_non_enumerated+0x16(8767630, 9240de0, 803be98, 803be98)
0803bec8 ses.so`ses_create_disk+0x171(86ccba0, 9240de0, 863b608, 1)
0803bfb8 ses.so`ses_create_generic+0x3cd(86ccba0, 9241f68, 9240f00, 0, fdd90457, fdd9045b)
0803c018 ses.so`ses_create_children+0x170(86ccba0, 9240f00, 17, 0, …
```
=> 10187 ses enumerator blows chunks on US60+8 (r151028)

usr/src/lib/brand/shared/zadump/Makefile
With thanks for @ptribble for reporting:
```
Under "Check ELF runtime attributes"
usr/lib/brand/shared/zadump: non-conforming mcs(1) comment <no $(POST_PROCESS)?>
```
Before:
```
% mcs -p zadump
zadump:
@(#)SunOS 5.11 omnios-r151028-d3d0427bff November 2018
@(#)SunOS 5.11 omnios-r151028-d3d0427bff November 2018
@(#)SunOS 5.11 omnios-r151028-d3d0427bff November 2018
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1756 (illumos)
```
After:
```
% mcs -p zadump
zadump:
@(#)SunOS 5.11 omnios-master-8f333db69e February 2019
```
=> Add missing post process step for zadump

usr/src/uts/common/exec/elf/elf.c
…NAMIC
Reviewed by: Richard Lowe <richlowe@richlowe.net>
Reviewed by: Patrick Mooney <patrick.mooney@joyent.com>
=> OS-7630 elfexec() should keep to unsigned types when processing PT_DY… (r151028)

usr/src/uts/common/exec/elf/elf.c
…NAMIC
Reviewed by: Richard Lowe <richlowe@richlowe.net>
Reviewed by: Patrick Mooney <patrick.mooney@joyent.com>
=> OS-7630 elfexec() should keep to unsigned types when processing PT_DY… (r151026)

usr/src/uts/common/exec/elf/elf.c
…NAMIC
Reviewed by: Richard Lowe <richlowe@richlowe.net>
Reviewed by: Patrick Mooney <patrick.mooney@joyent.com>
=> OS-7630 elfexec() should keep to unsigned types when processing PT_DY… (r151022)

usr/src/cmd/ipdadm/ipdadm.c, usr/src/lib/libipd/common/libipd.h, usr/src/man/man1m/ipdadm.1m, usr/src/uts/common/inet/ipd/ipd.c, usr/src/uts/common/sys/ipd.h
I left the bigger network fixes in delphix-os to Joyent who is already internally reviewing the bigger chunks. This contains one small patch that seems to make sense although I never used ipdadm and the daemon that allows you to inject errors and drops on network connections for testing purposes.
=> Upstream DelphixOS network fixes.

usr/src/pkg/manifests/driver-hyperv-pv.mf, usr/src/pkg/manifests/system-hyperv-tools.mf
If the tools are not installed, the driver generates errors as it cannot communicate with the service. Installing the tools without the driver just means that they won't start. It feels better to make the driver dependent on the tools.
=> Fix-up hyperv manifests

usr/src/lib/libumem/common/vmem.c
First patch is arbitrary, it compiles some more programs with libumem. We could decide to drop that one. The seconds one is more important as it fixes a problem in libumem. I compared the content of libumem against the same directory in delphix-os gate and its exactly the same after this patch so there are no other patches applied to it.
=> Upstream DelphixOS libumem fixes.

.gitignore, README.OmniOS, usr/src/lib/brand/lx/testing/Readme_ltp, usr/src/uts/common/io/mac/mac_util.c
Weekly upstream for joyent_merge/2019031301
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019031301-c4647a6bbf i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Mar 13 11:18:06 UTC 2019 ====
==== Nightly distributed build completed: Wed Mar 13 12:22:10 UTC 2019 ====
real    1:04:03
/usr/bin/uname
SunOS bloody 5.11 omnios-upstream_merge-2019031201-306641b65e i86pc i386 i86pc
cw version 4.0
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```
=> Upstream merge joyent_merge/2019031301

usr/src/uts/i86pc/os/hma.c, usr/src/uts/intel/io/hyperv/vmbus/hyperv.c
These changes make the messages go to the system log by default and only to the console if booted in verbose mode.
=> Fewer messages to console during boot

usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/os/hma.c, usr/src/uts/i86pc/sys/hma.h
This completes the changes needed to ensure that one cannot shoot oneself in the foot with respect to running incompatible hypervisors concurrently.
```
theeo# mdb -ke 'hma_registrations::walk list | ::print -t hma_reg_t hr_name'
theeo# zoneadm -z bloody boot
theeo# mdb -ke 'hma_registrations::walk list | ::print -t hma_reg_t hr_name'
const char *hr_name = 0xfffffffff83e590a "bhyve"
theeo# VBoxHeadless -s test
Oracle VM VirtualBox Headless Interface 5.2.26
(C) 2008-2019 Oracle Corporation
All rights reserved.
19/03/2019 12:54:28 Listening for VNC connections on TCP port 5900
19/03/2019 12:54:28 Listening for VNC connections on TCP6 port 5900
VRDE server is listening on port 5900.
Error: failed to start machine. Error message: VT-x is being used by another hypervisor …
```
=> OS-7600 Want exclusive hma registration

usr/src/uts/intel/io/hyperv/netvsc/if_hn.c, usr/src/uts/intel/io/hyperv/utilities/hv_kvp.c, usr/src/uts/intel/io/hyperv/utilities/vmbus_icreg.h, usr/src/uts/intel/io/hyperv/utilities/vmbus_timesync.c, usr/src/uts/intel/io/hyperv/vmbus/hyperv.c, usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
These fix a number of crash bugs in the new hyperv drivers.
With these fixes, installing OmniOS on a HyperV first generation machine works well, using the PV drivers for disk and network interface.
Running as a guest with a single CPU is still not supported, but at least it no longer causes a system panic.
Second generation HyperV machines will require more work.
=> Various hyperv PV driver fixes

README.OmniOS, usr/src/uts/common/io/sata/adapters/ahci/ahci.c
Weekly upstream for joyent_merge/2019032801
None
```
==== Nightly distributed build started:   Thu Mar 28 19:31:58 UTC 2019 ====
==== Nightly distributed build completed: Thu Mar 28 20:23:22 UTC 2019 ====
real    0:51:24
/usr/bin/uname
SunOS bloody 5.11 omnios-master-fa6e4ea903 i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151029/7.4.0-il-1) 7.4.0
Copyright (C) 2017 Free Software Foundation, …
```
=> Upstream merge joyent_merge/2019032801

usr/src/lib/brand/lx/zone/config.xml
We're missing these hooks for the lx brand
(SmartOS has them, see https://github.com/joyent/smartos-live/blob/master/overlay/generic/usr/lib/brand/lx/config.xml#L49 )
=> Add state change hooks for lx zones

usr/src/cmd/fs.d/df.c, usr/src/pkg/manifests/developer-opensolaris-osnet.mf, usr/src/uts/common/fs/smbclnt/netsmb/smb_iod.c, usr/src/uts/i86pc/io/viona/viona.c
Backport(s) for backportr30
```
==== Nightly distributed build started:   Mon Apr  8 10:50:47 UTC 2019 ====
==== Nightly distributed build completed: Mon Apr  8 11:39:33 UTC 2019 ====
real    0:48:46
/usr/bin/uname
SunOS r151030 5.11 omnios-r151030-32d720bfc8 i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151030/7.4.0-il-1) 7.4.0
This is free …
```
=> Backports for r151030

usr/src/uts/intel/io/dktp/controller/ata/ata_common.c, usr/src/uts/intel/io/dktp/controller/ata/ata_dma.c, usr/src/uts/intel/io/hyperv/vmbus/hyperv.c
Reviewed at: http://reviews.delphix.com/r/48492/
This is Pavel's commit I'm shepherding into illumos-omnios.  In hyperv.c, I changed his printf() to cmn_err() to match existing code.  I plan on testing this on Azure itself later today if all goes well.
=> DLPX-63519 ATA reads timeout after Azure update

README.OmniOS, usr/contrib/freebsd/x86/specialreg.h, usr/src/compat/freebsd/amd64/machine/specialreg.h, usr/src/uts/common/brand/lx/os/lx_pid.c, usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/disp/fss.c, usr/src/uts/common/disp/sysdc.c, usr/src/uts/common/disp/ts.c, usr/src/uts/common/fs/proc/prsubr.c, usr/src/uts/common/fs/ufs/ufs_directio.c, usr/src/uts/common/os/bio.c, usr/src/uts/common/os/condvar.c, usr/src/uts/common/os/pid.c, usr/src/uts/common/os/rwlock.c, usr/src/uts/common/sys/fss.h, usr/src/uts/common/sys/ia.h, usr/src/uts/common/sys/thread.h, usr/src/uts/common/sys/ts.h, usr/src/uts/common/vm/page_lock.c, usr/src/uts/i86pc/io/vmm/x86.c, usr/src/uts/i86pc/ml/offsets.in, usr/src/uts/intel/ia32/ml/lock_prim.s, usr/src/uts/intel/ia32/os/syscall.c, usr/src/uts/sfmmu/vm/hat_sfmmu.c, usr/src/uts/sparc/os/syscall.c, usr/src/uts/sparc/v9/ml/lock_prim.s, usr/src/uts/sun4/ml/offsets.in
Weekly upstream merge for illumos-joyent
None (OS-7801 has already been backported to r30)
```
SunOS nemesis 5.11 omnios-joyent_merge-2019052301-92f6114091 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu May 23 18:22:00 UTC 2019 ====
==== Nightly distributed build completed: Thu May 23 19:35:13 UTC 2019 ====
real    1:13:12
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-5e514c8a6b1 i86pc i386 i86pc
cw version 4.0
warranty; not even for …
```
=> Joyent merge/2019052301

usr/src/uts/common/fs/zfs/vdev_queue.c
We are getting noise on the console during boot as follows. Joyent have a fix which will likely be upstreamed in time. I'm picking it now to fix this in bloody.
```
SunOS Release 5.11 Version omnios-master-95346d5fd9 64-bit
Copyright (c) 1983, 2010, Oracle and/or its affiliates. All rights reserved.
Copyright (c) 2017-2019 OmniOS Community Edition (OmniOSce) Association.
WARNING: zfs_zone_zio_dequeue: count==0
WARNING: zfs_zone_zio_dequeue: count==0
WARNING: zfs_zone_zio_dequeue: count==0
WARNING: zfs_zone_zio_dequeue: count==0
WARNING: zfs_zone_zio_dequeue: count==0
bloody console login: May 29 10:24:56 bloody zfs: WARNING: zfs_zone_zio_dequeue: count==0
bloody console login: May 29 10:54:04 bloody zfs: WARNING: zfs_zone_zio_dequeue: count==0
```
=> OS-7798 zfs_zone_zio_dequeue: count==0 console noise during boot

usr/src/uts/i86pc/os/mp_machdep.c, usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
This is what I'm testing on my system.  No full build yet, so just dropping in a new "unix" in an existing r151030 build for now.  I'll open another PR against master once this tests out OK.
https://github.com/omniosorg/illumos-omnios/issues/482
=> Provide psm_get_ipivect even on single CPU systems

.gitignore, README.OmniOS, usr/src/uts/i86pc/io/viona/viona.c
Weekly upstream for joyent_merge/2019060501
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019060501-d1cb068c02 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Jun  5 10:48:22 UTC 2019 ====
==== Nightly distributed build completed: Wed Jun  5 11:41:38 UTC 2019 ====
real    0:53:16
/usr/bin/uname
SunOS bloody 5.11 omnios-master-01c610f1f5 i86pc i386 i86pc
cw version 4.0 …
```
=> Upstream merge joyent_merge/2019060501

usr/src/cmd/man/Makefile, usr/src/cmd/man/rebuild-whatis, usr/src/cmd/man/rebuild-whatis.xml, usr/src/pkg/manifests/system-man.mf, usr/src/pkg/transforms/restart_fmri
Fixes https://github.com/omniosorg/illumos-omnios/issues/494
Packages now get their man pages tagged with a restart_fmri action:
```
% pkg contents -mg packages/i386/nightly-nd/repo.redist fss | grep man
dir group=bin mode=0755 owner=root path=usr/share/man
dir facet.doc.man=true group=bin mode=0755 owner=root path=usr/share/man/man7
file feda492d099cc87d4674fbbb3e859ef2af35fb3d chash=4dcc635a03b98b051a1243be45771d2327910cf2 facet.doc.man=true group=bin mode=0444 owner=root path=usr/share/man/man7/FSS.7 pkg.content-hash=file:sha512t_256:4284e5c4e44a8b7692b147780a9c0c36c3a20569e8f8e33c23e39b01af380329 pkg.content-hash=gzip:sha512t_256:d4d943badc489cf3d1981f377027bff7ce16c0b227b311261cb0b2b346887f4a pkg.csize=3293 pkg.size=8128 restart_fmri=svc:/system/rebuild-whatis:default
```
Installing …
=> Automatically maintain the whatis database

usr/src/cmd/dlmgmtd/dlmgmt_door.c, usr/src/lib/brand/shared/zadump/zadump.c, usr/src/uts/common/io/comstar/port/qlt/qlt.c
Fixing a few more smatch warnings for bits only in OmniOS.
We're almost smatch clean. The next upstream merge will fix most of the remaining ones then there are just a few for smb that will be fixed once SMB3 is complete.
=> Fix smatch warnings

usr/src/lib/smbsrv/libsmb/common/smb_pwdutil.c
Fixes https://www.illumos.org/issues/11026
This has been tested via https://hf.omnios.org/r151030/11026.p5p
=> NEX-15023 Windows usernames should be treated as case insensitive

.gitignore, README.OmniOS, usr/contrib/freebsd/dev/nvme/nvme.h, usr/src/boot/sys/boot/efi/libefi/i386/Makefile, usr/src/boot/sys/boot/libstand/Makefile.com, usr/src/cmd/mdb/common/mdb/mdb_cmds.c, usr/src/cmd/mdb/common/modules/genunix/genunix.c, usr/src/uts/common/brand/lx/syscall/lx_socket.c, usr/src/uts/common/io/mac/mac_client.c, usr/src/uts/common/io/mac/mac_provider.c, usr/src/uts/common/io/simnet/simnet.c, usr/src/uts/common/sys/mac_impl.h, usr/src/uts/common/sys/pattr.h, usr/src/uts/intel/ia32/ml/lock_prim.s
Weekly upstream for joyent_merge/2019081201
None
```
SunOS bloody 5.11 omnios-joyent_merge-2019081201-ab5fa937ca i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Aug 12 11:18:13 UTC 2019 ====
==== Nightly distributed build completed: Mon Aug 12 12:15:05 UTC 2019 ====
real    0:56:52
/usr/bin/uname
SunOS bloody 5.11 omnios-master-398f96250b i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151031/7.4.0-il-2) 7.4.0
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```
=> Upstream merge joyent_merge/2019081201

usr/src/cmd/hal/Makefile.hal, usr/src/cmd/latencytop/Makefile.com, usr/src/cmd/policykit/Makefile, usr/src/lib/policykit/libpolkit/Makefile.com
Since upgrading to glib2 version 2.62.0, it has not been possible to build illumos-omnios with shadow compilers enabled; here's the fix. It needs to go upstream too or it will not be possible to build illumos-gate on r151032 once it is released. It may be possible to be more specific with the smatch disable rules - that will be determined during the upstreaming process.
```
==== Nightly distributed build started:   Sat Sep 14 15:15:39 UTC 2019 ====
==== Nightly distributed build completed: Sat Sep 14 16:15:01 UTC 2019 ====
real    0:59:22
/usr/bin/uname
SunOS bloody 5.11 omnios-master-6c67d193c89 i86pc i386 i86pc
cw version 5.0
gcc …
```
=> Add support for building with glib2 v2.62

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_socket.c
Weekly upstream for joyent_merge/2019091801
to r151030
```
==== Nightly distributed build started:   Wed Sep 18 13:24:16 UTC 2019 ====
==== Nightly distributed build completed: Wed Sep 18 14:33:31 UTC 2019 ====
real    1:09:15
/usr/bin/uname
SunOS bloody 5.11 omnios-master-7f6d3461785 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151031/7.4.0-il-3) 7.4.0
Copyright (C) 2010 Free Software …
```
=> Upstream merge joyent_merge/2019091801

usr/src/boot/sys/boot/forth/loader.4th, usr/src/boot/sys/boot/forth/loader.conf, usr/src/boot/sys/boot/forth/logo-omnios.4th, usr/src/boot/sys/boot/forth/menu-commands.4th, usr/src/boot/sys/boot/forth/menu.rc, usr/src/boot/sys/boot/forth/shortcuts.4th, usr/src/boot/sys/boot/forth/support.4th
This adds two new loader configuration variables - `loader_resolution` and `boot_resolution`
The first specifies the screen resolution of the framebuffer-based loader screen, and defaults to 800x600.
The second specifies the screen resolution that is selected just before booting the kernel and defaults to 1024x768.
Both of these can be overridden via a file in `/boot/conf.d/` if desired.
@v-a-b
=> Add configurable screen resolution variables to loader

usr/src/boot/Makefile.version, usr/src/boot/lib/libstand/stand.h, usr/src/boot/lib/libstand/zalloc.c, usr/src/boot/lib/libstand/zalloc_malloc.c, usr/src/boot/lib/libstand/zalloc_protos.h, usr/src/boot/sys/boot/common/module.c, usr/src/boot/sys/boot/efi/libefi/efipart.c, usr/src/cmd/boot/installboot/i386/installboot.c, usr/src/uts/common/fs/nfs/nfs4_client_state.c, usr/src/uts/common/fs/smbsrv/smb2_negotiate.c, usr/src/uts/common/fs/zfs/vdev_disk.c, usr/src/uts/i86pc/io/viona/viona_impl.h, usr/src/uts/i86pc/io/viona/viona_main.c, usr/src/uts/i86pc/io/viona/viona_ring.c, usr/src/uts/i86pc/io/viona/viona_rx.c, usr/src/uts/i86pc/io/viona/viona_tx.c
```
==== Nightly distributed build started:   Thu Oct  3 10:46:33 GMT 2019 ====
==== Nightly distributed build completed: Thu Oct  3 11:47:30 GMT 2019 ====
real    1:00:57
/usr/bin/uname
SunOS r151032 5.11 omnios-r151032-5297db41ff i86pc i386 i86pc
number of concurrent jobs = 12
cw version 5.0
gcc (OmniOS 151032/7.4.0-il-3) 7.4.0
This is free software; see the source …
```
=> Backports for r151032

usr/src/uts/common/io/bge/bge_impl.h
from https://www.illumos.org/issues/10152, I checked the code and in fact, it still building with debug enabled. I don't have a bge chip to test this change though.
=> 10152 bge debugging always on

usr/src/boot/Makefile.version, usr/src/boot/sys/boot/common/gfx_fb.c, usr/src/boot/sys/boot/efi/loader/framebuffer.c, usr/src/boot/sys/boot/i386/libi386/i386_copy.c, usr/src/boot/sys/boot/i386/libi386/vbe.c, usr/src/cmd/boot/bootadm/bootadm_loader.c, usr/src/cmd/smbsrv/smbd/server.xml, usr/src/cmd/svc/milestone/fs-usr, usr/src/cmd/svc/startd/transition.c, usr/src/common/font/font.c, usr/src/uts/common/fs/zfs/dsl_scan.c, usr/src/uts/common/sys/font.h
Backports to r151032
```
==== Nightly distributed build started:   Wed Oct  9 20:56:40 GMT 2019 ====
==== Nightly distributed build completed: Wed Oct  9 21:58:45 GMT 2019 ====
real    1:02:05
/usr/bin/uname
SunOS r151032 5.11 omnios-r151032-5297db41ff i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151032/7.4.0-il-3) 7.4.0
This is free …
```
=> Backports to r151032

usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/lib/libmlrpc/common/ndr_process.c, usr/src/lib/libpcidb/common/pcidb.c, usr/src/uts/common/fs/smbsrv/smb2_dispatch.c, usr/src/uts/common/fs/smbsrv/smb2_setinfo_file.c, usr/src/uts/common/fs/smbsrv/smb_ofile.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_set_fileinfo.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c, usr/src/uts/common/fs/smbsrv/smb_tree_connect.c, usr/src/uts/common/fs/smbsrv/smb_user.c, usr/src/uts/common/smbsrv/smb_kproto.h, usr/src/uts/common/smbsrv/smb_ktypes.h
Weekly illumos-gate upstream merge
* all `SMB` related fixes
```
SunOS nemesis 5.11 omnios-upstream_merge-2019102001-5b81b2c019 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Oct 21 17:25:21 UTC 2019 ====
==== Nightly distributed build completed: Mon Oct 21 19:02:02 UTC 2019 ====
real    1:36:40
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-c01e1563fa i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151033/7.4.0-il-1) 7.4.0
warranty; not even for MERCHANTABILITY …
```
=> Upstream merge/2019102001

usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/lib/libmlrpc/common/ndr_process.c, usr/src/uts/common/fs/smbsrv/smb2_dispatch.c, usr/src/uts/common/fs/smbsrv/smb2_negotiate.c, usr/src/uts/common/fs/smbsrv/smb2_setinfo_file.c, usr/src/uts/common/fs/smbsrv/smb_ofile.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_set_fileinfo.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c, usr/src/uts/common/fs/smbsrv/smb_tree_connect.c, usr/src/uts/common/fs/smbsrv/smb_user.c, usr/src/uts/common/smbsrv/smb_kproto.h, usr/src/uts/common/smbsrv/smb_ktypes.h
SMB backports to r151032
```
==== Nightly distributed build started:   Tue Oct 22 09:47:08 GMT 2019 ====
==== Nightly distributed build completed: Tue Oct 22 10:48:33 GMT 2019 ====
real    1:01:24
/usr/bin/uname
SunOS r151032 5.11 omnios-r151032-e8a22ce3b4 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151032/7.4.0-il-1) 7.4.0
This is free …
```
=> SMB backports to r151032

usr/src/uts/common/fs/zfs/zfs_vnops.c
Avoid stack overwrite in zfs_setattr_dir()
=> 11856 chown can trigger vmdump when running recentish zfs

usr/src/uts/common/fs/zfs/zfs_vnops.c
Avoid stack overwrite in zfs_setattr_dir()
OpenZFS commit https://github.com/zfsonlinux/zfs/commit/8cb34421e0bf1fea316d16014483d61381a41f57
=> 11856 chown can trigger vmdump when running recentish zfs (r151032)

README.OmniOS, usr/src/uts/common/inet/ip/ip6_input.c, usr/src/uts/common/inet/ip/ip_input.c, usr/src/uts/common/inet/ip_impl.h, usr/src/uts/common/io/bridge.c, usr/src/uts/common/io/dls/dls_link.c, usr/src/uts/common/io/mac/mac.c, usr/src/uts/common/io/mac/mac_client.c, usr/src/uts/common/io/mac/mac_provider.c, usr/src/uts/common/io/mac/mac_sched.c, usr/src/uts/common/io/mac/mac_util.c, usr/src/uts/common/sys/mac.h, usr/src/uts/common/sys/mac_client_impl.h, usr/src/uts/common/sys/pattr.h, usr/src/uts/i86pc/io/viona/viona_main.c, usr/src/uts/i86pc/io/viona/viona_rx.c
Weekly upstream for joyent_merge/2019111801
None
```
bloody# uname -a
SunOS bloody 5.11 omnios-joyent_merge-2019111801-a2ef021faf i86pc i386 i86pc
bloody# /opt/net-tests/bin/nettest
Test: /opt/net-tests/tests/forwarding/ip_fwd_001 (run as root)    [00:30] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_002 (run as root)    [00:30] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_003 (run as root)    [00:30] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_004 (run as root)    [00:30] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_005 (run as root)    [00:31] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_006 (run as root)    [00:30] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_007 (run as root)    [00:29] [PASS]
Test: /opt/net-tests/tests/forwarding/ip_fwd_008 …
```
=> Upstream merge joyent_merge/2019111801

usr/src/boot/sys/boot/Makefile.inc, usr/src/boot/sys/boot/i386/btx/btx/Makefile, usr/src/boot/sys/boot/i386/btx/btxldr/Makefile, usr/src/boot/sys/boot/i386/btx/lib/Makefile, usr/src/boot/sys/boot/i386/cdboot/Makefile, usr/src/boot/sys/boot/i386/pmbr/Makefile, usr/src/grub/grub-0.97/Makefile.solaris.defs, usr/src/grub/grub-0.97/stage1/Makefile.solaris, usr/src/grub/grub-0.97/stage2/Makefile.solaris
Now that GNU binutils targets 64-bit by default, we need to specify 32-bit (elf_i386_sol2) output when we want it.
=> 12016 Use of GNU ld should explicitly specify the required output format

usr/src/uts/common/io/tem_safe.c
This helps 8-bit colour modes work properly on the console after boot.
=> 12041 tem: x86 needs to use tems.ts_color_map() for 8-bit colors (r151032)

usr/src/uts/common/fs/nfs/nfs4_callback.c, usr/src/uts/common/fs/nfs/nfs4_dispatch.c, usr/src/uts/common/fs/nfs/nfs4_srv.c, usr/src/uts/common/fs/nfs/nfs_auth.c
Subject says it all.  Tested on SmartOS, not yet tested on OmniOSce per se BUT  first round of testing had identical problems as SmartOS did.  Just happen to have faster SmartOS boxes (for now... hopefully my new work desktop will support a 8-16GB OmniOSce VM or two).
=> Squish zero-length KM_SLEEP allocations

usr/src/common/devid/devid_scsi.c, usr/src/lib/sun_fc/common/Sun_fcScsiInquiryV2.cc, usr/src/lib/sun_fc/common/Sun_fcScsiReadCapacityV2.cc, usr/src/pkg/manifests/driver-cpu-sensor.mf, usr/src/uts/common/fs/zfs/dsl_scan.c, usr/src/uts/common/fs/zfs/sys/range_tree.h, usr/src/uts/intel/io/pchtemp/pchtemp.c
Weekly illumos-gate upstream merge
* none
```
OmniOS 5.11     omnios-upstream_merge-2019122701-33a1fd26f4     Dec. 27, 2019
SunOS Internal Development: hadfl 2019-Dec-27 [illumos-omnios]
```
```
==== Nightly distributed build started:   Fri Dec 27 12:35:05 UTC 2019 ====
==== Nightly distributed build completed: Fri Dec 27 14:39:16 UTC 2019 ====
real    2:04:10
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-8e56e550c6 i86pc i386 i86pc
cw version 5.0
warranty; not even for …
```
=> Upstream merge/2019122701

.gitignore, README.OmniOS, usr/src/cmd/zlogin/zlogin.c, usr/src/uts/common/inet/ipf/ip_fil_solaris.c
Weekly upstream for joyent_merge/2020010301
None
```
Last login: Fri Jan  3 16:13:06 2020 from 172.27.10.79
OmniOS 5.11     omnios-joyent_merge-2020010301-db479f15561      Jan. 03, 2020
SunOS Internal Development: af 2020-Jan-03 [illumos]
bloody%
SunOS bloody 5.11 omnios-joyent_merge-2020010301-db479f15561 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Jan  3 15:29:42 UTC 2020 ====
==== Nightly distributed build completed: Fri Jan  3 16:37:50 UTC 2020 ====
real    1:08:07
/usr/bin/uname
SunOS bloody 5.11 omnios-master-8e56e550c6 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS …
```
=> Upstream merge joyent_merge/2020010301

exception_lists/packaging, usr/src/pkg/manifests/system-library-demangle.mf
Although libdemangle-sys is still a private interface which may change, we can use it to replace the closed libdemangle for openjdk. Since we have releases, we are isolated from changes in the upstream library and can adjust bloody as necessary - @jasonbking
=> Ship the demangle-sys.h header file

usr/src/uts/common/inet/ip/ip_squeue.c, usr/src/uts/common/inet/squeue.c, usr/src/uts/common/inet/tcp/tcp_socket.c, usr/src/uts/common/sys/squeue.h, usr/src/uts/common/sys/squeue_impl.h, usr/src/uts/intel/ip/ip.global-objs.debug64, usr/src/uts/intel/ip/ip.global-objs.obj64, usr/src/uts/sparc/ip/ip.global-objs.debug64, usr/src/uts/sparc/ip/ip.global-objs.obj64
Pulling a performance improvement from Joyent for LX zones in particular (but system in general)
```
==== Nightly distributed build started:   Mon Feb 10 08:49:37 UTC 2020 ====
==== Nightly distributed build completed: Mon Feb 10 09:56:54 UTC 2020 ====
real    1:07:16
/usr/bin/uname
SunOS bloody 5.11 omnios-master-8d0d512421f i86pc i386 i86pc
cw version 5.0
gcc (GCC) …
```
=> LX: OS-6150 do not sq_wait unnecessarily

usr/src/uts/common/inet/ip/ip_squeue.c, usr/src/uts/common/inet/squeue.c, usr/src/uts/common/sys/squeue.h
OmniOS does not have generalised squeues. (SmartOS uses them for vnd)
=> LX: OS-6344/OS-6150 - fix mismerge

usr/src/lib/libc/port/sys/open.c
Pending the full upstream fix for [12306](https://www.illumos.org/issues/12306), this is a change to disable the XPG4v2 slave PTY behaviour completely.
```
==== Nightly distributed build started:   Sat Feb 15 11:14:04 UTC 2020 ====
==== Nightly distributed build completed: Sat Feb 15 12:23:40 UTC 2020 ====
real    1:09:36
/usr/bin/uname
SunOS bloody 5.11 omnios-master-59c7565d72 i86pc i386 i86pc
cw version 5.0
warranty; not even for MERCHANTABILITY or FITNESS FOR A …
```
=> Disable XPG4v2 slave PTY changes (pending 12306)

usr/src/man/man1m/Makefile, usr/src/man/man1m/hotplug.1m, usr/src/man/man3c/directio.3c, usr/src/pkg/manifests/SUNWcs.man1m.inc, usr/src/uts/common/fs/zfs/zfs_vnops.c
Weekly upstream for upstream_merge/2020030201
None
```
==== Nightly distributed build started:   Tue Mar  3 00:01:02 UTC 2020 ====
==== Nightly distributed build completed: Tue Mar  3 01:07:44 UTC 2020 ====
real    1:06:42
/usr/bin/uname
SunOS bloody 5.11 omnios-master-b463bb4090 i86pc i386 i86pc
cw version 5.0
Copyright (C) 2010 Free Software …
```
=> Upstream merge upstream_merge/2020030201

usr/src/cmd/bhyve/pci_emul.c, usr/src/cmd/bhyve/pci_emul.h, usr/src/cmd/bhyve/pci_fbuf.c, usr/src/lib/libvmmapi/common/mapfile-vers, usr/src/lib/libvmmapi/common/vmmapi.c, usr/src/lib/libvmmapi/common/vmmapi.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/sys/vmm.h, usr/src/uts/i86pc/sys/vmm_dev.h
From https://reviews.freebsd.org/D24066
We want to allow the UEFI firmware to enumerate and assign
addresses to PCI devices so we can boot from NVMe[1]. One issue
with this is that fbuf uses a special memory segment for the frame
buffer memory. The pci_emul code can handle address assignments to
PCI BARs, but doesn't know anything about the frame buffer memory
segment. Here we add a callback to emulated PCI devices to inform
them of a BAR configuration change. pci_fbuf then watches for
these BAR changes and relocates the frame buffer memory segment.
We also add a new VM_MUNMAP_MEMSEG ioctl to allow pci_fbuf to
actually change the frame buffer mapping.
[1]: https://github.com/freebsd/uefi-edk2/pull/9/
=> BHYVE: support relocating the fbuf data BAR

.gitignore, README.OmniOS, usr/src/cmd/bhyve/block_if.c, usr/src/cmd/bhyve/pci_virtio_block.c, usr/src/uts/common/brand/lx/syscall/lx_futex.c
Weekly upstream for joyent_merge/2020032301
To r151030, r151032:
* OS-8141 lx futex called with NULL... causes panic
```
SunOS bloody 5.11 omnios-joyent_merge-2020032301-bec234425c i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Mar 23 23:31:03 UTC 2020 ====
==== Nightly distributed build completed: Tue Mar 24 00:40:20 UTC 2020 ====
real    1:09:17
/usr/bin/uname
SunOS bloody 5.11 omnios-master-5b83ca0623 i86pc i386 i86pc
cw version 5.0
This is free software; see the source for copying conditions.  There is …
```
=> Upstream merge joyent_merge/2020032301

usr/src/boot/sys/boot/forth/menu-commands.4th, usr/src/boot/sys/boot/forth/menu.4th, usr/src/boot/sys/boot/forth/menu.rc, usr/src/boot/sys/boot/forth/menusets.4th
This consolidates the two kmdb options down into a new menu which has additional options, adds a Framebuffer menu option and removes unused code around kernel selection (to save space)
After:
> Dictionary: 722 words, 28145 cells used of 30000 total
and the options are:
And selecting the new `[F]ramebuffer` option toggles between this screen and:
=> loader: Improve kmdb option; add framebuffer option

README.OmniOS, usr/src/cmd/bhyve/pci_passthru.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
Weekly upstream for joyent_merge/2020032601
None
```
OmniOS 5.11     omnios-joyent_merge-2020032601-6fa14b9afa       Mar. 26, 2020
SunOS Internal Development: af 2020-Mar-26 [illumos]
bloody%
SunOS bloody 5.11 omnios-joyent_merge-2020032601-6fa14b9afa i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Mar 26 22:14:20 UTC 2020 ====
==== Nightly distributed build completed: Thu Mar 26 23:22:05 UTC 2020 ====
real    1:07:44
/usr/bin/uname
SunOS bloody 5.11 omnios-master-5b83ca0623 i86pc i386 i86pc
cw version 5.0 …
```
=> Upstream merge joyent_merge/2020032601

usr/src/cmd/Makefile, usr/src/cmd/demangle/Makefile, usr/src/cmd/demangle/demangle.c, usr/src/lib/commpage/amd64/cp_subr.s, usr/src/lib/commpage/common/cp_main.c, usr/src/lib/commpage/i386/cp_subr.s, usr/src/lib/libdemangle/common/demangle-sys.h, usr/src/lib/libdemangle/common/demangle.c, usr/src/lib/libdemangle/common/mapfile-vers, usr/src/man/man1/Makefile, usr/src/man/man1/demangle.1, usr/src/pkg/manifests/developer-object-file.mf, usr/src/uts/common/fs/zfs/spa.c, usr/src/uts/common/fs/zfs/sys/spa.h, usr/src/uts/common/fs/zfs/sys/spa_boot.h, usr/src/uts/common/fs/zfs/sys/vdev_impl.h, usr/src/uts/common/fs/zfs/vdev_disk.c, usr/src/uts/common/fs/zfs/zfs_vfsops.c, usr/src/uts/common/os/devcfg.c, usr/src/uts/common/sys/ddi_implfuncs.h, usr/src/uts/intel/zfs/spa_boot.c, usr/src/uts/sparc/zfs/spa_boot.c
```
OmniOS 5.11     omnios-bpr34-8effd1d7de Apr. 02, 2020
SunOS Internal Development: af 2020-Apr-02 [illumos]
r151034%
r151034% uname -a
SunOS r151034 5.11 omnios-bpr34-8effd1d7de i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Apr  2 09:49:06 UTC 2020 ====
==== Nightly distributed build completed: Thu Apr  2 11:00:12 UTC 2020 ====
real    1:11:06
/usr/bin/uname
SunOS r151034 5.11 omnios-r151034-2e94bc8321 i86pc i386 i86pc
cw version 5.0
warranty; …
```
=> Upstream merge r151034 backports

usr/src/cmd/svc/milestone/network-physical.xml, usr/src/cmd/varpd/varpd.xml
It makes more sense to set up the dependency this way around since the varpd service is not installed in a non-global zone. With the original configuration, `network/physical:default` in an NGZ still had a dependency on varpd and this way it does not.
```
bloody% svcs -x
bloody%
bloody% svcs varpd
STATE          STIME    FMRI
disabled       22:09:38 svc:/network/varpd:default
bloody% svcs -D varpd
STATE          STIME    FMRI
online         22:09:39 svc:/network/physical:default
bloody% svcs -d network/physical:default
STATE          STIME    FMRI
disabled       22:09:38 svc:/network/install:default
disabled       22:09:38 svc:/network/varpd:default
online         22:09:38 svc:/network/datalink-management:default
online         22:09:38 svc:/network/ip-interface-management:default
online …
```
=> Specify network-physical's dependency on varpd in the varpd manifest

.gitignore, README.OmniOS, usr/src/lib/brand/lx/zone/Makefile, usr/src/lib/brand/lx/zone/lx_boot.ksh, usr/src/lib/brand/lx/zone/lx_boot_zone_void.ksh, usr/src/pkg/manifests/system-zones-brand-lx.mf, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/syscall/lx_socket.c
Weekly upstream for Joyent merge/2020041001
- mainfest has been fixed after build
* none
```
OmniOS 5.11     omnios-joyent_merge-2020041001-284039ff46       Apr. 10, 2020
SunOS Internal Development: hadfl 2020-Apr-10 [illumos-omnios]
SunOS mars 5.11 omnios-joyent_merge-2020041001-284039ff46 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Apr 10 11:36:36 CEST 2020 ====
==== Nightly distributed build completed: Fri Apr 10 12:58:47 CEST 2020 ====
real    1:22:10
/usr/bin/uname
SunOS mars 5.11 omnios-master-9a0c008aef i86pc i386 i86pc
cw version 5.0 …
```
=> Joyent merge/2020041001

usr/src/cmd/svc/milestone/net-physical
There is a chicken and egg problem with bringing up overlays at boot time. Once an overlay is created, no vnics can be added to it until the vxlan encapsulation plugin is able to bind to its configured listen IP address. That means that overlay vnics must be added after IP interfaces are brought up. However, there may be IP interfaces configured on top of overlay vnics; these must be brought up after the overlay vnics are in place.
Before this change, `vnic0/v4` is in the _disabled_ state after boot as shown below. After the change it is online.
```
bloody% dladm
LINK        CLASS     MTU    STATE    BRIDGE     OVER
vioif0      phys      1400   up       --         --
ov0         overlay   1400   up       --         --
vnic0       vnic      1400   up       --         ov0
bloody% ipadm …
```
=> GZ IP interfaces over overlay vnics are down after boot

usr/src/pkg/manifests/system-network-overlay.mf
Since libdladm.so is linked against it. I'm not including the compilation symlinks (plain `.so) entries in this.
=> libvarpd must appear in NGZ

usr/src/pkg/manifests/driver-network-mlxcx.mf
Fix needed to allow the installation of `driver/network/mlxcx`.
```
omniosce# pkg install --reject ntpsec \*
Creating Plan (Checking for conflicting actions): \
pkg install: The requested change to the system attempts to install multiple actions
for legacy 'SUNWmrsas' with conflicting attributes:
1 package delivers 'legacy category=system desc="LSI MegaRAID SAS2.0 Controller HBA Driver" hotline="Please contact your local service provider" name="LSI MegaRAID SAS2.0 HBA Driver" pkg=SUNWmrsas vendor=Illumos version=11.11,REV=2009.11.11':
pkg://omnios/driver/storage/mr_sas@0.5.11,5.11-151034.0:20200419T131209Z
1 package delivers 'legacy category=system desc="Mellanox ConnectX-4/5/6 Ethernet Driver" hotline="Please contact your local service provider" name="Mellanox ConnectX-4/5/6 Ethernet …
```
=> 12469 Mlxcx: pkg errors (r151034)

usr/src/cmd/devfsadm/i386/misc_link_i386.c, usr/src/cmd/w/w.c, usr/src/cmd/whodo/whodo.c, usr/src/lib/fm/topo/modules/sun4v/chip/chip_sun4v.c, usr/src/lib/fm/topo/modules/sun4v/hostbridge/hb_sun4v.c, usr/src/pkg/manifests/driver-network-mlxcx.mf, usr/src/psm/stand/boot/common/heap_kmem.c, usr/src/psm/stand/boot/common/readfile.c, usr/src/psm/stand/cpr/sparcv9/sun4u/machdep.c, usr/src/psm/stand/cpr/sparcv9/sun4u/util.c, usr/src/stand/lib/fs/hsfs/hsfsops.c, usr/src/stand/lib/fs/nfs/auth_unix.c, usr/src/stand/lib/fs/nfs/bootparams.c, usr/src/stand/lib/fs/nfs/clnt_btcp.c, usr/src/stand/lib/fs/nfs/clnt_budp.c, usr/src/stand/lib/fs/nfs/getdents.c, usr/src/stand/lib/fs/nfs/getdents3.c, usr/src/stand/lib/fs/nfs/lookup.c, usr/src/stand/lib/fs/nfs/mount.c, usr/src/stand/lib/fs/nfs/nfs4ops.c, usr/src/stand/lib/fs/nfs/pmap.c, usr/src/stand/lib/fs/nfs/rpc.c, usr/src/stand/lib/fs/ufs/lufsboot.c, usr/src/stand/lib/fs/ufs/ufsops.c, usr/src/stand/lib/inet/ipv4.c, usr/src/stand/lib/tcp/Makefile, usr/src/stand/lib/tcp/tcp.c, usr/src/test/crypto-tests/tests/Makefile.crypto, usr/src/test/crypto-tests/tests/digest/Makefile, usr/src/uts/common/rpc/xdr.c
Weekly illumos-gate upstream merge
* none
```
OmniOS 5.11     omnios-upstream_merge-2020042101-36fe961ea2     Apr. 21, 2020
SunOS Internal Development: hadfl 2020-Apr-21 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2020042101-36fe961ea2 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Tue Apr 21 18:48:27 CEST 2020 ====
==== Nightly distributed build completed: Tue Apr 21 20:06:55 CEST 2020 ====
real    1:18:27
/usr/bin/uname
SunOS mars 5.11 omnios-master-2f72ee0787 i86pc i386 i86pc
cw version 5.0 …
```
=> Upstream merge/2020042101

usr/src/lib/libzonecfg/common/libzonecfg.c
Test script:
```
#!/bin/ksh
rm -rf /tmp/aaa
mkdir -p /tmp/aaa/etc/zones
mkdir -p /tmp/aaa/var/run
cp /etc/zones/SUNW*.xml /tmp/aaa/etc/zones/
echo global:installed:/ > /tmp/aaa/etc/zones/index
sleep 1
cat /etc/zones/did.txt
zonecfg -R /tmp/aaa -z test1 'create -b; set zonepath=/tmp/aaa/test1; exit'
cat /etc/zones/did.txt
cat /tmp/aaa/etc/zones/did.txt
find /etc/zones -newer /tmp/aaa
```
Before:
```
bloody# ./did
21
22
cat: /tmp/aaa/etc/zones/did.txt: cannot open [No such file or directory]
/etc/zones/did.txt
```
After:
```
bloody# ./did
22
22
1
```
=> Accessing /etc/zones/did.txt should be alternate-root aware

usr/src/cmd/boot/filelist/i386/filelist.ramdisk
Without, there is no way to get the ppt driver to bind to a device and use it for bhyve PCI passthrough.
Problem reported by @stellarpower
=> /etc/ppt_aliases needs to be in the boot archive

usr/src/cmd/modload/Makefile, usr/src/cmd/modload/Makefile.com, usr/src/cmd/modload/addrem.h, usr/src/cmd/modload/amd64/Makefile, usr/src/cmd/modload/drvsubr.c, usr/src/cmd/modload/plcysubr.c, usr/src/cmd/modload/sparcv9/Makefile, usr/src/lib/libzonecfg/common/libzonecfg.c, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/sys/lx_brand.h
Backports to r151034
```
==== Nightly distributed build started:   Tue Apr 28 16:26:21 UTC 2020 ====
==== Nightly distributed build completed: Tue Apr 28 17:41:21 UTC 2020 ====
real    1:15:00
/usr/bin/uname
SunOS r151034 5.11 omnios-r151034-9ce5cf3455 i86pc i386 i86pc
cw version 5.0
This is free …
```
=> Backports to r151034

usr/src/cmd/fs.d/nfs/lockd/lockd.c, usr/src/lib/brand/lx/lx_lockd/lockd.c, usr/src/lib/brand/lx/lx_lockd/nfs_tbind.c, usr/src/tools/scripts/Makefile, usr/src/uts/common/fs/nfs/nfs_sys.c, usr/src/uts/common/klm/klmmod.c, usr/src/uts/common/klm/nlm_impl.c, usr/src/uts/common/klm/nlm_impl.h, usr/src/uts/common/nfs/nfssys.h
Backport(s) for r34
```
==== Nightly distributed build started:   Thu May  7 10:38:48 UTC 2020 ====
==== Nightly distributed build completed: Thu May  7 11:55:39 UTC 2020 ====
real    1:16:50
/usr/bin/uname
SunOS r151034 5.11 omnios-r151034-f57f507df0 i86pc i386 i86pc
cw version 5.0
This is free …
```
=> Backports for r151034

README.OmniOS, usr/src/compat/freebsd/sys/callout.h, usr/src/uts/i86pc/io/vmm/vmm_sol_glue.c
Weekly upstream for joyent_merge/2020051301
```
==== Nightly distributed build started:   Wed May 13 15:59:35 UTC 2020 ====
==== Nightly distributed build completed: Wed May 13 17:02:38 UTC 2020 ====
real    1:03:02
/usr/bin/uname
SunOS bloody 5.11 omnios-master-6f16462a87 i86pc i386 i86pc
cw version 5.0 …
```
=> Upstream merge joyent_merge/2020051301

usr/src/pkg/manifests/system-bhyve-tests.mf, usr/src/pkg/manifests/system-bhyve.mf, usr/src/pkg/manifests/system-library-bhyve.mf, usr/src/pkg/manifests/system-network-overlay.mf, usr/src/pkg/manifests/system-zones-brand-lx.mf, usr/src/pkg/transforms/omnios_only, usr/src/tools/scripts/onu.sh.in
A nice clean boot to a gate onu now:
```
(_)| || | _   _  _ __ ___    ___   ___
| || || || | | || '_ ` _ \  / _ \ / __|
| || || || |_| || | | | | || (_) |\__ \         ,
|_||_||_| \__,_||_| |_| |_| \___/ |___/        ,./% &
(*****(
*/*//
*,///((
+============Welcome to illumos===========+        ,*//((/%
|                                         |          ///((((%
|  1. Boot Multi User [Enter]             |           ,*/(((((%       &#///((&
|  2. Boot [S]ingle User                  |            .///((((((%  %/(((/
|  3. [Esc]ape to loader prompt           |             .////(((((///((,
|  4. Reboot                              |             .*////((((((((((
|                                         |                  ./((((((((/
|  Options:                               | …
```
=> Further improvements to onu-to-gate

usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/bhyve/bhyverun.h, usr/src/cmd/bhyve/test/tst/mevent/lists.delete.c, usr/src/cmd/bhyve/test/tst/mevent/testlib.c, usr/src/cmd/bhyve/test/tst/mevent/testlib.h, usr/src/cmd/bhyve/uart_emul.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/vm/vm_map.h, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
Re-synchronise remaining bhyve bits with upstream-gate.
Drop local console `wait`option (it only works for socket consoles and is something that Joyent removed upstream)
Replace HMA registration patch with the version that is pending upstream.
I did a full build which was successful.
=> Bhyve cleanup & re-sync with gate

README.OmniOS, usr/src/pkg/manifests/system-test-zfstest.mf, usr/src/test/zfs-tests/cmd/watch_dir/Makefile, usr/src/test/zfs-tests/cmd/watch_dir/watch_dir.c, usr/src/test/zfs-tests/include/commands.cfg, usr/src/test/zfs-tests/runfiles/smartos.run, usr/src/test/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_watched_inotify.ksh, usr/src/test/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_watched_portfs.ksh, usr/src/uts/common/brand/lx/syscall/lx_socket.c, usr/src/uts/common/fs/portfs/port_fop.c, usr/src/uts/common/fs/vnode.c, usr/src/uts/common/fs/zfs/zfs_vfsops.c, usr/src/uts/common/io/inotify.c, usr/src/uts/common/sys/vnode.h
Weekly upstream for Joyent
* tbd
```
OmniOS r151035  omnios-joyent_merge-2020060401-1737f1b3d3       June 2020
illumos development build: 2020-Jun-04 [illumos-omnios]
SunOS mars 5.11 omnios-joyent_merge-2020060401-1737f1b3d3 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jun  4 17:50:47 CEST 2020 ====
==== Nightly distributed build completed: Thu Jun  4 19:08:49 CEST 2020 ====
real    1:18:01
/usr/bin/uname
SunOS mars 5.11 omnios-master-a84f9c312d i86pc i386 i86pc
cw version 5.0
This is free …
```
=> Joyent merge/2020060401

README.OmniOS, usr/src/uts/common/fs/portfs/port_fop.c
Weekly upstream for joyent_merge/2020062201
Picking up this fix for a panic recently introduced with 
`LX: OS-8054 inotify watches lead to EBUSY during zfs mount` (e0bc238d0549b65f981e36b78bc56895d6014335)
=> Upstream merge joyent_merge/2020062201

.gitignore, usr/src/boot/Makefile.version, usr/src/boot/lib/libstand/zfs/zfsimpl.c, usr/src/cmd/w/w.c, usr/src/data/locale/Makefile, usr/src/lib/cfgadm_plugins/ccid/Makefile, usr/src/lib/cfgadm_plugins/ccid/sparc/Makefile, usr/src/lib/cfgadm_plugins/ccid/sparcv9/Makefile, usr/src/lib/libctf/common/ctf_dwarf.c, usr/src/man/man1m/mkfifo.1m, usr/src/man/man3c/wcswidth.3c, usr/src/pkg/manifests/driver-misc-ccid.mf, usr/src/test/util-tests/tests/ctf/check-array.c, usr/src/test/util-tests/tests/ctf/test-array.c, usr/src/tools/stabs/sparc/Makefile, usr/src/tools/stabs/stabs.c, usr/src/uts/common/io/dld/dld_drv.c, usr/src/uts/common/io/iwn/if_iwn.c, usr/src/uts/i86pc/io/vmm/amd/svm.c, usr/src/uts/i86pc/sys/pci_cfgacc_x86.h, usr/src/uts/intel/io/pci/pci_boot.c, usr/src/uts/intel/io/pci/pci_memlist.c, usr/src/uts/intel/io/pci/pci_resource.c, usr/src/uts/intel/pci_autoconfig/Makefile, usr/src/uts/sparc/Makefile.sparc, usr/src/uts/sparc/ccid/Makefile
Weekly upstream for upstream_merge/2020070201
To r151034:
* 12867 Mis-programmed pcie bridge leaves 64-bit device unusable
* 12901 loader: can not read zfs pool with slog removed
```
OmniOS r151035  omnios-upstream_merge-2020070201-703b2b26e7     July 2020
illumos development build: 2020-Jul-02 [illumos]
bloody%
SunOS bloody 5.11 omnios-upstream_merge-2020070201-703b2b26e7 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jul  2 19:23:56 UTC 2020 ====
==== Nightly distributed build completed: Thu Jul  2 20:29:15 UTC 2020 ====
real    1:05:19
/usr/bin/uname
SunOS bloody 5.11 omnios-master-5f05325a4c i86pc i386 i86pc
cw …
```
=> Upstream merge upstream_merge/2020070201

usr/src/uts/common/brand/lx/io/lx_netlink.c
Fixes #798 
With this fix in place, I've booted an lx zone 2000 times successfully, where it was about a 50% success rate before.
=> LX: netlink errors must set flags to 0

usr/src/cmd/smbsrv/smbd/server.xml
This reverts commit 59e17ede6a43437ce6e61d5233c93cbe7bcd8b0f.
Conflicts:
usr/src/cmd/smbsrv/smbd/server.xml
=> Revert "NEX-9723 SMB2 open delays with exclusive oplocks"

usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
A fix for a long-term problem in lx - see https://github.com/joyent/illumos-joyent/issues/161
=> LX: readlink("/proc/<pid>/exe") can fail

usr/src/cmd/smbsrv/smbd/server.xml
This reverts commit 59e17ede6a43437ce6e61d5233c93cbe7bcd8b0f.
Conflicts:
usr/src/cmd/smbsrv/smbd/server.xml
=> Revert "NEX-9723 SMB2 open delays with exclusive oplocks" (r151034)

usr/src/uts/common/brand/lx/syscall/lx_ioctl.c
```
==== Nightly distributed build started:   Sun Jul 12 13:25:38 CEST 2020 ====
==== Nightly distributed build completed: Sun Jul 12 14:42:09 CEST 2020 ====
real    1:16:31
/usr/bin/uname
SunOS mars 5.11 omnios-master-ca9dd52f78 i86pc i386 i86pc
cw version 5.0 …
```
=> OS-7999 out of bounds read in ict_siocgifconf64()

usr/src/uts/intel/ia32/ml/lock_prim.s
We missed pulling this back into r151030 and it causes a crash when using the `lockstat` command.
Reported on IRC by _mjg
=> OS-7925 rw_exit lockstat patch point has garbage %rcx (r151030)

README.OmniOS, usr/src/uts/common/brand/lx/io/lx_netlink.c
This is effectively a null commit - just adding a missing copyright and updating the last Joyent commit. It will push a commit to lx-port-data too.
=> Joyent merge/2020080301

README.OmniOS, usr/src/lib/libzfs/common/libzfs_pool.c, usr/src/uts/common/fs/zfs/vdev.c, usr/src/uts/common/fs/zfs/zfs_ioctl.c
Backport(s) for 12894_r34
```
==== Nightly distributed build started:   Tue Aug  4 10:14:10 UTC 2020 ====
==== Nightly distributed build completed: Tue Aug  4 11:23:05 UTC 2020 ====
real    1:08:55
/usr/bin/uname
SunOS r151034 5.11 omnios-r151034-0d278a0cc5 i86pc i386 i86pc
cw version 5.0
This is free …
```
=> Backport 12894_r34

usr/src/uts/i86pc/boot/boot_fb.c
This change came in as part of https://www.illumos.org/issues/13003 and changes the boot screen so that the initial messages are emboldened.
Revert this change by putting it under a guard.
=> Revert bright-white boot text change

usr/src/cmd/cmd-inet/etc/Makefile, usr/src/cmd/svc/milestone/Makefile, usr/src/cmd/svc/milestone/config-assemble, usr/src/cmd/svc/milestone/config-assemble.xml, usr/src/pkg/manifests/SUNWcs.mf
I've tested this by adding a custom service to the end of `/etc/inet/services`, and then ONU-ing to a new debug BE with these changes in. Here's services before:
```
bloody% tail -5 /etc/inet/services
solaris-audit   16162/tcp                       # Secure remote audit logging
wnn6            22273/tcp                       # Wnn6 jserver
wnn6            22273/udp                       # Wnn6 jserver
ttest           12345/tcp                       # test service
bloody% ls /etc/inet/services.d
/etc/inet/services.d: No such file or directory
```
The ONU also pulled in an updated `git` package (see https://github.com/omniosorg/omnios-build/pull/2023 ) which delivers a services fragment.
After a reboot, the new service is online and the log shows that an initial migration was done:
``` …
```
=> Packages should be able to augment /etc/inet/services

README.OmniOS, usr/src/uts/common/inet/ip/ipclassifier.c, usr/src/uts/common/inet/tcp/tcp.c, usr/src/uts/common/inet/tcp/tcp_output.c, usr/src/uts/common/sys/socket_proto.h, usr/src/uts/i86pc/io/gfx_private/gfxp_bitmap.c
```
==== Nightly distributed build started:   Sat Sep  5 12:08:03 UTC 2020 ====
==== Nightly distributed build completed: Sat Sep  5 13:07:09 UTC 2020 ====
real    0:59:06
/usr/bin/uname
SunOS r151034 5.11 omnios-r151034-b3d6e2addc i86pc i386 i86pc
cw version 5.0
/usr/jdk/openjdk1.8.0/bin/javac
openjdk full version "1.8.0_265-omnios-151034-b01"
/usr/bin/openssl
OpenSSL 1.1.1g  21 Apr 2020 …
```
=> Backports to illumos-omnios r151034

usr/src/cmd/zoneadm/zoneadm.c
This avoids the following behaviour:
```
r151034% pfexec zadm halt testzone
r151034% pfexec zadm delete testzone
Are you sure you want to uninstall zone testzone (y/[n])? y
WARNING: Unable to completely remove /zones/testzone
because it contains additional user data.  Only the standard directory
entries have been removed.
Are you sure you want to delete zone testzone (y/[n])? y
r151034% pfexec ls /zones/testzone
etc/
```
=> zoneadm should cleanup etc/ too

usr/src/man/man7d/igb.7d, usr/src/test/os-tests/runfiles/default.run, usr/src/uts/common/brand/lx/syscall/lx_futex.c, usr/src/uts/common/inet/squeue.c, usr/src/uts/common/inet/tcp/tcp_socket.c, usr/src/uts/common/io/i40e/core/i40e_common.c, usr/src/uts/common/io/i40e/i40e_gld.c, usr/src/uts/common/io/i40e/i40e_sw.h, usr/src/uts/common/mapfiles/mac.mapfile
Weekly upstream for upstream_merge/2020093001
None
```
OmniOS r151035  omnios-upstream_merge-2020093001-fa44213720     September 2020
illumos development build: 2020-Sep-30 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2020093001-fa44213720 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Sep 30 09:53:20 UTC 2020 ====
==== Nightly distributed build completed: Wed Sep 30 11:07:04 UTC 2020 ====
real    1:13:43
/usr/bin/uname
SunOS bloody 5.11 omnios-master-b7ba24aaa1 i86pc i386 i86pc
cw version 5.0
Copyright (C) 2017 Free Software …
```
=> Upstream merge upstream_merge/2020093001

usr/src/boot/lib/libstand/pager.c, usr/src/boot/sys/boot/common/gfx_fb.h, usr/src/boot/sys/boot/i386/libi386/vbe.c, usr/src/boot/sys/boot/i386/libi386/vbe.h, usr/src/man/man2/rename.2, usr/src/man/man2/statvfs.2, usr/src/man/man7d/pchtemp.7d, usr/src/pkg/manifests/driver-cpu-sensor.mf, usr/src/test/net-tests/tests/net_common.ksh, usr/src/test/os-tests/runfiles/default.run, usr/src/uts/common/inet/ipclassifier.h, usr/src/uts/i86pc/io/rootnex.c, usr/src/uts/intel/io/pchtemp/pchtemp.c
Weekly upstream merge
To r151036
* 13193 pchtemp could support Intel 400 series chipset 
```
OmniOS r151035  omnios-upstream_merge-2020100801-d42ecce3ae     October 2020
illumos development build: 2020-Oct-08 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2020100801-d42ecce3ae i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct  8 17:26:33 CEST 2020 ====
==== Nightly distributed build completed: Thu Oct  8 18:48:00 CEST 2020 ====
real    1:21:27
/usr/bin/uname
SunOS mars 5.11 omnios-master-b7ba24aaa1 i86pc i386 i86pc
cw version 5.0
Copyright …
```
=> Upstream merge/2020100801

usr/src/lib/libpam/pam_framework.c
Reviewed by: Alex Wilson <alex@cooperi.net>
=> 13242 parse_user_name in PAM is sloppy (r151036)

usr/src/lib/libpam/pam_framework.c
Reviewed by: Alex Wilson <alex@cooperi.net>
=> 13242 parse_user_name in PAM is sloppy (r151034)

usr/src/pkg/manifests/developer-dtrace.mf, usr/src/tools/env/omnios-illumos-gate.sh
Following the recent OpenJDK11 update, some manifests also need updates.
Revert to using OpenJDK8 for gate builds until this is resolved upstream.
=> fix dtrace manifest following java update

usr/src/boot/Makefile.version, usr/src/boot/lib/libstand/zfs/nvlist.c, usr/src/boot/sys/boot/common/gfx_fb.c, usr/src/boot/sys/boot/i386/libi386/vbe.h, usr/src/boot/sys/boot/i386/libi386/vidconsole.c, usr/src/head/grp.h, usr/src/lib/libc/port/gen/initgroups.c, usr/src/lib/libc/port/mapfile-vers, usr/src/man/man3c/Makefile, usr/src/man/man3c/getgrouplist.3c, usr/src/pkg/manifests/system-library.man3c.inc, usr/src/uts/common/io/aggr/aggr_grp.c, usr/src/uts/common/io/mlxcx/mlxcx.c, usr/src/uts/common/sys/aggr_impl.h, usr/src/uts/i86pc/io/vmm/vmm_lapic.c
Weekly upstream merge from illumos-gate
* 13207 Creating an aggr with more than 128 Tx or Rx rings panics
* 13208 Create aggr fails when underlying links have more than 128 Tx
```
OmniOS r151037  omnios-upstream_merge-2020121301-caba67bdea     December 2020
illumos development build: 2020-Dec-13 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2020121301-caba67bdea i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sun Dec 13 12:26:18 CET 2020 ====
==== Nightly distributed build completed: Sun Dec 13 13:45:09 CET 2020 ====
real    1:18:51
/usr/bin/uname
SunOS mars 5.11 omnios-master-0d048edc02 i86pc i386 i86pc
number of …
```
=> Upstream merge/2020121301

usr/src/uts/common/exec/java/java.c, usr/src/uts/common/exec/shbin/shbin.c
8c602d87c1bc4bcf5f1c0cecae5814216f42b473 changed the format of gexec()'s `brand_action` parameter.
This fixes a couple of places which were missed at the time.
=> Clean up gexec calls with EBA_NONE

usr/src/cmd/zoneadmd/vplat.c, usr/src/cmd/zoneadmd/zoneadmd.c, usr/src/man/man1/prctl.1, usr/src/man/man1m/zonecfg.1m, usr/src/man/man5/resource_controls.5, usr/src/uts/common/brand/lx/syscall/lx_rlimit.c
I started this by debugging a problem with running certain pieces of software in an lx zone. That turned out to be that `getconf CHILD_MAX` was returning INT_MAX, a number far in excess of the number of children a process can have. The software was trying and failing to allocate memory to hold the PIDs of all potential children.
In fixing that, I found that the `max-processes` zone control was not documented, so I've updated the man pages to include that. Further testing showed that the automatic inference that should occur when setting only one of the max-lwps or max-processes resource limits on a zone was not working. This turns out to be a mismerge of OS-5292 in the past. Rather than fix that directly, I've brought over OS-1179 which improves zone startup time by reducing the number of …
=> LX: Incorrect RLIMIT_NPROC causing some software to fail

usr/src/cmd/cdpadm/Makefile, usr/src/test/crypto-tests/tests/Makefile.crypto, usr/src/test/os-tests/tests/secflags/Makefile
These fixes are required following the recent fix to gcc that made `-zassert-deflib` work properly in 64-bit.
=> assert-deflib fixes (r151036)

usr/src/cmd/cdpadm/Makefile, usr/src/test/crypto-tests/tests/Makefile.crypto, usr/src/test/os-tests/tests/secflags/Makefile
These fixes are required following the recent fix to gcc that made `-zassert-deflib` work properly in 64-bit.
=> assert-deflib fixes (r151034)

.gitignore, README.OmniOS, usr/src/cmd/bhyve/bhyverun.c, usr/src/lib/libvmmapi/common/mapfile-vers, usr/src/lib/libvmmapi/common/vmmapi.c, usr/src/lib/libvmmapi/common/vmmapi.h, usr/src/uts/common/fs/zfs/arc.c, usr/src/uts/i86pc/io/vmm/sys/vmm_kernel.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/sys/vmm_dev.h, usr/src/uts/i86pc/vmm/Makefile
```
==== Nightly distributed build started:   Tue Mar  9 12:13:11 UTC 2021 ====
==== Nightly distributed build completed: Tue Mar  9 13:27:41 UTC 2021 ====
real    1:14:30
/usr/bin/uname
SunOS bloody 5.11 omnios-master-cafb533f9e5 i86pc i386 i86pc
cw version 5.0 …
```
=> OS-8005 bhyve memory pressure needs to target ARC better

usr/src/cmd/ptools/pfiles/pfiles.c, usr/src/cmd/sgs/libconv/common/corenote.c, usr/src/cmd/sgs/libconv/common/corenote.msg, usr/src/cmd/truss/codes.c, usr/src/uts/common/brand/lx/syscall/lx_open.c, usr/src/uts/common/fs/vnode.c, usr/src/uts/common/os/fio.c, usr/src/uts/common/sys/file.h
Same results for the ltp open syscall tests before and after this change, and I verified that O_DIRECTORY was being exercised. For example, running specific open tests which use O_DIRECTORY:
```
root@lx:~/ltp/testcases/kernel/syscalls/open# grep -l O_DIRECTORY *.c
open01.c
open08.c
open11.c
root@lx:~/ltp/testcases/kernel/syscalls/open# ./open01
tst_test.c:1289: TINFO: Timeout per run is 0h 05m 00s
open01.c:57: TFAIL: sticky bit is cleared unexpectedly
open01.c:59: TPASS: sirectory bit is set as expected
root@lx:~/ltp/testcases/kernel/syscalls/open# ./open08
tst_test.c:1289: TINFO: Timeout per run is 0h 05m 00s
open08.c:82: TPASS: expected failure - errno = 17 : File exists
open08.c:82: TPASS: expected failure - errno = 21 : Is a directory
open08.c:82: TPASS: expected failure - errno = 20 …
```
=> lx can use O_DIRECTORY directly & O_PATH improvement.

.gitignore, exception_lists/packaging.deps, usr/src/cmd/Makefile, usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop.c, usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop.h, usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_capture.c, usr/src/cmd/pcidb/Makefile, usr/src/cmd/pcidb/pcidb.c, usr/src/contrib/ast/src/cmd/ksh93/tests/builtins.sh, usr/src/lib/libpcidb/Makefile.com, usr/src/lib/libpcidb/common/mapfile-vers, usr/src/lib/libpcidb/common/pcidb.c, usr/src/lib/libpcidb/common/pcidb.h, usr/src/man/man1m/chroot.1m, usr/src/man/man1m/snoop.1m, usr/src/pkg/manifests/SUNWcs.mf, usr/src/pkg/manifests/diagnostic-pci.mf, usr/src/pkg/manifests/system-test-utiltest.mf, usr/src/test/os-tests/tests/stackalign/stackalign.c, usr/src/test/util-tests/runfiles/default.run, usr/src/test/util-tests/tests/Makefile, usr/src/test/util-tests/tests/pcidb/Makefile, usr/src/test/util-tests/tests/pcidb/pcidbtest.ksh, usr/src/tools/onbld/Checks/DbLookups.py
Weekly upstream for upstream_merge/2021032601
None
```
OmniOS r151037  omnios-upstream_merge-2021032601-b7321237bf     March 2021
illumos development build: 2021-Mar-26 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2021032601-b7321237bf i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Mar 26 10:20:02 UTC 2021 ====
==== Nightly distributed build completed: Fri Mar 26 11:38:12 UTC 2021 ====
real    1:18:09
/usr/bin/uname
SunOS bloody 5.11 omnios-master-0401360920 i86pc i386 i86pc
cw version 5.0
Copyright (C) 2017 Free Software …
```
=> Upstream merge upstream_merge/2021032601

usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
```
==== Nightly distributed build started:   Sun Apr  4 00:05:55 UTC 2021 ====
==== Nightly distributed build completed: Sun Apr  4 01:21:34 UTC 2021 ====
real    1:15:38
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-c83a8f9e0b i86pc i386 i86pc
cw version 5.0 …
```
=> r151038 backports

usr/src/cmd/zoneadmd/zoneadmd.c, usr/src/lib/libbrand/common/libbrand.c, usr/src/lib/libbrand/common/libbrand.h, usr/src/lib/libbrand/common/mapfile-vers, usr/src/lib/libbrand/dtd/brand.dtd.1, usr/src/tools/scripts/onu.sh.in, usr/src/uts/common/os/exit.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/zone.h
```
==== Nightly distributed build started:   Sun Apr 18 10:14:34 UTC 2021 ====
==== Nightly distributed build completed: Sun Apr 18 11:32:48 UTC 2021 ====
real    1:18:13
/usr/bin/uname
SunOS bloody 5.11 omnios-master-cc133161da i86pc i386 i86pc
cw version 5.0 …
```
=>  Allow brands to control their init restart behaviour

README.OmniOS, usr/src/lib/libctf/common/ctf_dwarf.c, usr/src/lib/libdemangle/common/demangle.c, usr/src/lib/libdemangle/common/rust.c, usr/src/man/man3c/strtod.3c, usr/src/man/man3c/wcstod.3c, usr/src/man/man9f/scsi_hba_attach_setup.9f, usr/src/test/util-tests/tests/ctf/check-function.c, usr/src/test/util-tests/tests/ctf/test-function.c, usr/src/test/util-tests/tests/demangle/rust.c, usr/src/uts/common/fs/smbsrv/smb_tree.c, usr/src/uts/common/os/logsubr.c, usr/src/uts/common/sys/log.h, usr/src/uts/common/syscall/open.c
Weekly upstream for upstream_merge/2021042501
```
OmniOS r151037  omnios-upstream_merge-2021042501-b0f357568c7    April 2021
illumos development build: 2021-Apr-25 [illumos]
bloody%
SunOS bloody 5.11 omnios-upstream_merge-2021042501-b0f357568c7 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sun Apr 25 18:10:04 UTC 2021 ====
==== Nightly distributed build completed: Sun Apr 25 19:27:43 UTC 2021 ====
real    1:17:38
/usr/bin/uname
SunOS bloody 5.11 omnios-master-473317b31a i86pc i386 i86pc
cw version 5.0
This is …
```
=> Upstream merge upstream_merge/2021042501

.gitignore, usr/src/cmd/pcieadm/pcieadm.c, usr/src/cmd/pcieadm/pcieadm.h, usr/src/cmd/pcieadm/pcieadm_cfgspace.c, usr/src/lib/libdemangle/common/demangle.c, usr/src/lib/libdemangle/common/rust.c, usr/src/pkg/manifests/system-test-utiltest.mf, usr/src/test/util-tests/runfiles/default.run, usr/src/test/util-tests/tests/demangle/rust.c, usr/src/test/util-tests/tests/pcieadm/Makefile, usr/src/test/util-tests/tests/pcieadm/pcieadm-priv.ksh, usr/src/uts/common/os/logsubr.c, usr/src/uts/common/sys/log.h, usr/src/uts/common/syscall/open.c
```
==== Nightly distributed build started:   Sun Apr 25 19:55:16 UTC 2021 ====
==== Nightly distributed build completed: Sun Apr 25 21:13:12 UTC 2021 ====
real    1:17:56
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-3605dfceff i86pc i386 i86pc
cw version 5.0 …
```
=> Backports to r151038

usr/src/Makefile.master, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/bhyve/privileges.c, usr/src/cmd/bhyve/privileges.h, usr/src/man/man4/bhyve_config.4
```
==== Nightly distributed build started:   Tue May 11 14:15:16 UTC 2021 ====
==== Nightly distributed build completed: Tue May 11 15:33:40 UTC 2021 ====
real    1:18:23
/usr/bin/uname
SunOS bloody 5.11 omnios-master-0721c7dd962 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151039/7.5.0-il-1) 7.5.0 …
```
=> Add privilege management to bhyve

usr/src/cmd/syslogd/system-log.xml
When importing both `system-log` services on a newly booting system such as an ipkg or lipkg branded zone, `system-log:default` was ending up without a start or stop method, or any of the other properties.
```
bloody# zadm boot -c ipkg
[Connected to zone 'ipkg' console]
[NOTICE: Zone booting up]
OmniOS r151039 Version omnios-master-0721c7dd962 64-bit
Copyright (c) 2017-2021 OmniOS Community Edition (OmniOSce) Association.
Loading smf(5) service descriptions: 113/113
Hostname: ipkg
ipkg console login: root
Password:
OmniOS r151039  omnios-master-0721c7dd962       May 2021
root@ipkg:~# svcs -p system-log
STATE          STIME    FMRI
disabled       10:58:22 svc:/system/system-log:rsyslog
online         10:58:29 …
```
=> system-log:default does not import properly alongside system-log:rsyslog

usr/src/tools/scripts/onu.sh.in
This just makes an `onu` take longer than necessary for no benefit in almost all cases.
=> Disable IPS indexing when performing an onu

.gitignore, README.OmniOS, usr/src/uts/common/brand/lx/autofs/lx_autofs.c, usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/brand/lx/syscall/lx_mount.c, usr/src/uts/common/brand/lx/syscall/lx_prctl.c, usr/src/uts/common/brand/lx/syscall/lx_stat.c, usr/src/uts/common/fs/lookup.c, usr/src/uts/common/sys/file.h
Fixes #1011 
Tested booting various lx images including fedora34 which uses systemd v248. It does not start without the changes in this PR but does after.
```
[Connected to zone 'fedira34' console]
[NOTICE: Zone booting up]
systemd v248-2.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Welcome to Fedora 34 (Container Image)!
Hostname set to <LXCNAME>.
...
Fedora 34 (Container Image)
Kernel 4.4 on an x86_64 (console)
LXCNAME login:
```
```
==== Nightly distributed …
```
=> lx brand updates to support systemd >= v247

usr/src/cmd/csh/sh.c, usr/src/cmd/prtvtoc/prtvtoc.c, usr/src/cmd/zfs/zfs_main.c, usr/src/man/man1m/bhyve.1m, usr/src/man/man4/bhyve_config.4, usr/src/uts/common/fs/smbsrv/smb2_durable.c, usr/src/uts/common/fs/smbsrv/smb_user.c
* none
```
OmniOS r151039  omnios-upstream_merge-2021071801-e49f3274aa     July 2021
illumos development build: 2021-Jul-18 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2021071801-e49f3274aa i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sun Jul 18 12:25:20 CEST 2021 ====
==== Nightly distributed build completed: Sun Jul 18 13:47:09 CEST 2021 ====
real    1:21:49
/usr/bin/uname
SunOS mars 5.11 omnios-master-c2ced650b5 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151039/7.5.0-il-1) 7.5.0
This is free …
```
=> Upstream merge/2021071801

usr/src/boot/sys/boot/forth/support.4th, usr/src/cmd/cmd-inet/lib/ipmgmtd/ipmgmt_door.c, usr/src/lib/libipadm/common/ipadm_ipmgmt.h, usr/src/lib/nsswitch/files/Makefile.com, usr/src/man/man9f/nvlist_alloc.9f, usr/src/uts/i86pc/ml/kpti_trampolines.s, usr/src/uts/i86pc/sys/machprivregs.h, usr/src/uts/i86xpv/sys/machprivregs.h
Weekly upstream for upstream_merge/2021072201
None
```
OmniOS r151039  omnios-upstream_merge-2021072201-7fbf9dd9f18    July 2021
illumos development build: 2021-Jul-22 [illumos]
bloody%
bloody%
SunOS bloody 5.11 omnios-upstream_merge-2021072201-7fbf9dd9f18 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jul 22 23:01:31 UTC 2021 ====
==== Nightly distributed build completed: Fri Jul 23 00:17:19 UTC 2021 ====
real    1:15:47
/usr/bin/uname
SunOS bloody 5.11 omnios-master-7c6e2098d6 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151039/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free …
```
=> Upstream merge upstream_merge/2021072201

usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c
This fixes a regression with lx zones running images such as debian 10.
=> LX: revert /proc/<pid>/fd/ directories to symlinks

usr/src/lib/brand/lx/zone/lx_boot_zone_ubuntu.ksh
Currently `lx_boot_zone_ubuntu` manages /etc/resolv.conf if the user opts to manual manage the file, and not set resolvers and dns-domain in the zonecfg.
This is because `zone_attr()` will exit 0 even if the value is incorrect, `lx_boot` does not have this issue as it checks for a non empty value in stead. Applying the same change here makes ubuntu lx zones behave properly.
I tested by:
- boot a lx zone with resolvers and dns-domain set, copy /etc/resolv.conf
- replace lx_boot_zone_ubuntu
- boot a lx zone with resolvers and dns-domain set, diff /etc/resolv.conf /etc/resolv.conf.old --> no diff
- remove both resolvers and dns-domain from the zonecfg
- remove /etc/resolv.conf in the zone
- stop + boot the zone
- verify there is no /etc/resolv.conf create
The behavior before was a file with …
=> lx_boot_zone_ubuntu should check for non empty val

usr/src/uts/common/os/driver_lyr.c, usr/src/uts/common/os/strsubr.c, usr/src/uts/common/sys/sunldi_impl.h, usr/src/uts/i86pc/io/gfx_private/gfxp_bitmap.c
```
==== Nightly distributed build started:   Thu Sep 23 09:41:51 UTC 2021 ====
==== Nightly distributed build completed: Thu Sep 23 10:32:40 UTC 2021 ====
real    0:50:49
/usr/bin/uname
SunOS r151030 5.11 omnios-r151030-5bd7739fe4 i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151030/7.4.0-il-1) 7.4.0 …
```
=> Backports to r151030

.gitignore, usr/src/lib/krb5/plugins/kdb/ldap/Makefile.com, usr/src/uts/common/os/driver_lyr.c, usr/src/uts/common/os/strsubr.c, usr/src/uts/common/sys/sunldi_impl.h, usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/os/tscc_vmware.c
Weekly upstream for upstream_merge/2021092301
To all releases:
* 14098 handle failure when muxing non-device streams
(getting ready for upcoming wireguard improvements)
```
OmniOS r151039  omnios-upstream_merge-2021092301-90190fd5ac     September 2021
illumos development build: 2021-Sep-23 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2021092301-90190fd5ac i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Sep 23 08:55:53 UTC 2021 ====
==== Nightly distributed build completed: Thu Sep 23 10:30:41 UTC 2021 ====
real    1:34:48
/usr/bin/uname
SunOS bloody 5.11 omnios-master-8d191514879 i86pc i386 i86pc
cw version 5.0 …
```
=> Upstream merge upstream_merge/2021092301

usr/src/uts/common/os/driver_lyr.c, usr/src/uts/common/os/strsubr.c, usr/src/uts/common/sys/sunldi_impl.h
```
==== Nightly distributed build started:   Thu Sep 23 10:44:23 UTC 2021 ====
==== Nightly distributed build completed: Thu Sep 23 11:59:09 UTC 2021 ====
real    1:14:46
/usr/bin/uname
SunOS r151036 5.11 omnios-r151036-86a06d8a2c i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151036/7.5.0-il-1) 7.5.0 …
```
=> Backports to r151036

usr/src/boot/Makefile.version, usr/src/boot/sys/boot/common/dev_net.c, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/cmd-inet/usr.bin/tftp/Makefile, usr/src/cmd/cmd-inet/usr.bin/tftp/main.c, usr/src/cmd/cmd-inet/usr.bin/tftp/tftp.c, usr/src/data/hwdata/pci.ids, usr/src/data/hwdata/usb.ids, usr/src/lib/libvmmapi/common/vmmapi.c, usr/src/lib/libvmmapi/common/vmmapi.h, usr/src/man/man1/ctfdump.1, usr/src/man/man3c/mbrtoc16.3c, usr/src/pkg/manifests/system-data-hardware-registry.mf, usr/src/tools/cpcgen/Makefile, usr/src/uts/common/fs/zfs/vdev_raidz.c, usr/src/uts/common/fs/zfs/zvol.c, usr/src/uts/common/os/dkioc_free_util.c, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/sys/vmm_kernel.h, usr/src/uts/i86pc/io/vmm/vmm.c, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c, usr/src/uts/i86pc/os/fakebop.c, usr/src/uts/i86pc/sys/vmm_dev.h
Weekly upstream for upstream_merge/2021092901
To r151038 and r151036:
* 14115 dumping to zvol on raidz will corrupt the pool 
```
OmniOS r151039  omnios-upstream_merge-2021092901-747bf91a71     September 2021
illumos development build: 2021-Sep-29 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2021092901-747bf91a71 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Sep 29 08:21:42 UTC 2021 ====
==== Nightly distributed build completed: Wed Sep 29 09:42:02 UTC 2021 ====
real    1:20:19
/usr/bin/uname
SunOS bloody 5.11 omnios-master-583b18de89 i86pc i386 i86pc
cw version 5.0 …
```
=> Upstream merge upstream_merge/2021092901

usr/src/cmd/zoneadm/Makefile, usr/src/cmd/zoneadmd/Makefile, usr/src/cmd/zoneadmd/vplat.c, usr/src/cmd/zoneadmd/zoneadmd.c, usr/src/cmd/zoneadmd/zoneadmd.h, usr/src/cmd/zonecfg/Makefile, usr/src/cmd/zonecfg/zonecfg.c, usr/src/cmd/zonename/Makefile, usr/src/head/libzonecfg.h, usr/src/lib/brand/lx/zone/lx_boot_zone_ubuntu.ksh, usr/src/lib/libdladm/common/libdladm.h, usr/src/lib/libzonecfg/common/libzonecfg.c, usr/src/lib/libzonecfg/common/zonecfg_impl.h
Initially to address problems with `zoneadmd`'s stderr being lost, but also pulled in some other (old) fixes from SmartOS including support for longer attribute values, which will help with cloud-init and the `sshkey` option, and a fix to stop `zoneadmd` ending up with the environment of the shell that called `zoneadm` in the case of manually booting a zone.
=> Various fixes for zoneadmd

usr/src/uts/i86pc/Makefile.files, usr/src/uts/i86pc/os/tscc_hyperv.c, usr/src/uts/i86pc/unix/Makefile, usr/src/uts/intel/io/hyperv/sys/hyperv.h
This is a prerequisite for enabling Gen2 VM support (though there is still more work). It also works fine with Gen1 VMs (both Hyper-V and Azure) and will fallback to the existing methods if the MSRs are unsupported.
=> Add TSC calibration support using Hyper-V MSRs

usr/src/cmd/bhyve/smbiostbl.c, usr/src/cmd/smbios/smbios.c
* none
```
OmniOS r151041  omnios-upstream_merge-2021122901-276ff928b8     December 2021
illumos development build: 2021-Dec-29 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2021122901-276ff928b8 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Dec 29 12:23:46 CET 2021 ====
==== Nightly distributed build completed: Wed Dec 29 13:51:12 CET 2021 ====
real    1:27:25
/usr/bin/uname
SunOS mars 5.11 omnios-master-5dcfdfc0686 i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151041/7.5.0-il-1) 7.5.0
This is …
```
=> Upstream merge/2021122901

usr/src/lib/brand/lx/zone/lx_boot_zone_debian.ksh, usr/src/lib/brand/lx/zone/lx_boot_zone_redhat.ksh
After fixing zoneadmd so that it passes stderr back to zoneadm clients, booting some lx images is noisy, for example, devuan (which uses the debian boot script but does not have systemd):
```
bloody% pfexec zadm boot lx
zone 'lx': /usr/lib/brand/lx/lx_boot[151]: .[138]: /zones/lx/root/etc/init/network-interface-security.override: cannot create [No such file or directory]
zone 'lx': /usr/lib/brand/lx/lx_boot[151]: .[138]: /zones/lx/root/etc/init/udev.override: cannot create [No such file or directory]
zone 'lx': /usr/lib/brand/lx/lx_boot[151]: .[138]: /zones/lx/root/etc/init/udevmonitor.override: cannot create [No such file or directory]
zone 'lx': /usr/lib/brand/lx/lx_boot[151]: .[138]: /zones/lx/root/etc/init/udevtrigger.override: cannot create [No such file or directory]
zone 'lx': …
```
=> Errors from lx zone boot

usr/src/cmd/bhyve/pci_nvme.c
```
Loading modules: [ libumem.so.1 libc.so.1 libnvpair.so.1 libproc.so.1 ld.so.1 ]
> ::status
debugging core file of bhyve (64-bit) from bhyvetest
initial argv: bhyve-bhyvetest -k /etc/bhyve.cfg
threading model: native threads
status: process panicked
upanic message: *** libc mutex system failure: mutex_enter: bad mutex type\x0a
libc panic message: *** libc mutex system failure: mutex_enter: bad mutex type
> $C
fffffc7e9b945800 libc.so.1`syscall+0x30()
fffffc7e9b945820 libc.so.1`upanic+0x22(fffffc7e9b945850, 190)
fffffc7e9b945840 0xfffffc7feef4ae9d()
fffffc7e9b945a10 0xfffffc7feef4af84()
fffffc7e9b945a30 libc.so.1`mutex_panic+0x26(dfbf58, fffffc7feefc2023)
fffffc7e9b945a60 libc.so.1`mutex_enter+0x64(dfbf58)
fffffc7e9b945ae0 pci_nvme_handle_io_cmd+0x53(dd3010, 10)
fffffc7e9b945b40 …
```
=> bhyve: NVMe missed mutex initialisation

usr/src/lib/libdladm/common/libdladm.c, usr/src/lib/libdladm/common/libdladm.h, usr/src/lib/libdladm/common/libdlvnic.c, usr/src/uts/common/fs/vnode.c, usr/src/uts/common/io/cxgbe/common/common.h, usr/src/uts/common/io/cxgbe/common/t4_hw.c, usr/src/uts/common/io/cxgbe/firmware/t4fw_interface.h, usr/src/uts/common/io/cxgbe/t4nex/adapter.h, usr/src/uts/common/io/cxgbe/t4nex/t4_mac.c, usr/src/uts/common/io/cxgbe/t4nex/t4_nexus.c, usr/src/uts/i86pc/os/tscc_hpet.c, usr/src/uts/i86pc/os/tscc_pit.c
Weekly upstream for upstream_merge/2022031001
```
OmniOS r151041  omnios-upstream_merge-2022031001-51f61ef898     March 2022
illumos development build: 2022-Mar-10 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2022031001-51f61ef898 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Mar 10 23:15:16 UTC 2022 ====
==== Nightly distributed build completed: Fri Mar 11 00:58:54 UTC 2022 ====
real    1:43:38
/usr/bin/uname
SunOS bloody 5.11 omnios-master-b3f6954b58 i86pc i386 i86pc
cw version 6.1
This is free …
```
=> Upstream merge upstream_merge/2022031001

usr/src/uts/i86pc/io/isa.c, usr/src/uts/i86pc/os/ddi_impl.c
This should allow OmniOS to function as a Hyper-V Gen2 guest. The restriction is that the graphical/fb console does not work currently (the screen is blank after the kernel loads). Using a serial console does work (and is currently recommended). 
Getting the fb support to work will likely require more work to the vmbus driver. It should probably drive the probing of these fully virtualized bits -- serial ports and the frame buffer -- instead of the workaround here. However, that's currently an unknown amount of effort, and this change is small enough that it could easily be backed out (or really replaced) as part of integrating such work, and it gets things working in a usable (if not 100% optimal) state.
=> Hyper-V Gen2 VM support (serial console only)

usr/src/uts/intel/io/hyperv/README.sync, usr/src/uts/intel/io/hyperv/netvsc/hn_nvs.c, usr/src/uts/intel/io/hyperv/netvsc/if_hn.c, usr/src/uts/intel/io/hyperv/sys/hyperv.h, usr/src/uts/intel/io/hyperv/sys/vmbus.h, usr/src/uts/intel/io/hyperv/vmbus/hyperv.c, usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
Add VMBus protocol version 4.0. and 5.0 to support Windows 10 and newer HyperV
hosts.
For VMBus 4.0 and newer HyperV, the netvsc gpadl teardown must be done after
vmbus close.
@jasonbking
=> HYPERV: Update VMBus version 4.0 and 5.0 support.

usr/src/cmd/truss/print.c, usr/src/uts/common/sys/zone.h
While testing the `s10` brand under the upcoming r151042 release, a service failed to come online:
```
ipsecalgs: Unable to determine zone IP type: Invalid argument
zone_getattr(10, ZONE_ATTR_FLAGS, 0x08047DE8, 2) Err#22 EINVAL
```
Some dtrace showed that the branded zone was requesting attribute number `14`:
```
r151042# dtrace -n 'zone_getattr:entry/arg0==11/{self->t++; trace(arg1)}' -n 'zone_getattr:return/self->t/{self->t--; trace(arg1)}' -n 'zone_status_get:return/self->t/{trace(arg1)}' -n 'zone_list_access:return/self->t/{trace(arg1)}' -n 's10_getattr:entry/self->t/{trace(arg1)}' -n 's10_getattr:return/self->t/{trace(arg1)}'
CPU     ID                    FUNCTION:NAME
2  28085               zone_getattr:entry             32768
2  37731           zone_status_get:return …
```
=> Restore early ZONE_ATTR_ values

usr/src/cmd/bhyve/rfb.c
This is because the DES key is just the supplied password with the bits flipped, and the parity bits are usually all 0 (for a 7-bit ASCII password). OpenSSL 3 reports a parity error, openssl 1.1 and 1.0 do not.
I've tested this new version with all three versions of openssl.
=> bhyve VNC authentication fails with openssl3

usr/src/pkg/manifests/developer-build-onbld.p5m, usr/src/tools/find_elf/Makefile
We have some out-of-gate components which use `find_elf` and cannot find it following `14712 Replace find_elf with something faster`. This adds a symlink at the original location.
@jasonbking - do you think we should get this upstreamed too? I know that a few packages use onbld tools (illumos-kvm for example) but I don't know how many use `find_elf` outside of the OmniOS build stuff.
=> Add find_elf symlink in original location

usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
This small change was something I noticed while debugging HyperV.  I'm going to be submitting another PR that basically "rewrites" hv_storvsc (fixing numerous bugs along the way).
After this change, various extra nodes will show in the device tree (all the other nodes that vmbus creates but we don't have drivers for), and if you don't have a functional driver (because say you've moved it out of the way or it is buggy and doesn't attach), you can still attach a new one without needing to reboot.
It's unlikely that this will matter much to end users, but its a signficant quality of life improvement for anyone working on these drivers.  We also would like to follow good practices in case anyone decides to "copy" this code in the future.
=> HYPERV: vmbus ndi_devi_online should not destroy node if fails

usr/src/lib/brand/lx/lx_init/lxinit.c
@sjorge hit this when trying to give an lx zone both IPv4 and IPv6, the zone exited with 
```
lx_init err: ipadm_create_if error 10: ubtn0/v4: Interface already exists
```
given a zone configuration with:
```
- allowed-address: 10.23.10.159/20
defrouter: 10.23.10.1
global-nic: ixgbe0
mac-addr: 2:8:20:e5:1:33
physical: ubtn0
vlan-id: '100'
- allowed-address: xxxx:xxxx::xxxx/64
global-nic: ixgbe0
mac-addr: 2:8:20:e5:1:33
physical: ubtn0
vlan-id: '100'
```
=> lxinit should handle multiple IPs per VNIC

usr/src/uts/common/exec/elf/elf.c, usr/src/uts/common/exec/intp/intp.c, usr/src/uts/common/os/brand.c, usr/src/uts/common/os/core.c, usr/src/uts/common/os/exec.c, usr/src/uts/common/sys/brand.h
This re-syncs OmniOS with the final illumos-gate ELF hardening work in https://code.illumos.org/c/illumos-gate/+/1805
OmniOS already had most of this so the delta is pretty small, but brings in a different approach for dumping DWARF data into core dumps, which is the main diff in `elf.c`.
Before undrafting I will run a full gate build with these bits, check boot an lx and s10-branded zone and run the corefile testsuites.
```
==== Nightly distributed build started:   Wed Aug 31 15:50:26 UTC 2022 ====
==== Nightly distributed build completed: Wed Aug 31 17:07:04 UTC 2022 ====
real    1:16:38
/usr/bin/uname
SunOS bloody 5.11 omnios-master-585cb404c03 i86pc i386 i86pc
number of concurrent jobs …
```
=> 14236 signed math leads getelfshdr astray (re-sync)

usr/src/uts/intel/io/hyperv/storvsc/hv_storvsc_drv_illumos.c, usr/src/uts/intel/io/hyperv/storvsc/hv_vstorage.h
This is a rather large refactoring of the SCSI HBA driver for Hyper-V.
It has been reviewed by Jerry Jelinek at RackTop, but has received only light testing thus far.
(Note that it dropped an OmniOS copyright, because I started from the version prior to the OmniOS commit, but with this factor that change -- cc60b39673999c129e584bbcb78746ff7be6b7af -- is no longer needed at all.)
The code is rewritten to use iport(9) and the common tran_setup_pkt(9e) infrastructure.  It also removes support for HyperV versions before Windows 10.  (Rationale: Windows 8.1 is on Extended Support, which will end in January, and Azure -- the main target for this -- uses newer versions anyway.  We don't think anyone is actively using this with HyperV versions before that, and the workarounds for the older HyperV …
=> HYPERV: Hyper-V SCSI HBA Refactoring

usr/src/cmd/bhyve/pci_e82545.c, usr/src/cmd/bhyve/pci_nvme.c, usr/src/cmd/bhyve/pci_xhci.c
```
==== Nightly distributed build started:   Sun Sep 18 16:25:14 UTC 2022 ====
==== Nightly distributed build completed: Sun Sep 18 17:32:55 UTC 2022 ====
real    1:07:41
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-ee8a5b332a i86pc i386 i86pc
cw version 5.0 …
```
=> Bhyve backports (r151038)

usr/src/cmd/bhyve/pci_e82545.c, usr/src/cmd/bhyve/pci_emul.c, usr/src/cmd/bhyve/pci_nvme.c, usr/src/cmd/bhyve/pci_xhci.c
```
==== Nightly distributed build started:   Sun Sep 18 16:27:20 UTC 2022 ====
==== Nightly distributed build completed: Sun Sep 18 18:22:58 UTC 2022 ====
real    1:55:37
/usr/bin/uname
SunOS r151042 5.11 omnios-r151042-73702cd512 i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151042/10.3.0-il-1) 10.3.0
gcc (OmniOS 151042/7.5.0-il-1) 7.5.0
This is free …
```
=> Bhyve backports (r151042)

usr/src/cmd/hal/hald/solaris/sysevent.c, usr/src/test/bhyve-tests/tests/vmm/interface_version.c, usr/src/uts/intel/io/vmm/vmm_sol_dev.c
* none
```
OmniOS r151043  omnios-upstream_merge-2022092901-7ec4c74df51    September 2022
illumos development build: 2022-Sep-29 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2022092901-7ec4c74df51 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Sep 29 15:45:29 UTC 2022 ====
==== Nightly distributed build completed: Thu Sep 29 16:26:11 UTC 2022 ====
real    0:40:41
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-58966f25ef4 i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151043/10.4.0-il-1) 10.4.0
Copyright (C) 2020 Free Software Foundation, …
```
=> Upstream merge/2022092901

usr/src/cmd/zpool/zpool_main.c, usr/src/common/zfs/zprop_common.c, usr/src/pkg/manifests/system-test-ostest.p5m, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/Makefile, usr/src/test/os-tests/tests/regression/Makefile, usr/src/test/os-tests/tests/regression/illumos-15031.c, usr/src/uts/common/fs/proc/prdata.h, usr/src/uts/common/fs/proc/prsubr.c, usr/src/uts/common/fs/proc/prvnops.c, usr/src/uts/common/fs/zfs/sys/zfs_vfsops.h, usr/src/uts/common/fs/zfs/zfs_vfsops.c
```
==== Nightly distributed build started:   Tue Oct  4 15:20:32 UTC 2022 ====
==== Nightly distributed build completed: Tue Oct  4 16:40:59 UTC 2022 ====
real    1:20:27
/usr/bin/uname
SunOS r151044 5.11 omnios-r151044-8d2a88fb9d i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151044/10.4.0-il-1) 10.4.0
gcc (OmniOS 151044/7.5.0-il-1) 7.5.0
This is free …
```
=> Backports to r151044

exception_lists/packaging.deps, usr/src/Makefile.master
in parallel with python 3.10, for now.
=> Build python 3.11 modules

usr/src/lib/libc/port/threads/sigaction.c, usr/src/man/man2/getcontext.2, usr/src/pkg/manifests/system-test-ostest.p5m, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/Makefile, usr/src/test/os-tests/tests/ucontext.c
Approved by: Patrick Mooney <pmooney@pfmooney.com>
=> 15206 setcontext(2) should not restore %fsbase (r151044)

usr/src/boot/forth/beadm.4th, usr/src/boot/forth/support.4th, usr/src/cmd/pcieadm/pcieadm_cfgspace.c, usr/src/common/unicode/u8_textprep.c, usr/src/lib/libc/port/gen/isatty.c, usr/src/lib/libdladm/Makefile.com, usr/src/lib/libdladm/common/flowattr.c, usr/src/lib/libdladm/common/flowprop.c, usr/src/lib/libdladm/common/libdlaggr.c, usr/src/lib/libdladm/common/libdlib.c, usr/src/lib/libdladm/common/libdlstat.c, usr/src/lib/libdladm/common/linkprop.c, usr/src/lib/smbsrv/libsmb/Makefile.com, usr/src/lib/smbsrv/libsmb/common/smb_acl.c, usr/src/lib/smbsrv/libsmb/common/smb_domain.c, usr/src/lib/smbsrv/libsmb/common/smb_pwdutil.c, usr/src/man/man3c/isatty.3c, usr/src/pkg/manifests/system-test-libctest.p5m, usr/src/test/libc-tests/runfiles/default.run, usr/src/test/libc-tests/tests/Makefile, usr/src/test/libc-tests/tests/isatty.c
* [15286 do_composition() needs sign awareness](https://github.com/omniosorg/illumos-omnios/commit/f137b22e734e85642da3e56e8b94da3f5f027c73)
```
OmniOS r151045  omnios-upstream_merge-2022122601-bf5ae4914d     December 2022
illumos development build: 2022-Dec-26 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2022122601-bf5ae4914d i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Dec 26 12:14:29 UTC 2022 ====
==== Nightly distributed build completed: Mon Dec 26 12:54:54 UTC 2022 ====
real    0:40:25
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-9c871b379a6 i86pc i386 i86pc
number of concurrent jobs = …
```
=> Upstream merge/2022122601

usr/src/cmd/idmap/idmapd/idmap_lsa.c, usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c, usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c, usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c, usr/src/lib/smbsrv/libsmb/common/libsmb.h, usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
```
==== Nightly distributed build started:   Fri Dec 30 21:25:24 UTC 2022 ====
==== Nightly distributed build completed: Fri Dec 30 22:30:51 UTC 2022 ====
real    1:05:26
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-1d6c6e5c34 i86pc i386 i86pc
cw version 5.0 …
```
=> 15295 SMB services should check IPC caller privileges (r151038)

usr/src/cmd/idmap/idmapd/idmap_lsa.c, usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c, usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c, usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c, usr/src/lib/smbsrv/libsmb/common/libsmb.h, usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
```
==== Nightly distributed build started:   Fri Dec 30 21:25:47 UTC 2022 ====
==== Nightly distributed build completed: Fri Dec 30 23:43:01 UTC 2022 ====
real    2:17:14
/usr/bin/uname
SunOS r151042 5.11 omnios-r151042-4b7d907d8c i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151042/10.3.0-il-1) 10.3.0
gcc (OmniOS 151042/7.5.0-il-1) 7.5.0
This is free …
```
=> 15295 SMB services should check IPC caller privileges (r151042)

usr/src/cmd/idmap/idmapd/idmap_lsa.c, usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c, usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c, usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c, usr/src/lib/smbsrv/libsmb/common/libsmb.h, usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
```
==== Nightly distributed build started:   Fri Dec 30 21:26:16 UTC 2022 ====
==== Nightly distributed build completed: Fri Dec 30 23:39:41 UTC 2022 ====
real    2:13:24
/usr/bin/uname
SunOS r151044 5.11 omnios-r151044-e3132f191c i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151044/10.4.0-il-1) 10.4.0
gcc (OmniOS 151044/7.5.0-il-1) 7.5.0
This is free …
```
=> 15295 SMB services should check IPC caller privileges (r151044)

usr/src/cmd/idmap/idmapd/idmap_lsa.c, usr/src/cmd/smbsrv/smbd/smbd_authsvc.c, usr/src/cmd/smbsrv/smbd/smbd_doorsvc.c, usr/src/cmd/smbsrv/smbd/smbd_pipesvc.c, usr/src/cmd/smbsrv/smbd/smbd_share_doorsvc.c, usr/src/lib/smbsrv/libsmb/common/libsmb.h, usr/src/lib/smbsrv/libsmb/common/smb_doorclnt.c
```
==== Nightly distributed build started:   Fri Dec 30 21:19:56 UTC 2022 ====
==== Nightly distributed build completed: Fri Dec 30 23:35:31 UTC 2022 ====
real    2:15:34
/usr/bin/uname
SunOS bloody 5.11 omnios-master-3f10ed6a1c i86pc i386 i86pc
cw version 7.1
gcc (OmniOS 151045/10.4.0-il-1) 10.4.0
gcc (OmniOS 151045/7.5.0-il-1) 7.5.0
This is free software; …
```
=> 15295 SMB services should check IPC caller privileges

usr/src/uts/common/fs/smbsrv/smb_init.c
Reported by @gwr as a dangling difference between gate and omnios.
```
That appears to have come from this:
commit 1fe1b1faaf445ec3a6b487abdf733de481df202a
Author: Dan McDonald <danmcd@joyent.com>
Date:   Wed Aug 30 15:33:47 2017 -0400
OS-6319 Fix for OS-6297 forgot smb_ioc_svcenum_t
Reviewed by: Patrick Mooney <patrick.mooney@joyent.com>
Reviewed by: Mike Zeller <mike.zeller@joyent.com>
Approved by: Patrick Mooney <patrick.mooney@joyent.com>
And that was fixed in illumos with:
commit 5f3b52abece3d89262210be84196e7367cd279d2
Author: Gordon Ross <gwr@nexenta.com>
Date:   Mon Aug 28 21:50:05 2017 +0000
8662 SMB server ioctls should be appropriately sized.
Reviewed by: Dan McDonald …
```
=> 8662 SMB server ioctls should be appropriately sized (fix mismerge)

usr/src/cmd/dlmgmtd/dlmgmt_db.c, usr/src/cmd/dlmgmtd/dlmgmt_door.c, usr/src/cmd/dlmgmtd/dlmgmt_impl.h, usr/src/cmd/dlmgmtd/dlmgmt_main.c, usr/src/cmd/dlmgmtd/dlmgmt_util.c, usr/src/cmd/zoneadmd/vplat.c, usr/src/lib/libdladm/common/libdladm.h, usr/src/lib/libdladm/common/libdlmgmt.c, usr/src/uts/common/io/dld/dld_drv.c, usr/src/uts/common/io/dls/dls_mgmt.c, usr/src/uts/common/os/zone.c, usr/src/uts/common/sys/dls_mgmt.h
```
==== Nightly distributed build started:   Mon Mar 27 12:35:05 UTC 2023 ====
==== Nightly distributed build completed: Mon Mar 27 13:52:43 UTC 2023 ====
real    1:17:38
/usr/bin/uname
SunOS bloody 5.11 omnios-master-69de2a5279f i86pc i386 i86pc
cw version 8.0
gcc (OmniOS 151045/10.4.0-il-1) 10.4.0
gcc (OmniOS 151045/7.5.0-il-1) 7.5.0
This is free software; …
```
=> Upstream merge datalink improvements.

usr/src/lib/libctf/common/ctf_dwarf.c, usr/src/lib/libctf/common/ctf_lib.c
This is cherry picked from arm64-gate and it extends libctf.so so that we can do more CTF conversions for aarch64 artefacts.
=> AARCH64: add support to libctf

usr/src/cmd/idmap/idmapd/dbutils.c, usr/src/cmd/idmap/idmapd/idmap.xml, usr/src/cmd/idmap/idmapd/idmap_config.c, usr/src/cmd/idmap/idmapd/idmap_config.h, usr/src/cmd/idmap/idmapd/idmapd.h, usr/src/cmd/idmap/idmapd/init.c, usr/src/lib/libadutils/common/addisc.c
```
==== Nightly distributed build started:   Sat Jul  1 07:03:52 UTC 2023 ====
==== Nightly distributed build completed: Sat Jul  1 07:50:44 UTC 2023 ====
real    0:46:52
/usr/bin/uname
SunOS r151046 5.11 omnios-r151046-f51538a8df i86pc i386 i86pc
cw version 8.0
gcc (OmniOS 151046/10.4.0-il-1) 10.4.0
/usr/jdk/openjdk11.0/bin/javac
openjdk full version "11.0.19+7-omnios-151046"
/usr/bin/openssl
OpenSSL 3.0.9 30 May 2023 (Library: …
```
=> Upstream idmap fixes (r151046)

usr/src/cmd/idmap/idmapd/dbutils.c, usr/src/cmd/idmap/idmapd/idmap.xml, usr/src/cmd/idmap/idmapd/idmap_config.c, usr/src/cmd/idmap/idmapd/idmap_config.h, usr/src/cmd/idmap/idmapd/idmapd.h, usr/src/cmd/idmap/idmapd/init.c, usr/src/lib/libadutils/common/addisc.c
```
==== Nightly distributed build started:   Sat Jul  1 07:03:59 UTC 2023 ====
==== Nightly distributed build completed: Sat Jul  1 07:55:54 UTC 2023 ====
real    0:51:54
/usr/bin/uname
SunOS r151044 5.11 omnios-r151044-e3d9e095a8 i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151044/10.4.0-il-1) 10.4.0
/usr/jdk/openjdk11.0/bin/javac
openjdk full version "11.0.19+7-omnios-151044"
/usr/bin/openssl
OpenSSL 3.0.8 7 Feb 2023 (Library: …
```
=> Upstream idmap fixes (r151044)

usr/src/cmd/idmap/idmapd/dbutils.c, usr/src/cmd/idmap/idmapd/idmap.xml, usr/src/cmd/idmap/idmapd/idmap_config.c, usr/src/cmd/idmap/idmapd/idmap_config.h, usr/src/cmd/idmap/idmapd/idmapd.h, usr/src/cmd/idmap/idmapd/init.c, usr/src/lib/libadutils/common/addisc.c
```
==== Nightly distributed build started:   Sat Jul  1 07:03:57 UTC 2023 ====
==== Nightly distributed build completed: Sat Jul  1 08:03:01 UTC 2023 ====
real    0:59:03
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-8ccf9ed9ab i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151038/7.5.0-il-2) 7.5.0
/usr/jdk/openjdk11.0/bin/javac
openjdk full version "11.0.19+7-omnios-151038"
/usr/bin/openssl
OpenSSL 1.1.1u  30 May 2023 …
```
=> Upstream idmap fixes (r151038)

.gitignore, usr/src/boot/Makefile.inc, usr/src/cmd/cmd-inet/usr.bin/telnet/ring.c, usr/src/cmd/ipf/tools/ipfcomp.c, usr/src/lib/smbsrv/libfksmbsrv/common/fksmb_idmap.c, usr/src/lib/smbsrv/libmlsvc/common/smb_logon.c, usr/src/lib/smbsrv/libsmb/common/smb_acl.c, usr/src/lib/smbsrv/libsmb/common/smb_idmap.c, usr/src/man/man9e/mac.9e, usr/src/uts/common/exec/elf/elf_notes.c, usr/src/uts/common/fs/proc/prsubr.c, usr/src/uts/common/fs/proc/prvnops.c, usr/src/uts/common/fs/smbsrv/smb2_durable.c, usr/src/uts/common/fs/smbsrv/smb_acl.c, usr/src/uts/common/fs/smbsrv/smb_idmap.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_user.c, usr/src/uts/common/inet/ipf/fil.c, usr/src/uts/common/inet/ipf/ip_htable.c, usr/src/uts/common/smbsrv/smb_idmap.h
Weekly upstream for upstream_merge/2023071301
To all releases:
- 15779 libuuid can produce invalid V4 UUIDs
- 15788 kernel stack leak through prgetsecflags()
- 14306 Can't get SID for ID=0 type=0, status=-9977
```
OmniOS r151047 Version omnios-upstream_merge-2023071301-467ec3a905f 64-bit
Copyright (c) 2017-2023 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Tue Jul 11 20:52:40 2023 on console
OmniOS r151047  omnios-upstream_merge-2023071301-467ec3a905f    July 2023
illumos development build: 2023-Jul-13 [illumos]
root@bloody:~#
SunOS bloody 5.11 omnios-upstream_merge-2023071301-467ec3a905f i86pc i386 i86pc
``` …
=> Upstream merge upstream_merge/2023071301

usr/src/uts/common/brand/lx/syscall/lx_socket.c
This fixes https://github.com/omniosorg/illumos-omnios/issues/1219
When a IPv6 resolver was in /etc/resolv.conf the system was unable to resolve any hostnames, after poking around with dtrace
```
root@saturn:~# ./lxunsup.d
PID                 NAME CALL
10698                 curl NOSYS (334): out of bounds\0
10698                 curl NOSYS (435): out of bounds\0
10698                 curl setsockopt(41, 25)\0
10698                 curl setsockopt(41, 25)\0
```
Seems we hut some issues in setsockopt, we can verify it's missing options 25 for proto 41
```
root@saturn:~# ./lxsockops.d
PID                 NAME PROTO SOCKOPT
10727                 curl    41 25
10727                 curl    41 25
```
As @danmcd pointed out https://github.com/omniosorg/illumos-omnios/issues/1219#issuecomment-1723 …
=> lx branded zones should treat IPV6_RECVERR the same IP_ counter part

usr/src/cmd/pgrep/pgrep.c
=> pgrep -n/-o uses wrong process argv

usr/src/cmd/cmd-inet/usr.bin/nc/socks.c, usr/src/lib/libc/port/regex/engine.c, usr/src/lib/libc/port/regex/regcomp.c, usr/src/lib/libc/port/regex/regex2.h, usr/src/lib/libc/port/regex/regexec.c, usr/src/lib/libc/port/regex/regfree.c, usr/src/lib/libc/port/regex/utils.h, usr/src/lib/libfru/Makefile.flag, usr/src/lib/libfru/libfru/Parser.cc, usr/src/lib/libfru/libfru/nameSyntaxYacc.y, usr/src/man/man3c/regcomp.3c, usr/src/test/util-tests/tests/ctf/check-common.c
* none
```
OmniOS r151049  omnios-upstream_merge-2024010401-be0b3eb938c    January 2024
illumos development build: 2024-Jan-04 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2024010401-be0b3eb938c i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jan  4 16:48:21 UTC 2024 ====
==== Nightly distributed build completed: Thu Jan  4 17:24:46 UTC 2024 ====
real    0:36:25
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-973ed9565af i86pc i386 i86pc
cw version 9.0
gcc (OmniOS 151049/10.5.0-il-1) 10.5.0 …
```
=> Upstream merge/2024010401

usr/src/uts/i86pc/os/fakebop.c, usr/src/uts/i86pc/os/pci_cfgspace.c
16237 Add BIOS INT call results to early debug output
Reviewed by: Bill Sommerfeld <sommerfeld@hamachi.org>
Reviewed by: Gordon Ross <Gordon.W.Ross@gmail.com>
Reviewed by: Keith Wesolowski <wesolows@oxide.computer>
=> 16234 BIOS PCI detection failure results in only bus 0 being enumerated (r151046)

usr/src/uts/i86pc/os/fakebop.c, usr/src/uts/i86pc/os/pci_cfgspace.c
16237 Add BIOS INT call results to early debug output
Reviewed by: Bill Sommerfeld <sommerfeld@hamachi.org>
Reviewed by: Gordon Ross <Gordon.W.Ross@gmail.com>
Reviewed by: Keith Wesolowski <wesolows@oxide.computer>
=> 16234 BIOS PCI detection failure results in only bus 0 being enumerated (r151048)

usr/src/uts/i86pc/os/tscc_vmware.c
This fixes booting on AWS Nitro instances, where the PIT is broken. These
instances support CPUID leaf 0x40000010 for retrieving the TSC directly.
=> 16222 TSC vmware calibration could be more general (interim)

usr/src/uts/i86pc/io/vmm/intel/vmx_support.s, usr/src/uts/i86pc/os/cpuid.c, usr/src/uts/intel/ia32/ml/retpoline.s, usr/src/uts/intel/sys/x86_archext.h
…in HW
commit 34060b797a
Conflicts:
usr/src/uts/i86pc/io/vmm/intel/vmx_support.s
usr/src/uts/i86pc/os/cpuid.c
usr/src/uts/intel/sys/x86_archext.h
=> 16413 Post-barrier Return Stack Buffer (PBRSB) fixes can be detected … (r151038)

README.OmniOS, usr/src/cmd/truss/Makefile, usr/src/cmd/truss/codes.c, usr/src/cmd/truss/codes.h, usr/src/cmd/truss/codes_bhyve.c, usr/src/lib/libc/port/gen/memalign.c, usr/src/lib/libtermcap/Makefile, usr/src/lib/libtermcap/common/xtermcap.h, usr/src/lib/libumem/common/umem.c, usr/src/man/man3c/aligned_alloc.3c, usr/src/pkg/manifests/system-header.p5m, usr/src/pkg/manifests/system-test-libctest.p5m, usr/src/test/libc-tests/runfiles/default.run, usr/src/test/libc-tests/tests/Makefile, usr/src/test/libc-tests/tests/aligned_alloc.c, usr/src/test/libc-tests/tests/aligned_alloc.ksh, usr/src/test/os-tests/tests/fifo-tvnsec.c, usr/src/uts/common/brand/lx/sys/lx_fcntl.h, usr/src/uts/common/brand/lx/syscall/lx_fcntl.c, usr/src/uts/common/inet/ip/icmp.c, usr/src/uts/common/inet/udp/udp.c, usr/src/uts/common/io/blkdev/blkdev.c, usr/src/uts/common/io/nvme/nvme.c, usr/src/uts/common/io/nvme/nvme_var.h, usr/src/uts/common/sys/blkdev.h
* 16579 bhyve: xhci tablet device probe fails under recent Linux kernels
* OS-8543 Want support for OFD locks in lx-brand
```
OmniOS r151051  omnios-upstream_merge-2024053001-fec05c08d27    May 2024
illumos development build: 2024-May-30 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2024053001-fec05c08d27 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu May 30 15:29:45 UTC 2024 ====
==== Nightly distributed build completed: Thu May 30 16:06:07 UTC 2024 ====
real    0:36:22
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-615aba20106 i86pc i386 i86pc
cw version 9.0 …
```
=> Upstream merge/2024053001

.gitignore, usr/src/lib/libc/port/threads/synch.c, usr/src/test/libc-tests/tests/clocklock/Makefile, usr/src/test/libc-tests/tests/clocklock/clock_lock_cond.c, usr/src/test/libc-tests/tests/clocklock/clock_lock_mutex.c, usr/src/test/libc-tests/tests/clocklock/clock_lock_rwlock.c, usr/src/test/libc-tests/tests/clocklock/clock_lock_sem.c, usr/src/uts/common/brand/lx/syscall/lx_dup.c, usr/src/uts/common/brand/lx/syscall/lx_fcntl.c, usr/src/uts/common/brand/lx/syscall/lx_open.c
Weekly upstream for upstream_merge/2024073001
None
```
OmniOS r151051 Version omnios-upstream_merge-2024073001-6a0f1e6a8c9 64-bit
Copyright (c) 2017-2024 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Fri Jul 26 14:21:10 2024 on console
OmniOS r151051  omnios-upstream_merge-2024073001-6a0f1e6a8c9    July 2024
illumos development build: 2024-Jul-30 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2024073001-6a0f1e6a8c9 i86pc i386 i86pc
```
Also tested booting an ubuntu lx zone, which was successful:
```
root@lx:~# systemctl status
● lx
State: running
Jobs: 0 queued
Failed: 0 units
Since: Tue 2024-07-30 14:19:30 UTC; 28s ago …
```
=> Upstream merge upstream_merge/2024073001

.gitignore, usr/src/cmd/cmd-inet/usr.lib/wpad/Makefile, usr/src/cmd/dtrace/test/tst/common/print/tst.xlate.d, usr/src/cmd/dtrace/test/tst/common/print/tst.xlate.d.out, usr/src/cmd/sendmail/src/Makefile, usr/src/lib/krb5/plugins/preauth/pkinit/Makefile.com, usr/src/lib/libdtrace/common/dt_cg.c, usr/src/lib/libkmf/plugins/kmf_openssl/Makefile.com, usr/src/pkg/manifests/driver-network-vioif.p5m, usr/src/test/zfs-tests/include/libtest.shlib, usr/src/uts/common/io/1394/t1394.c, usr/src/uts/common/io/cardbus/cardbus.c, usr/src/uts/common/io/ib/clients/of/sol_ofs/sol_kverbs.c, usr/src/uts/common/io/vioif/THIRDPARTYLICENSE, usr/src/uts/common/io/vioif/THIRDPARTYLICENSE.descrip, usr/src/uts/common/os/ipc.c
Weekly upstream for upstream_merge/2024112701
None
```
OmniOS r151053 Version omnios-upstream_merge-2024112701-5cdacf2c8bf 64-bit
Copyright (c) 2017-2024 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
OmniOS r151053  omnios-upstream_merge-2024112701-5cdacf2c8bf    November 2024
illumos development build: 2024-Nov-27 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2024112701-5cdacf2c8bf i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Nov 27 15:26:31 UTC 2024 ====
==== Nightly distributed build completed: Wed Nov 27 16:39:49 UTC 2024 ====
real    1:13:17 …
```
=> Upstream merge upstream_merge/2024112701

usr/src/tools/env/omnios-illumos-omnios.sh
With the upcoming change to gcc14 as the shadow compiler in gate, we should remove this old workaround.
See https://www.illumos.org/issues/16935 for the gate change.
=> Prepare for gcc14 shadow

.gitignore, usr/src/cmd/bhyve/common/pci_virtio_viona.c, usr/src/cmd/devmgmt/cmds/devfree.c, usr/src/cmd/devmgmt/cmds/devreserv.c, usr/src/cmd/fs.d/fslib.c, usr/src/cmd/power/handlers.c, usr/src/cmd/svc/startd/method.c, usr/src/data/hwdata/pci.ids, usr/src/data/hwdata/usb.ids, usr/src/lib/smbclnt/libfksmbfs/common/fake_fssub.c, usr/src/pkg/manifests/system-data-hardware-registry.p5m, usr/src/test/util-tests/tests/find/findroot.ksh, usr/src/uts/common/fs/fs_subr.c, usr/src/uts/common/fs/gfs.c, usr/src/uts/common/fs/smbclnt/netsmb/smb_rq.c, usr/src/uts/common/fs/smbclnt/smbfs/smbfs_vnops.c, usr/src/uts/common/fs/zfs/dnode.c, usr/src/uts/common/io/dld/dld_drv.c, usr/src/uts/common/io/nvme/nvme.c, usr/src/uts/common/io/nvme/nvme_var.h, usr/src/uts/common/syscall/tasksys.c, usr/src/uts/intel/promif/prom_emul.c
Weekly upstream for upstream_merge/2025020701
None
```
OmniOS r151053 Version omnios-upstream_merge-2025020701-14af648076b 64-bit
Copyright (c) 2017-2025 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Tue Oct 15 10:52:22 2024 from 172.27.10.79
OmniOS r151053  omnios-upstream_merge-2025020701-14af648076b    February 2025
illumos development build: 2025-Feb-07 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2025020701-14af648076b i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Feb  7 17:30:43 UTC 2025 ====
==== Nightly distributed build completed: Fri Feb  7 18:45:56 UTC 2025 ====
==== …
```
=> Upstream merge upstream_merge/2025020701

usr/src/uts/common/brand/lx/os/lx_brand.c
Grafana overrides default stack size, but it is ignored by reason above, ELF header is parsing wrongly.
=> #1551  lx_brand: Fix small stack size due to wrong elf header parsing (ed_phdr)

usr/src/uts/intel/io/hyperv/vmbus/hyperv.c
We currently see the `desc` field twice during a verbose boot:
Hyper-V featuresHyper-V features: 0x00000000
Hyper-V guest recommendationsHyper-V guest recommendations: 0x00000000
=> HYPERV: feature descriptions printed out twice

usr/src/cmd/fm/modules/common/fabric-xlate/fabric-xlate.c, usr/src/cmd/isns/isnsd/door.c, usr/src/cmd/isns/isnsd/xml/data.c, usr/src/cmd/svc/svccfg/svccfg_xml.c, usr/src/lib/fm/topo/libtopo/common/topo_xml.c, usr/src/lib/libbrand/common/libbrand.c, usr/src/lib/libpool/common/pool_kernel.c, usr/src/lib/libpool/common/pool_xml.c, usr/src/lib/libsocket/inet/getifaddrs.c, usr/src/lib/libzonecfg/common/libzonecfg.c
This issue has shown up on a system running r151046. Let's get it backported and into next week's release.
=> 15633 libsocket: getallifaddrs() can die with NULL pointer dereference (r151046)

README.OmniOS, usr/src/cmd/bhyve/common/pci_virtio_console.c, usr/src/cmd/mdb/intel/mdb/mdb_bhyve.c, usr/src/lib/brand/lx/lx_init/lxinit.c, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/procfs/lx_proc.h, usr/src/uts/common/brand/lx/procfs/lx_prvnops.c, usr/src/uts/common/io/cxgbe/t4nex/adapter.h, usr/src/uts/common/io/cxgbe/t4nex/t4_mac.c, usr/src/uts/common/io/cxgbe/t4nex/t4_nexus.c, usr/src/uts/common/io/cxgbe/t4nex/t4_sge.c
* none
```
OmniOS r151055  omnios-upstream_merge-2025082801-b7d2e8c3df5    August 2025
illumos development build: 2025-Aug-28 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2025082801-b7d2e8c3df5 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Aug 28 15:12:46 UTC 2025 ====
==== Nightly distributed build completed: Thu Aug 28 15:48:37 UTC 2025 ====
real    0:35:50
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-ee5eb697ca9 i86pc i386 i86pc
cw version 10.0
gcc (OmniOS 151055/10.5.0-il-2) 10.5.0 …
```
=> Upstream merge/2025082801
