usr/src/boot/Makefile.version, usr/src/boot/sys/boot/i386/libi386/biosdisk.c, usr/src/cmd/ztest/ztest.c, usr/src/lib/libzfs/common/libzfs_dataset.c, usr/src/lib/libzfs_core/common/libzfs_core.c, usr/src/lib/libzfs_core/common/libzfs_core.h, usr/src/lib/libzfs_core/common/mapfile-vers, usr/src/uts/common/fs/zfs/dmu.c, usr/src/uts/common/fs/zfs/dsl_bookmark.c, usr/src/uts/common/fs/zfs/dsl_dataset.c, usr/src/uts/common/fs/zfs/sys/dsl_dataset.h, usr/src/uts/common/fs/zfs/zfs_ioctl.c, usr/src/uts/common/fs/zfs/zfs_vnops.c, usr/src/uts/common/fs/zfs/zvol.c, usr/src/uts/common/io/mr_sas/mr_sas.h, usr/src/uts/common/io/mr_sas/mr_sas_tbolt.c, usr/src/uts/i86pc/io/apix/apix.c, usr/src/uts/i86pc/io/pcplusmp/apic.c
Here's a small set of fairly straightforward backports to r151022.
mail_msg:
```
==== Nightly distributed build started:   Wed Jul  5 23:13:06 UTC 2017 ====
==== Nightly distributed build completed: Wed Jul  5 23:57:17 UTC 2017 ====
real    0:44:11
/usr/bin/uname
SunOS build 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc
openjdk full version "1.7.0_101-b00"
/usr/bin/as
as: Sun …
```
=> r151022 backport/2017070501

usr/src/cmd/ptools/pfiles/pfiles.c, usr/src/pkg/manifests/system-test-ostest.mf, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/Makefile, usr/src/test/os-tests/tests/pf_key/Makefile, usr/src/test/os-tests/tests/pf_key/acquire-compare.sh, usr/src/test/os-tests/tests/pf_key/acquire-spray.sh, usr/src/test/os-tests/tests/pf_key/eacq-enabler.c, usr/src/uts/common/inet/ip/ipsecah.c, usr/src/uts/common/inet/ip/ipsecesp.c, usr/src/uts/common/inet/ip/keysock.c, usr/src/uts/common/inet/ip/sadb.c, usr/src/uts/common/inet/ip/spd.c, usr/src/uts/common/inet/ip/spdsock.c, usr/src/uts/common/inet/ipsec_impl.h, usr/src/uts/common/inet/ipsecah.h, usr/src/uts/common/inet/ipsecesp.h, usr/src/uts/common/inet/sadb.h, usr/src/uts/intel/ia32/ml/modstubs.s, usr/src/uts/sparc/ml/modstubs.s
It's a bit unusual, but I'd like these kernel changes to land in the r151022 branch.  I'm happy to take any maintenance hits if anyone uses IPsec on r151022, because I would be doing the same. I did "git cherrypick" to pull them, and merge them in properly.
=> IPsec backports for r151022

README.OmniOS
... and remove lx merge status as this is tracked in bloody.
=> Add pending packages to README.OmniOS

README.OmniOS, usr/src/lib/brand/lx/zone/Makefile, usr/src/lib/brand/lx/zone/lx_boot.ksh, usr/src/lib/brand/lx/zone/lx_boot_zone_suse.ksh, usr/src/pkg/manifests/system-zones-brand-lx.mf, usr/src/uts/common/brand/lx/syscall/lx_socket.c
Upstream merge from `illumos-joyent`.
* none
```
SunOS mars 5.11 omnios-joyent_merge-2017091401-62193b8906 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Sep 14 18:05:09 CEST 2017 ====
==== Nightly distributed build completed: Thu Sep 14 19:07:22 CEST 2017 ====
real    1:02:12
/usr/bin/uname
SunOS mars 5.11 omnios-master-5480e1c069 i86pc i386 i86pc
32-bit …
```
=> Joyent merge/2017091401

usr/src/uts/common/fs/smbsrv/smb_init.c
see https://github.com/omniosorg/illumos-omnios/pull/56
=> fixing kernel CIFS (r151022)

usr/src/boot/Makefile.version, usr/src/boot/sys/boot/zfs/zfsimpl.c, usr/src/boot/sys/cddl/boot/zfs/zfsimpl.h, usr/src/cmd/mdb/common/modules/dtrace/dtrace.c, usr/src/cmd/mdb/common/modules/genunix/genunix.c, usr/src/cmd/mdb/common/modules/mdb_ks/mdb_ks.c, usr/src/cmd/mdb/common/modules/ptm/ptm.c, usr/src/cmd/tail/tail.c, usr/src/cmd/tail/tests/sun_solaris_tail.sh, usr/src/cmd/tail/tests/tailtests.sh, usr/src/man/man1m/acpidump.1m, usr/src/man/man1m/acpixtract.1m, usr/src/man/man9f/mac_register.9f, usr/src/test/test-runner/cmd/run
none
```
==== Nightly distributed build started:   Sat Oct  7 07:50:41 UTC 2017 ====
==== Nightly distributed build completed: Sat Oct  7 08:54:24 UTC 2017 ====
real    1:03:43
/usr/bin/uname
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 08/03/2009
/usr/ccs/bin/ld
ld: …
```
=> Upstream merge/2017100701

usr/src/lib/libdiskmgt/common/disks_private.h, usr/src/lib/libdiskmgt/common/drive.c, usr/src/lib/libdiskmgt/common/findevs.c, usr/src/lib/libdiskmgt/common/libdiskmgt.h, usr/src/lib/libdiskmgt/common/slice.c, usr/src/uts/common/inet/ip/ip6_ire.c, usr/src/uts/common/io/dld/dld_proto.c, usr/src/uts/common/sys/model.h, usr/src/uts/common/xen/io/xpvd.c, usr/src/uts/i86pc/os/startup.c, usr/src/uts/i86pc/os/trap.c, usr/src/uts/intel/sys/acpi/platform/acsolaris.h
* none
```
SunOS mars 5.11 omnios-upstream_merge-2017101201-cd7b419cc9 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct 12 11:52:37 CEST 2017 ====
==== Nightly distributed build completed: Thu Oct 12 12:49:50 CEST 2017 ====
real    0:57:13
/usr/bin/uname
SunOS mars 5.11 omnios-master-5975598b2d i86pc i386 i86pc …
```
=> Upstream merge/2017101201

usr/src/pkg/manifests/consolidation-man-man-incorporation.mf, usr/src/pkg/manifests/driver-network-llc2.mf, usr/src/pkg/manifests/service-network-snmp-mibiisa.mf, usr/src/pkg/manifests/source-network-pppdump.mf, usr/src/pkg/manifests/source-security-tcp-wrapper.mf, usr/src/pkg/manifests/system-library-storage-scsi-plugin.mf, usr/src/pkg/manifests/system-management-snmp-sea.mf, usr/src/pkg/manifests/system-manual.mf
=> Publish obsoleted packages with correct ONNV build number (r151024)

usr/src/pkg/manifests/consolidation-man-man-incorporation.mf, usr/src/pkg/manifests/system-library-storage-scsi-plugin.mf
backport for https://github.com/omniosorg/illumos-omnios/pull/77
=> Remove continuation lines that upset pkgfmt (r151024)

usr/src/cmd/fs.d/autofs/autod_nfs.c, usr/src/cmd/fs.d/autofs/ns_files.c, usr/src/common/ficl/vm.c, usr/src/common/zfs/zfs_namecheck.c, usr/src/ucblib/librpcsoc/clnt_tcp.c
Weekly upstream gate merge
None
```
==== Nightly distributed build started:   Thu Oct 26 10:22:38 UTC 2017 ====
==== Nightly distributed build completed: Thu Oct 26 11:28:28 UTC 2017 ====
real    1:05:49
/usr/bin/uname
/usr/bin/as
as: Sun Compiler Common 12 SunOS_i386 snv_121 …
```
=> Upstream merge/2017102601

usr/src/tools/env/omnios-illumos-gate.sh, usr/src/tools/env/omnios-illumos-omnios.sh
Update bloody version following branch for r151024
=> Bump bloody version to 151025

usr/src/uts/common/brand/lx/syscall/lx_prctl.c
=> Use passed name argument if thread name not yet set (r151024)

usr/src/cmd/pfexecd/pfexecd.xml, usr/src/cmd/rpcbind/bind.xml, usr/src/cmd/sendmail/lib/smtp-sendmail.xml
These three are active in a fresh OmniOS installation.
Are there any more for the list?
=> Enable ASLR for network-facing and security processes

README.OmniOS
only updating `Last illumos-joyent commit`
=> Update README.OmniOS with last Joyent commit

usr/src/cmd/mailwrapper/mailer.conf, usr/src/cmd/mailwrapper/pathnames.h, usr/src/pkg/manifests/system-network-mailwrapper.mf
=> mailwrapper should use dma by default on OmniOS

README.OmniOS, usr/src/pkg/manifests/system-test-zfstest.mf, usr/src/test/zfs-tests/tests/functional/slog/slog_015_neg.ksh, usr/src/uts/common/fs/zfs/sys/zil.h, usr/src/uts/common/fs/zfs/sys/zil_impl.h, usr/src/uts/common/fs/zfs/sys/zio.h, usr/src/uts/common/fs/zfs/zfs_znode.c, usr/src/uts/common/fs/zfs/zil.c, usr/src/uts/common/fs/zfs/zio.c
see: https://github.com/omniosorg/illumos-omnios/pull/122
=> zfs backports (r151024)

usr/src/uts/common/fs/smbsrv/smb_kshare.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/os/kstat_fr.c, usr/src/uts/common/os/mem_config.c, usr/src/uts/common/os/vm_pageout.c, usr/src/uts/common/smbsrv/smb_ioctl.h, usr/src/uts/common/sys/vm.h, usr/src/uts/common/sys/vmsystm.h, usr/src/uts/common/vm/vm_page.c, usr/src/uts/i86pc/vm/vm_machdep.c
see: https://github.com/omniosorg/illumos-omnios/pull/127 and https://github.com/omniosorg/illumos-omnios/pull/128
=> backports for r151024

README.OmniOS
will be published with `r151024j`
=> remove pending zfs patches from README.OmniOS

README.OmniOS
empty, just keeping up with Joyent's commits.
=> Joyent_merge/2018012601

usr/src/uts/i86pc/io/todpc_subr.c
Reviewed by: Yuri Pankov <yuripv@icloud.com>
=> 8680 Time of Day clock error (r151022)

usr/src/uts/i86pc/io/todpc_subr.c
Reviewed by: Yuri Pankov <yuripv@icloud.com>
=> 8680 Time of Day clock error (r151024)

usr/src/lib/libbe/common/libbe_priv.h, usr/src/tools/scripts/onu.1onbld, usr/src/tools/scripts/onu.sh.in
and fix list of BE-capable brands in libbe
=> Teach onu about linked-image zones

usr/src/lib/brand/lx/lx_init/lxinit.c
This change allows configuring an lx zone IP address and gateway via the allowed-address property:
```
net:
address not specified
allowed-address: 172.30.1.129/26
defrouter: 172.30.1.254
physical: deb0
```
versus:
```
net:
address not specified
allowed-address not specified
defrouter not specified
physical: deb0
property: (name=ips,value="172.30.1.129/26")
property: (name=primary,value="true")
property: (name=gateway,value="172.30.1.254")
```
Setting the addresses via allowed address has the extra benefit of configuring L3 protection on the interface so that zone cannot change to a different IP address:
```
GZ# dladm show-linkprop deb0
LINK         PROPERTY        PERM VALUE          DEFAULT        POSSIBLE
deb0         protection      rw   ip-nospoof     -- …
```
=> lx: Support zone "allowed-address" attribute

usr/src/lib/libc/port/mapfile-vers
Reviewed by: Peter Tribble <peter.tribble@gmail.com>
Reviewed by: Igor Kozhukhov <igor@dilos.org>
Reviewed by: Garrett D'Amore <garrett@damore.org>
=> 5709 Add binary compatibility with Solaris 10 update 10.

README.OmniOS, exception_lists/check_rtime, usr/contrib/freebsd/sys/queue.h, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/bhyve/mevent.c, usr/src/cmd/bhyve/mevent_test.c, usr/src/cmd/bhyve/test/Makefile, usr/src/cmd/bhyve/test/Makefile.com, usr/src/cmd/bhyve/test/Makefile.subdirs, usr/src/cmd/bhyve/test/Makefile.targ, usr/src/cmd/bhyve/test/scripts/Makefile, usr/src/cmd/bhyve/test/scripts/bhyvetest.ksh, usr/src/cmd/bhyve/test/tst/Makefile, usr/src/cmd/bhyve/test/tst/mevent/Makefile, usr/src/cmd/bhyve/test/tst/mevent/lists.delete.c, usr/src/cmd/bhyve/test/tst/mevent/mevent.c, usr/src/cmd/bhyve/test/tst/mevent/read.disable.c, usr/src/cmd/bhyve/test/tst/mevent/read.pause.c, usr/src/cmd/bhyve/test/tst/mevent/read.requeue.c, usr/src/cmd/bhyve/test/tst/mevent/testlib.c, usr/src/cmd/bhyve/test/tst/mevent/testlib.h, usr/src/cmd/bhyve/uart_emul.c, usr/src/pkg/manifests/system-bhyve-tests.mf, usr/src/uts/i86pc/io/viona/viona.c
Weekly upstream from `illumos-joyent`
None
```
SunOS mars 5.11 omnios-joyent_merge-2018032801-dafc32bda2 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Wed Mar 28 16:17:12 CEST 2018 ====
==== Nightly distributed build completed: Wed Mar 28 17:10:00 CEST 2018 ====
real    0:52:48
/usr/bin/uname
SunOS mars 5.11 omnios-master-fe6382e2a0 i86pc i386 i86pc
/build/illumos-omnios/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i …
```
=> Joyent merge/2018032801

usr/src/boot/sys/boot/common/dev_net.c, usr/src/man/man5/pxeboot.5
=> pxeboot fixes (r151026)

usr/src/boot/sys/boot/common/dev_net.c, usr/src/man/man5/pxeboot.5
Fixing three issues with pxeboot found during r151026 testing.
=> pxeboot fixes

README.OmniOS, usr/src/cmd/lofiadm/main.c
Backports to r151026 from https://github.com/omniosorg/illumos-omnios/pull/212
* SUNWcs
=> Upstream backport/2018051801

usr/src/cmd/mdb/i86pc/modules/unix/sec.c
=> ::sec - add missing malloc result check

usr/src/cmd/mdb/i86pc/modules/unix/sec.c, usr/src/man/man1/zlogin.1
(and fix OmniOS-specific zlogin man page typo - from https://github.com/omniosorg/illumos-omnios/issues/224)
=> ::sec - improve language and add HT note

README.OmniOS, usr/src/cmd/smbsrv/dtrace/smbd-all.d, usr/src/cmd/smbsrv/dtrace/smbd-authsvc.d, usr/src/cmd/smbsrv/dtrace/smbd-doorsvc.d, usr/src/cmd/smbsrv/dtrace/smbd-pipesvc.d, usr/src/lib/libmlrpc/common/ndr_process.c, usr/src/tools/quick/make-smbsrv
Fixes https://github.com/omniosorg/illumos-omnios/issues/254
Back-porting now and it will be included along with L1TF protection as and when that is back-ported.
=> 9769 SMB domain logon fails with I18N user name (r151026)

usr/src/uts/common/disp/thread.c
Approved by: Robert Mustacchi <rm@joyent.com>
=> L1TF: OS-7222 thread_create() should ensure ->t_cpu is set (r151026)

usr/src/uts/common/disp/thread.c
Approved by: Robert Mustacchi <rm@joyent.com>
=> L1TF: OS-7222 thread_create() should ensure ->t_cpu is set (r151022)

usr/src/cmd/bhyve/pci_virtio_block.c
=> virtio_block - Pass unhandled options through to blockif (r151028)

usr/src/cmd/bhyve/pci_virtio_block.c
In testing r151028, and in particular migration between KVM and bhyve, it was found to be necessary to pass sector size options through to the virtual disks. However, and earlier local change that we made to add support for `serial=` stops the attributes being passed through. This fixes it and has been tested on r151028. For ease of review, the diffs between upstream_joyent and our new version are at the bottom.
```
==== Nightly distributed build started:   Fri Oct  5 13:26:20 GMT 2018 ====
==== Nightly distributed build completed: Fri Oct  5 14:46:49 GMT 2018 ====
real    1:20:28
/usr/bin/uname
SunOS bloody 5.11 omnios-joyent_merge-2018100401-c6cc2b6b38 i86pc i386 i86pc
number of …
```
=> BHYVE: Allow generic block_if options for virtio disks

usr/src/lib/libzfs/common/libzfs_mount.c
See #285 for details. The fix was developed against r151028 - this is the PR for master.
=> Race in ZFS parallel mount

usr/src/cmd/svc/milestone/fs-local, usr/src/cmd/svc/milestone/local-fs.xml, usr/src/lib/libzfs/common/libzfs_mount.c
=> Add config/parallel to svc:/system/filesystem/local

usr/src/cmd/beadm/beadm.c, usr/src/cmd/boot/bootadm/bootadm.c, usr/src/cmd/boot/bootadm/bootadm_loader.c, usr/src/lib/libbe/common/be_activate.c, usr/src/lib/libbe/common/be_list.c, usr/src/lib/libbe/common/be_utils.c, usr/src/lib/libbe/common/libbe.h, usr/src/lib/libbe/common/libbe_priv.h, usr/src/lib/pylibbe/common/libbe_py.c, usr/src/uts/common/brand/lx/os/lx_ptrace.c
Backports from this week's upstream merges.
```
==== Nightly distributed build started:   Fri Oct 19 10:18:02 UTC 2018 ====
==== Nightly distributed build completed: Fri Oct 19 13:04:36 UTC 2018 ====
real    2:46:33
/usr/bin/uname
SunOS r151028 5.11 omnios-r151028-3811c51e4d i86pc i386 i86pc
/data/omnios-build/omniosorg/r151028/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc
/data/omnios-build/omniosorg/r151028/illumos/usr/src/tools/proto/root_i386-nd/opt/onbld/bin/i386/cw -_gcc …
```
=> Upstream merge backports/2018101901

usr/src/data/hwdata/pci.ids, usr/src/data/hwdata/usb.ids
Reviewed by: Marcel Telka <marcel@telka.sk>
Reviewed by: Dominik Hassler <hadfl@omniosce.org>
=> 9925 Update hwdata to 2018.10.25

usr/src/data/hwdata/pci.ids, usr/src/data/hwdata/usb.ids
Reviewed by: Marcel Telka <marcel@telka.sk>
Reviewed by: Dominik Hassler <hadfl@omniosce.org>
=> 9925 Update hwdata to 2018.10.25 (r151028)

usr/src/uts/common/io/sata/adapters/ahci/ahci.c
=> 7075 ahci: NULL pointer dereference in ahci_add_doneq() (r151028)

usr/src/lib/cfgadm_plugins/ib/common/cfga_ib.c, usr/src/lib/cfgadm_plugins/sata/common/cfga_sata.c, usr/src/lib/cfgadm_plugins/usb/common/cfga_usb.c
see https://github.com/omniosorg/illumos-omnios/pull/317
=> 9941 Noise from cfgadm plugins

usr/src/cmd/svc/common/manifest_hash.c
=> Honour PKG_INSTALL_ROOT when building hash filename (r151028)

usr/src/pkg/manifests/system-header.mf, usr/src/uts/i86pc/sys/Makefile
=> Ship sys/hma.h header (r151028)

usr/src/cmd/bhyve/fwctl.c
Reviewed by: John Levon <john.levon@joyent.com>
Reviewed by: Mike Gerdts <mike.gerdts@joyent.com>
Approved by: Mike Gerdts <mike.gerdts@joyent.com>
=> OS-7420 bhyve needs fix for FreeBSD-SA-18:14.bhyve (r151028)

usr/src/cmd/bhyve/fwctl.c
Reviewed by: John Levon <john.levon@joyent.com>
Reviewed by: Mike Gerdts <mike.gerdts@joyent.com>
Approved by: Mike Gerdts <mike.gerdts@joyent.com>
=> OS-7420 bhyve needs fix for FreeBSD-SA-18:14.bhyve (r151026)

usr/src/uts/common/brand/lx/syscall/lx_open.c
Fixes #331 
There is a slightly strange feature of Linux in that `openat("/path/to/symlink", O_NOFOLLOW|O_PATH)` returns a file descriptor that refers to the symlink itself, and that file descriptor can be subsequently used in fchownat(2), fstatat(2), linkat(2), and readlinkat(2) along with an empty path in order to have the call operate on the symlink itself.
OmniOS currently returns _ELOOP_ in response to such an _openat()_ call and newer systemd (specifically the `systemd_tmpfiles` service) considers this a problem and does not create temporary files and directories that are needed by other services such as _sshd_.
We don't have a way to emulate the file-descriptor for a symlink in illumos so the best we can do is return a descriptor to the target which has the FREAD and FWRITE flags …
=> lx: Partially emulate openat(..., O_NOFOLLOW|O_PATH) against symlink

usr/src/uts/common/fs/zfs/metaslab.c, usr/src/uts/common/fs/zfs/sys/metaslab_impl.h
=> OS-7151 ZFS loading and unloading metaslabs at audible frequency (r151028)

usr/src/boot/sys/boot/common/help.common, usr/src/boot/sys/boot/common/interp.c, usr/src/boot/sys/boot/forth/beadm.4th, usr/src/boot/sys/boot/forth/brand-omnios.4th, usr/src/boot/sys/boot/forth/check-password.4th, usr/src/boot/sys/boot/forth/logo-omnios.4th, usr/src/boot/sys/boot/forth/menu-commands.4th, usr/src/boot/sys/boot/forth/menu.4th, usr/src/boot/sys/boot/forth/menusets.4th, usr/src/boot/sys/boot/forth/screen.4th, usr/src/boot/sys/boot/forth/support.4th, usr/src/boot/sys/boot/forth/version.4th, usr/src/common/ficl/emu/loader_emu.c, usr/src/common/ficl/ficl.h, usr/src/common/ficl/tools.c
Sifting also supports vocabulary scope and search order.
=> Loader and brand improvements

usr/src/cmd/dladm/dladm.c, usr/src/man/man1m/dladm.1m
Partial side pull from:
OS-249 extend dladm subcommands to have better support for zones
commit fa9b9945bd
=> Show assigned zone in "dladm show-vnic" output

usr/src/cmd/zoneadm/zoneadm.c, usr/src/tools/scripts/onu.sh.in
Add pkgsrc to list of linked zones for onu
Always skip the GZ when considering zones for onu
=> Always report the GZ as the "ipkg" brand

usr/src/uts/common/io/dls/dls.c
Reviewed by: Andy Fiddaman <andy@omniosce.org>
Reviewed by: Dan McDonald <danmcd@joyent.com>
Reviewed by: Ryan Zezeski <rpz@joyent.com>
Approved by: Gordon Ross <gwr@nexenta.com>
=> 10543 dls_unbind() needs better checking (r151028)

usr/src/uts/common/io/dls/dls.c
Reviewed by: Andy Fiddaman <andy@omniosce.org>
Reviewed by: Dan McDonald <danmcd@joyent.com>
Reviewed by: Ryan Zezeski <rpz@joyent.com>
Approved by: Gordon Ross <gwr@nexenta.com>
=> 10543 dls_unbind() needs better checking (r151026)

usr/src/uts/common/io/dls/dls.c
Reviewed by: Andy Fiddaman <andy@omniosce.org>
Reviewed by: Dan McDonald <danmcd@joyent.com>
Reviewed by: Ryan Zezeski <rpz@joyent.com>
Approved by: Gordon Ross <gwr@nexenta.com>
=> 10543 dls_unbind() needs better checking (r151022)

usr/src/data/zoneinfo/africa, usr/src/data/zoneinfo/asia, usr/src/data/zoneinfo/backward, usr/src/data/zoneinfo/country.tab, usr/src/data/zoneinfo/etcetera, usr/src/data/zoneinfo/europe, usr/src/data/zoneinfo/northamerica, usr/src/pkg/manifests/system-data-zoneinfo.mf
```
==== Nightly distributed build started:   Tue Mar 26 16:26:21 UTC 2019 ====
==== Nightly distributed build completed: Tue Mar 26 17:15:23 UTC 2019 ====
real    0:49:02
/usr/bin/uname
SunOS bloody 5.11 omnios-master-0226821f7b i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151029/7.4.0-il-1) 7.4.0 …
```
=> Update tzdata to 2019a

usr/src/lib/brand/lx/zone/config.xml
=> Add state change hooks for lx zones (r151030)

usr/src/lib/brand/lx/zone/lx_boot.ksh, usr/src/lib/brand/lx/zone/lx_boot_zone_ubuntu.ksh, usr/src/uts/common/brand/lx/os/lx_syscall.c, usr/src/uts/common/brand/lx/sys/lx_socket.h, usr/src/uts/common/brand/lx/sys/lx_syscalls.h, usr/src/uts/common/brand/lx/syscall/lx_socket.c
=> Improve support for Ubuntu 18.04 as an lx guest (r151030)

usr/contrib/freebsd/x86/specialreg.h, usr/src/compat/freebsd/amd64/machine/specialreg.h, usr/src/uts/i86pc/io/vmm/x86.c
Approved by: Jerry Jelinek <jerry.jelinek@joyent.com>
=> OS-7801 bhyve should expose MD_CLEAR capability (r151030)

usr/contrib/freebsd/x86/specialreg.h, usr/src/compat/freebsd/amd64/machine/specialreg.h, usr/src/uts/i86pc/io/vmm/x86.c
Approved by: Jerry Jelinek <jerry.jelinek@joyent.com>
=> OS-7801 bhyve should expose MD_CLEAR capability (r151028)

usr/src/uts/intel/io/dktp/controller/ata/ata_common.c, usr/src/uts/intel/io/dktp/controller/ata/ata_dma.c, usr/src/uts/intel/io/hyperv/vmbus/hyperv.c
=> DLPX-63519 ATA reads timeout after Azure update (r151030)

usr/src/uts/common/brand/lx/os/lx_pid.c, usr/src/uts/common/brand/lx/procfs/lx_prsubr.c, usr/src/uts/common/disp/fss.c, usr/src/uts/common/disp/sysdc.c, usr/src/uts/common/disp/ts.c, usr/src/uts/common/fs/proc/prsubr.c, usr/src/uts/common/fs/ufs/ufs_directio.c, usr/src/uts/common/os/bio.c, usr/src/uts/common/os/condvar.c, usr/src/uts/common/os/pid.c, usr/src/uts/common/os/rwlock.c, usr/src/uts/common/sys/fss.h, usr/src/uts/common/sys/ia.h, usr/src/uts/common/sys/thread.h, usr/src/uts/common/sys/ts.h, usr/src/uts/common/vm/page_lock.c, usr/src/uts/i86pc/ml/offsets.in, usr/src/uts/intel/ia32/ml/lock_prim.s, usr/src/uts/intel/ia32/os/syscall.c, usr/src/uts/sfmmu/vm/hat_sfmmu.c, usr/src/uts/sparc/os/syscall.c, usr/src/uts/sparc/v9/ml/lock_prim.s, usr/src/uts/sun4/ml/offsets.in
```
==== Nightly distributed build started:   Tue May 28 13:52:11 UTC 2019 ====
==== Nightly distributed build completed: Tue May 28 14:42:20 UTC 2019 ====
real    0:50:08
/usr/bin/uname
SunOS r151030 5.11 omnios-r151030-632fca26eb i86pc i386 i86pc
cw version 4.0
gcc (OmniOS 151030/7.4.0-il-1) 7.4.0 …
```
=>  OS-7753 THREAD_KPRI_RELEASE does nothing of the sort (r151030)

usr/src/man/man1/pfexec.1
fixes: https://github.com/omniosorg/illumos-omnios/issues/477
=> pfexec.1 [fix mismerge]

usr/src/uts/intel/io/hyperv/vmbus/vmbus_chan.c
If we're running on a single-CPU virtual machine, we need to occasionally get off the CPU to allow initialisation to complete.
Fixes #482 
See also https://github.com/freebsd/freebsd/commit/f980a6124c06e08bf1686e5aaec46c6dd39960f4
=> HYPERV: Do not busy-wait during channel open

usr/src/tools/scripts/bldenv.sh
At present, if you enter a `bldenv` environment after HEAD has moved, an incremental build may fail with an error like:
```
ctfmerge: failed to merge types: Merged labels conflict
```
This is because the CTF data is labelled with the contents of the `$VERSION` environment variable, which is based on the git HEAD commit hash.
To allow for incremental builds, this PR changes `bldenv` to reset VERSION to match the previous build if a built kernel is found in the tree.
=> Detect built trees and override VERSION so that incremental builds work

README.OmniOS, usr/src/uts/common/inet/ip_ndp.h
see: https://github.com/omniosorg/illumos-omnios/pull/512
=> Backports r30

usr/src/man/man1/Makefile, usr/src/man/man1/zonestat.1, usr/src/man/man1m/Makefile, usr/src/man/man1m/zonestatd.1m, usr/src/pkg/manifests/system-zones.mf
commit ae4a2ff0df
Conflicts:
usr/src/man/man1/Makefile
usr/src/man/man1m/Makefile
usr/src/pkg/manifests/system-zones.mf
=> 3334 zonestat missing man page

usr/src/boot/sys/boot/forth/support.4th
This fixes a problem where boot can hang under Hyper-V and KVM when switching resolution just before boot.
=> Fix resolution switch before boot

usr/src/cmd/boot/bootadm/bootadm.c
A small issue found during r151032.rc1 testing:
```
-rw-r--r--   1 root     root          67 Sep 19 12:55 /etc/versions/build
updating /platform/i86pc/amd64/boot_archive (CPIO)
-rw-r--r--   1 root     root         251 Sep 19 12:55 /etc/versions/build
```
```
updating /platform/i86pc/amd64/boot_archive (CPIO)
-rw-r--r--   1 root     sys           67 Sep 19 12:55 /etc/versions/build
```
=> Bootadm should preserve ownership/permissions on self-assembly files

usr/src/lib/libdtrace/common/nfs.d, usr/src/uts/common/fs/nfs/nfs3_srv.c, usr/src/uts/common/fs/nfs/nfs4_srv.c, usr/src/uts/common/fs/nfs/nfs4_srv_attr.c, usr/src/uts/common/fs/nfs/nfs4_srv_ns.c, usr/src/uts/common/fs/nfs/nfs_auth.c, usr/src/uts/common/fs/nfs/nfs_export.c, usr/src/uts/common/fs/nfs/nfs_server.c, usr/src/uts/common/fs/nfs/nfs_srv.c, usr/src/uts/common/nfs/export.h, usr/src/uts/common/sys/zone.h
Hmmm... I thought I was tracking upstream better.  Be careful with this wad.  I can, instead, try something different if you wish...
=> Omnios nfs zone

usr/src/uts/common/inet/tcp/tcp.c
Reviewed by: Garrett D'Amore <gdamore@racktopsystems.com>
Reviewed by: Dan McDonald <danmcd@joyent.com>
=> 11849 listen of IPv6 address fails with EAFNOSUPPORT

README.OmniOS, usr/src/lib/libzfs/common/libzfs_sendrecv.c, usr/src/test/zfs-tests/tests/functional/rsend/send_encrypted_props.ksh
Backport from master branch #591
=> 11872 Fix incremental recursive encrypted receive (r151032)

usr/src/test/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_child.ksh, usr/src/uts/common/fs/zfs/dsl_crypt.c
…iggers VERIFY
Portions contributed by: Jason King <jason.brian.king@gmail.com>
Reviewed by: Jason King <jason.brian.king@gmail.com>
Reviewed by: Brian Behlendorf <behlendorf1@llnl.gov>
Reviewed by: Igor Kozhukhov <igor@dilos.org>
Reviewed by: Andrew Stormont <astormont@racktopsystems.com>
=> 11880 changing encryption key on dataset with unencrypted children tr… (r151032)

usr/src/data/zoneinfo/zone_sun.tab
Reviewed by: Andy Fiddaman <andy@omniosce.org>
=> 11934 One more typo in zone_sun.tab (r151032)

README.OmniOS, usr/src/uts/common/io/usb/scsa2usb/scsa2usb.c, usr/src/uts/common/sys/usb/scsa2usb/scsa2usb.h
=> 11952 large USB hard disks experience I/O failures (r151030)

usr/src/uts/common/fs/nfs/nfs4_db.c, usr/src/uts/common/nfs/export.h
=> nfs-zone update

README.OmniOS, usr/src/cmd/boot/installboot/i386/installboot.c, usr/src/uts/common/os/cpu_uarray.c
see: https://github.com/omniosorg/illumos-omnios/pull/607
=> backports to r32

usr/src/Makefile.master, usr/src/tools/env/omnios-illumos-gate.sh
see: https://github.com/omniosorg/omnios-build/pull/1699
=> Update .env files following move to 64-bit-only Perl

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_link.c
Just one commit with a fix for a credential leak, no build done.
=> Joyent merge/2020011001

usr/src/lib/libbe/common/be_create.c, usr/src/lib/libbe/common/be_rename.c, usr/src/lib/libbe/common/be_utils.c, usr/src/lib/libbe/common/libbe_priv.h
=> 12141 libbe cannot handle vfstab updates in NGZ (r151032)

usr/src/lib/libbe/common/be_create.c, usr/src/lib/libbe/common/be_rename.c, usr/src/lib/libbe/common/be_utils.c, usr/src/lib/libbe/common/libbe_priv.h
Reviewed by: C Fraire <cfraire@me.com>
=> 12141 libbe cannot handle vfstab updates in NGZ (r151030)

usr/src/cmd/ps/ps.c, usr/src/cmd/ps/ucbps.c, usr/src/man/man1/ps.1
=> UCB ps is truncating command arguments

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_futex.c
…X_PRIVATE_FLAG set causes panic (#272)
=> OS-8141 lx futex called with NULL  timeout and FUTEX_WAIT_BITSET|FUTE… (r151030)

README.OmniOS, usr/src/uts/common/brand/lx/syscall/lx_futex.c
…X_PRIVATE_FLAG set causes panic (#272)
=> OS-8141 lx futex called with NULL  timeout and FUTEX_WAIT_BITSET|FUTE… (r151032)

usr/src/data/zoneinfo/README.illumos, usr/src/data/zoneinfo/zone_sun.tab, usr/src/data/zoneinfo/zonelint
Portions-contributed by: pbdigital-dot-org <brown_philip@yahoo.com>
=> 12485 Typos in zone_sun.tab

usr/src/data/zoneinfo/README.illumos, usr/src/data/zoneinfo/zone_sun.tab, usr/src/data/zoneinfo/zonelint
Portions-contributed by: pbdigital-dot-org <brown_philip@yahoo.com>
=> 12485 Typos in zone_sun.tab (r151034)

usr/src/man/man1m/nfsd.1m, usr/src/man/man4/nfs.4, usr/src/man/man5/zones.5, usr/src/man/man7fs/sharefs.7fs
Reviewed by: Peter Tribble <peter.tribble@gmail.com>
Reviewed by: Gordon Ross <gordon.w.ross@gmail.com>
Approved by: Joshua M. Clulow <josh@sysmgr.org>
=> 12278 nfs-zone needs man page changes (r151034)

usr/src/cmd/w/w.c, usr/src/cmd/whodo/whodo.c
Reviewed by: Peter Tribble <peter.tribble@gmail.com>
Reviewed by: Yuri Pankov <ypankov@fastmail.com>
=> 12523 Buffer overflow in w and whodo (r151034)

README.OmniOS, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/sys/lx_brand.h
This lx fix has already been applied to r151034 but needs backporting to other supported releases.
=> Joyent merge/2020050101

README.OmniOS, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/sys/lx_brand.h
=> LX: OS-8165 dockerinit should be able to start lx_lockd (#297) (r151032)

README.OmniOS, usr/src/uts/common/brand/lx/os/lx_brand.c, usr/src/uts/common/brand/lx/sys/lx_brand.h
=> LX: OS-8165 dockerinit should be able to start lx_lockd (#297) (r151030)

usr/src/tools/scripts/onu.sh.in
=> ONU to illumos-gate should work with installed zones

usr/src/uts/common/fs/zfs/zfs_vfsops.c
This fixes the occasional problem that is reported with `pkg update` being unable to clone the BE, like this:
```
Packages to update:         4
Estimated space available:  38.05 GB
Estimated space to be consumed: 111.01 MB
Create boot environment:       Yes
Activate boot environment:       Yes
Create backup boot environment:        No
Rebuild boot archive:        No
DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                4/4       112/112    22.0/22.0      --
pkg: Unable to clone the current boot environment.
Exit 1
```
For a full write-up and analysis, see the illumos issue - https://www.illumos.org/issues/12783
=> 12783 async unlinked drain races with ZFS unmount (r151034)

usr/src/uts/common/brand/lx/io/lx_netlink.c
Fixes #794  (see ticket for analysis and further details)
=> OS-8181 exposed fault in lx netlink bind/sendto

usr/src/uts/common/fs/zfs/dnode_sync.c
Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed by: Brian Behlendorf <behlendorf1@llnl.gov>
Reviewed by: Igor Kozhukhov <igor@dilos.org>
=> 13034 dnode_sync is careless with range tree (r151030)

usr/src/cmd/ndmpd/ndmp/ndmpd_data.c
According to the RFC the ndmp_data_get_env call must return the
environment variables after both a backup and restore session. The old
implementation would only allow it after a backup.
This is what the NDMP RFC says:
This request is used by the DMA to obtain the backup environment
variable set associated with the current data operation. The
NDMP_DATA_GET_ENV request is typically issued following a successful
backup operation but MAY be issued during or after a recovery
operation as well. This request is only valid when the Data Server is
in the ACTIVE or HALTED states.
=> Fix ndmp_data_get_env calls.

usr/src/data/hwdata/pci.ids, usr/src/data/hwdata/usb.ids
commit 3626423cd8
Conflicts:
usr/src/pkg/manifests/system-data-hardware-registry.mf
=> 13167 Update hwdata to 2020.9.15 (r151030)

usr/src/cmd/make/bin/make.rules.file
I think it's about time we changed these.. and we have a whole bloody cycle to see if there is any fallout
=> Update make defaults for OmniOS

usr/src/cmd/ndmpd/tlm/tlm_backup_reader.c
This syncs the NDMP support till commit with hash
600a56024bf3e2650394f6b81b822368dd00a74f from Sat Apr 18 00:16:19 2020 -0700
It includes the following fix:
- NEX-20439 NDMP: backups to tape or DAS extremely slow
=> Sync NDMP support with illumos-nexenta.

usr/src/boot/Makefile.version, usr/src/boot/sys/boot/common/gfx_fb.c, usr/src/boot/sys/boot/common/multiboot2.c, usr/src/boot/sys/boot/common/tem.c, usr/src/boot/sys/boot/i386/libi386/vbe.c, usr/src/boot/sys/boot/i386/libi386/vbe.h, usr/src/boot/sys/boot/i386/libi386/vidconsole.c, usr/src/common/font/font.c, usr/src/lib/libc/amd64/Makefile, usr/src/lib/libc/amd64/unwind/unwind.c, usr/src/lib/libc/amd64/unwind/unwind_wrap.s, usr/src/pkg/manifests/developer-dtrace.mf, usr/src/tools/env/omnios-illumos-gate.sh, usr/src/tools/scripts/wsdiff.1onbld, usr/src/tools/scripts/wsdiff.py, usr/src/uts/common/c2/audit_io.c, usr/src/uts/common/fs/zfs/dnode.c, usr/src/uts/common/fs/zfs/sys/dmu_impl.h, usr/src/uts/common/fs/zfs/sys/dnode.h, usr/src/uts/common/fs/zfs/zfs_vnops.c, usr/src/uts/common/io/mlxcx/mlxcx_cmd.c, usr/src/uts/common/io/mlxcx/mlxcx_reg.h, usr/src/uts/common/syscall/auditsys.c
Weekly upstream for upstream_merge/2020102901
to r151036:
* 13254 SEGV due to misaligned stack in Unwind_RaiseException
```
OmniOS r151035  omnios-upstream_merge-2020102901-7bdb979096     October 2020
illumos development build: 2020-Oct-29 [illumos]
omni%                                                                           bloody% uname -a
SunOS bloody 5.11 omnios-upstream_merge-2020102901-7bdb979096 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Oct 29 12:27:34 UTC 2020 ====
==== Nightly distributed build completed: Thu Oct 29 13:44:05 UTC 2020 ====
real    1:16:30
/usr/bin/uname
SunOS bloody 5.11 omnios-master-a3ded613ea i86pc i386 i86pc …
```
=> Upstream merge upstream_merge/2020102901

usr/src/test/test-runner/cmd/run, usr/src/uts/common/fs/zfs/dmu_objset.c
12397 12254 broke the zfs test suite for older python versions
Portions contributed by: Tom Caputi <tcaputi@datto.com>
Portions contributed by: Nasf-Fan <fan.yong@intel.com>
Portions contributed by: Gvozden Neskovic <neskovic@gmail.com>
Change-ID: If502dbed8229d18fc2319348f673aa78747b9eef
=> 13358 dmu_objset_upgrade_stop() needs to wait (r151034)

usr/src/test/test-runner/cmd/run, usr/src/uts/common/fs/zfs/dmu_objset.c
12397 12254 broke the zfs test suite for older python versions
Portions contributed by: Tom Caputi <tcaputi@datto.com>
Portions contributed by: Nasf-Fan <fan.yong@intel.com>
Portions contributed by: Gvozden Neskovic <neskovic@gmail.com>
Change-ID: If502dbed8229d18fc2319348f673aa78747b9eef
=> 13358 dmu_objset_upgrade_stop() needs to wait (r151036)

usr/src/cmd/zfs/zfs_iter.c
Reviewed by: Andy Fiddaman <andy@omnios.org>
=> 13388 ZFS list bookmark not working on zvols (r151030)

usr/src/cmd/zfs/zfs_iter.c
Reviewed by: Andy Fiddaman <andy@omnios.org>
=> 13388 ZFS list bookmark not working on zvols (r151034)

usr/src/cmd/zfs/zfs_iter.c
Reviewed by: Andy Fiddaman <andy@omnios.org>
=> 13388 ZFS list bookmark not working on zvols (r151036)

usr/src/cmd/bhyve/Makefile, usr/src/tools/smatch/Makefile
Reviewed by: Rich Lowe <richlowe@richlowe.net>
=> 13443 gate build missing some NATIVE_LIBS (r151036)

usr/src/cmd/bhyve/Makefile, usr/src/tools/smatch/Makefile
Reviewed by: Rich Lowe <richlowe@richlowe.net>
=> 13443 gate build missing some NATIVE_LIBS (r151034)

usr/src/boot/sys/boot/i386/isoboot/isoboot.c, usr/src/cmd/beadm/beadm.c, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/rfb.c, usr/src/cmd/sgs/libld/common/args.c, usr/src/cmd/sgs/libld/common/ldmain.c, usr/src/cmd/sgs/libld/common/libld.msg, usr/src/cmd/sgs/liblddbg/common/args.c, usr/src/cmd/sgs/liblddbg/common/liblddbg.msg, usr/src/cmd/sgs/liblddbg/common/mapfile-vers, usr/src/lib/libbe/common/be_create.c, usr/src/lib/libbe/common/be_rename.c, usr/src/man/man1m/beadm.1m, usr/src/uts/common/fs/ufs/ufs_inode.c, usr/src/uts/common/sys/contract/process_impl.h, usr/src/uts/common/sys/fs/ufs_inode.h, usr/src/uts/i86pc/os/startup.c, usr/src/uts/i86pc/sys/cpupm_throttle.h, usr/src/uts/i86pc/sys/machsystm.h
Weekly upstream for upstream_merge/2021012101
None
```
OmniOS r151037  omnios-upstream_merge-2021012101-fcd9f99f35     January 2021
illumos development build: 2021-Jan-21 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2021012101-fcd9f99f35 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jan 21 14:24:37 UTC 2021 ====
==== Nightly distributed build completed: Thu Jan 21 15:41:02 UTC 2021 ====
real    1:16:24
/usr/bin/uname
SunOS bloody 5.11 omnios-ooce-ksh-9405ebbd49 i86pc i386 i86pc
cw version 5.0
This is …
```
=> Upstream merge upstream_merge/2021012101

usr/src/uts/common/os/main.c, usr/src/uts/common/os/mem_config.c, usr/src/uts/common/os/vm_pageout.c, usr/src/uts/common/sys/vm.h
13107 pageout should use hrtime instead of lbolt
=> 13097 improve VM tunables for modern systems

usr/src/uts/intel/io/hyperv/storvsc/hv_storvsc_drv_illumos.c
=> BSR-8013 Azure - rebooting after adding disks caused panic

usr/src/cmd/zoneadm/zfs.c
Fixes https://github.com/omniosorg/zadm/issues/39
=> 2766 zoneadm install fails with root of zpool not mounted

README.OmniOS, usr/src/uts/common/fs/zfs/zfs_vnops.c
https://illumos.topicbox.com/groups/omnios-discuss/Tc9314eeb31d3508b-M58c2970a3aba5b99d31280e1/pulling-13118-into-r151036
=> 13118 Very slow reaping, possible deadlock in zfs_delmap (r151036)

usr/src/man/man1/ksh93.1
See the HTML rendered version at https://man.omnios.org/ksh93.1
and the old version at https://man.omnios.org/ksh92.1
I fixed a lot of errors on the way through and quite a lot of grammar too, but there's every chance I introduced one or two new ones too given the scale of it.
=> Convert ksh93.1 to mandoc

usr/src/man/man1/ksh93.1
A few small ksh93.1 updates from the ongoing upstream review.
=> Bring in ksh93.1 updates from gate review

README.OmniOS, usr/src/uts/common/fs/smbsrv/smb_tree.c
This has been tested via https://hf.omnios.org/r36/smb-13643.p5p
=> 13643 smb share of lofs mount fails

usr/src/uts/i86pc/io/vmm/vmm.c
Reviewed by: Yuri Pankov <yuripv@yuripv.dev>
Reviewed by: Hans Rosenfeld <rosenfeld@grumpf.hope-2000.org>
Approved by: Robert Mustacchi <rm@fingolfin.org>
=> 13645 bhyve queues wrong SIPI (r151038)

usr/src/cmd/cmd-inet/usr.lib/in.cdpd/yuka.c, usr/src/man/man1m/cdpadm.1m, usr/src/man/man1m/in.cdpd.1m
Take the opportunity to clean up the man pages a bit too.
```
reaper# ppriv -S `pgrep in.cdpd`
21238:  /usr/lib/inet/in.cdpd -R
flags = PRIV_AWARE
E: file_read,file_write
I: basic,!file_link_any,net_rawaccess,!proc_info,!proc_session
P: file_read,file_write
L: file_read,file_write
```
=> in.cdpd should drop privileges

usr/src/cmd/bhyve/privileges.c, usr/src/lib/libm/Makefile.libm.com, usr/src/lib/libm/common/C/__rem_pio2m.c
Weekly upstream for upstream_merge/2021052501
None
```
OmniOS r151039  omnios-upstream_merge-2021052501-4e5df92e11     May 2021
illumos development build: 2021-May-25 [illumos]
bloody%
SunOS bloody 5.11 omnios-upstream_merge-2021052501-4e5df92e11 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Tue May 25 13:15:33 UTC 2021 ====
==== Nightly distributed build completed: Tue May 25 14:31:03 UTC 2021 ====
real    1:15:29
/usr/bin/uname
SunOS bloody 5.11 omnios-master-bbb9e162e0 i86pc i386 i86pc
cw version 5.0
gcc (OmniOS 151039/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free Software …
```
=> Upstream merge upstream_merge/2021052501

usr/src/cmd/bhyve/pci_nvme.c
```
reaper# zadm show r36 extra
{
"extra" : "-s 7,nvme,ram=1024"
}
reaper# /usr/lib/brand/bhyve/boot -t r36
pci.0.7.0.device=nvme
pci.0.7.0.path=ram=1024
bhyve-r36: Could not open backing file: ram=1024: No such file or directory
nvme: Could not open backing file: No such file or directory
device emulation initialization error: No such file or directory
```
=> bhyve: nvme ramdisk path does not work (r151038)

README.OmniOS, usr/src/cmd/smbsrv/smbd/smbd_join.c
=> 14021 stack overflow in smbd:smbd_dc_check (r151038)

usr/src/uts/common/exec/java/java.c, usr/src/uts/common/exec/shbin/shbin.c
See also https://github.com/omniosorg/omnios-build/pull/2561
=> Fix javaexec module's ability to run executable jars

usr/src/cmd/diskinfo/diskinfo.c
Server with 18 disks:
$ time diskinfo
TYPE    DISK                    VID      PID              SIZE          RMV SSD
SCSI    c0t5000CCA04D086780d0   HGST     HUSMR1625ASS  232.89 GiB   no  yes
....
real    0m3.952s
user    0m0.205s
sys     0m0.436s
$ time ./diskinfo.new
TYPE    DISK                    VID      PID              SIZE          RMV SSD
SCSI    c0t5000CCA04D086780d0   HGST     HUSMR1625ASS  232.89 GiB   no  yes
...
real    0m0.107s
user    0m0.016s
sys     0m0.032s
=> diskinfo: get rid of topo calls if there are no -c or -P options

README.OmniOS, usr/src/Makefile.master, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/svc/seed/Makefile, usr/src/man/man4/bhyve_config.4, usr/src/pkg/manifests/SUNWcs.p5m, usr/src/tools/cw/cw.c, usr/src/tools/scripts/wsdiff.py, usr/src/uts/common/brand/lx/cgroups/cgrps_node.c, usr/src/uts/common/brand/lx/devfs/lxd_node.c, usr/src/uts/common/sys/mac.h, usr/src/uts/i86pc/io/vmm/intel/vmx.c, usr/src/uts/i86pc/io/vmm/intel/vmx.h, usr/src/uts/intel/genunix/Makefile
```
==== Nightly distributed build started:   Mon Nov 29 20:57:13 UTC 2021 ====
==== Nightly distributed build completed: Mon Nov 29 22:16:56 UTC 2021 ====
real    1:19:43
/usr/bin/uname
SunOS bloody 5.11 omnios-master-72433da6283 i86pc i386 i86pc
cw version 5.1
gcc (OmniOS 151041/7.5.0-il-1) 7.5.0
shadow: /opt/gcc-10/bin/gcc
This is free software; …
```
=> Upstream merge

.gitignore, usr/src/cmd/cmd-inet/lib/ipmgmtd/ipmgmt_persist.c, usr/src/cmd/sgs/ldd/common/ldd.c, usr/src/cmd/sgs/ldd/common/ldd.msg, usr/src/cmd/sgs/tools/SUNWonld-README, usr/src/test/elf-tests/tests/relocs/i386/got32x/got32x.sh, usr/src/uts/common/io/iprb/iprb.c, usr/src/uts/common/io/mac/mac_datapath_setup.c, usr/src/uts/common/io/mac/mac_sched.c, usr/src/uts/common/os/grow.c
Weekly upstream for upstream_merge/2021121301
None
```
OmniOS r151041  omnios-upstream_merge-2021121301-ecbd5430966    December 2021
illumos development build: 2021-Dec-13 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2021121301-ecbd5430966 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Mon Dec 13 11:30:22 UTC 2021 ====
==== Nightly distributed build completed: Mon Dec 13 12:50:46 UTC 2021 ====
real    1:20:24
/usr/bin/uname
SunOS bloody 5.11 omnios-master-5838effec5 i86pc i386 i86pc
cw version 5.1
gcc (OmniOS 151041/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free Software …
```
=> Upstream merge upstream_merge/2021121301

exception_lists/copyright, exception_lists/cstyle, exception_lists/hdrchk, exception_lists/wscheck, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/bhyvegc.c, usr/src/cmd/bhyve/bhyvegc.h, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/bhyve/pci_fbuf.c, usr/src/cmd/bhyve/rfb.c, usr/src/cmd/bhyve/rfb.h, usr/src/cmd/bhyve/rfb_impl.h, usr/src/lib/libidspace/common/libidspace.h, usr/src/lib/libidspace/common/mapfile-vers, usr/src/lib/libumem/common/umem_update_thread.c, usr/src/man/man4/bhyve_config.4
14495 bhyve VNC server should support alternate pixel formats
14494 bhyve VNC server could support multiple connections
=> bhyve VNC server refactor

usr/src/cmd/bhyve/bhyvegc.c, usr/src/cmd/bhyve/mevent.c, usr/src/cmd/bhyve/rfb.c, usr/src/cmd/bhyve/test/tests/mevent/vnode_file.c, usr/src/compat/bhyve/pthread.h, usr/src/head/pthread.h, usr/src/lib/libc/port/mapfile-vers, usr/src/lib/libc/port/threads/synch.c, usr/src/man/man3c/pthread_mutex_init.3c, usr/src/man/man3head/pthread.h.3head, usr/src/uts/common/os/exit.c, usr/src/uts/i86pc/io/vmm/vmm_instruction_emul.c
## onu
```
OmniOS r151041  omnios-bhyve-02310f54d5 February 2022
illumos development build: 2022-Feb-20 [illumos]
bloody%
SunOS bloody 5.11 omnios-bhyve-02310f54d5 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sun Feb 20 16:38:25 UTC 2022 ====
==== Nightly distributed build completed: Sun Feb 20 17:58:32 UTC 2022 ====
real    1:20:06
/usr/bin/uname
SunOS bloody 5.11 omnios-master-51544087da i86pc i386 i86pc
cw version 6.1
This is free software; see the source for copying conditions. …
```
=> bhyve updates

usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/diff/Makefile, usr/src/cmd/diff/diff.c, usr/src/cmd/diff/diff.h, usr/src/cmd/nvmeadm/nvmeadm.c, usr/src/cmd/nvmeadm/nvmeadm.h, usr/src/cmd/nvmeadm/nvmeadm_dev.c, usr/src/cmd/syseventd/modules/zfs_mod/Makefile, usr/src/man/man1/diff.1, usr/src/man/man1m/bhyve.1m, usr/src/man/man1m/nvmeadm.1m, usr/src/man/man4/bhyve_config.4, usr/src/pkg/manifests/system-bhyve-tests.p5m, usr/src/test/bhyve-tests/runfiles/default.run, usr/src/test/bhyve-tests/tests/vmm/Makefile, usr/src/test/bhyve-tests/tests/vmm/mem_devmem.c, usr/src/uts/common/io/nvme/nvme.c, usr/src/uts/common/os/policy.c, usr/src/uts/common/sys/nvme.h, usr/src/uts/i86pc/io/vmm/vmm_sol_dev.c
* none
```
OmniOS r151041  omnios-upstream_merge-2022030401-6825afae7c     March 2022
illumos development build: 2022-Mar-04 [illumos-omnios]
SunOS mars 5.11 omnios-upstream_merge-2022030401-6825afae7c i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Mar  4 21:04:18 CET 2022 ====
==== Nightly distributed build completed: Fri Mar  4 22:29:22 CET 2022 ====
real    1:25:03
/usr/bin/uname
SunOS mars 5.11 omnios-master-7fdae7f347b i86pc i386 i86pc
cw version 6.1
This is …
```
=> Upstream merge/2022030401

exception_lists/copyright, exception_lists/cstyle, exception_lists/hdrchk, exception_lists/wscheck, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/bhyvegc.c, usr/src/cmd/bhyve/bhyvegc.h, usr/src/cmd/bhyve/bhyverun.c, usr/src/cmd/bhyve/console.c, usr/src/cmd/bhyve/console.h, usr/src/cmd/bhyve/pci_fbuf.c, usr/src/cmd/bhyve/ps2kbd.c, usr/src/cmd/bhyve/rfb.c, usr/src/cmd/bhyve/rfb.h, usr/src/cmd/bhyve/rfb_impl.h, usr/src/lib/libidspace/common/libidspace.h, usr/src/lib/libidspace/common/mapfile-vers, usr/src/lib/libumem/common/umem_update_thread.c, usr/src/man/man4/bhyve_config.4
```
==== Nightly distributed build started:   Wed Mar  9 10:54:00 UTC 2022 ====
==== Nightly distributed build completed: Wed Mar  9 12:09:17 UTC 2022 ====
real    1:15:17
/usr/bin/uname
SunOS r151038 5.11 omnios-r151038-d88e3ac728 i86pc i386 i86pc
cw version 5.0 …
```
=> Improve bhyve VNC server (r151038)

README.OmniOS, usr/src/cmd/bhyve/Makefile, usr/src/cmd/bhyve/mevent.c, usr/src/cmd/bhyve/test/Makefile.com, usr/src/cmd/fwflash/Makefile.com, usr/src/cmd/fwflash/plugins/transport/common/ufm.c, usr/src/man/man3c/pthread_mutex_init.3c, usr/src/man/man3head/pthread.h.3head, usr/src/pkg/manifests/system-test-utiltest.p5m, usr/src/test/util-tests/runfiles/default.run, usr/src/test/util-tests/tests/dladm/show-overlay-exit.ksh, usr/src/tools/scripts/git-pbchk.1onbld, usr/src/tools/scripts/git-pbchk.py, usr/src/uts/common/io/cxgbe/common/common.h, usr/src/uts/common/io/cxgbe/common/t4_hw.c, usr/src/uts/common/io/cxgbe/t4nex/adapter.h, usr/src/uts/common/io/cxgbe/t4nex/t4_nexus.c, usr/src/uts/common/io/cxgbe/t4nex/t4_sge.c
Weekly upstream for upstream_merge/2022031701
None
```
OmniOS r151041  omnios-upstream_merge-2022031701-873233cb7e     March 2022
illumos development build: 2022-Mar-17 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2022031701-873233cb7e i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Mar 17 23:52:31 UTC 2022 ====
==== Nightly distributed build completed: Fri Mar 18 01:30:59 UTC 2022 ====
real    1:38:27
/usr/bin/uname
SunOS bloody 5.11 omnios-master-57a305f45c i86pc i386 i86pc
cw version 6.1
Copyright (C) 2020 Free Software …
```
=> Upstream merge upstream_merge/2022031701

usr/src/cmd/dladm/dladm.c, usr/src/cmd/svc/milestone/net-nwam, usr/src/cmd/svc/milestone/net-physical, usr/src/cmd/varpd/varpd.xml, usr/src/data/zoneinfo/africa, usr/src/data/zoneinfo/asia, usr/src/data/zoneinfo/europe, usr/src/data/zoneinfo/southamerica, usr/src/lib/libdladm/common/libdladm.c, usr/src/lib/libdladm/common/libdladm.h, usr/src/lib/libdladm/common/libdladm_impl.h, usr/src/lib/libdladm/common/libdloverlay.c, usr/src/lib/libdladm/common/libdloverlay.h, usr/src/man/man8/dladm.8, usr/src/pkg/manifests/system-data-zoneinfo.p5m, usr/src/uts/common/sys/overlay_common.h
Weekly upstream for upstream_merge/2022032101
```
==== Nightly distributed build started:   Mon Mar 21 19:07:43 UTC 2022 ====
==== Nightly distributed build completed: Mon Mar 21 20:25:16 UTC 2022 ====
real    1:17:32
/usr/bin/uname
SunOS bloody 5.11 omnios-master-acc06f3103 i86pc i386 i86pc
cw version 6.1
gcc (OmniOS 151041/7.5.0-il-1) 7.5.0
Copyright (C) 2017 Free …
```
=> Upstream merge upstream_merge/2022032101

usr/src/pkg/manifests/SUNWcs.p5m
Fixes https://github.com/omniosorg/illumos-omnios/issues/1137
=> duplicate entry in SUNWcs manifest

usr/src/lib/brand/lx/lx_vdso/tools/vdso_tool.c
=> LX: lx_vdso.so PT_DYNAMIC section should not be writeable 

usr/src/cmd/cmd-inet/usr.lib/in.mpathd/net-ipmp
Issue found by @mvwieringen during early r151042 testing.
=> 14617 svc:/network/ipmp maintenance in shared IP zone (r151042)

README.OmniOS, usr/src/lib/brand/lx/lx_vdso/tools/vdso_tool.c
This fixes lx compatibility with glibc >= 2.35
=> LX: lx_vdso.so PT_DYNAMIC section should not be writeable (r151038)

usr/src/cmd/sgs/common/alist.c, usr/src/cmd/sgs/common/string_table.c, usr/src/cmd/sgs/include/sgs.h, usr/src/cmd/sgs/ld/Makefile.com, usr/src/cmd/sgs/libld/Makefile.com, usr/src/cmd/sgs/libld/common/_libld.h, usr/src/cmd/sgs/libld/common/files.c, usr/src/cmd/sgs/libld/common/globals.c, usr/src/cmd/sgs/libld/common/groups.c, usr/src/cmd/sgs/libld/common/ldmain.c, usr/src/cmd/sgs/libld/common/libld.msg, usr/src/cmd/sgs/libld/common/libs.c, usr/src/cmd/sgs/libld/common/machsym.sparc.c, usr/src/cmd/sgs/libld/common/map.c, usr/src/cmd/sgs/libld/common/map_core.c, usr/src/cmd/sgs/libld/common/map_support.c, usr/src/cmd/sgs/libld/common/outfile.c, usr/src/cmd/sgs/libld/common/place.c, usr/src/cmd/sgs/libld/common/sections.c, usr/src/cmd/sgs/libld/common/sunwmove.c, usr/src/cmd/sgs/libld/common/syms.c, usr/src/cmd/sgs/libld/common/unwind.c, usr/src/cmd/sgs/libld/common/util.c, usr/src/cmd/sgs/libld/common/version.c, usr/src/cmd/sgs/tools/SUNWonld-README, usr/src/tools/sgs/ld/Makefile, usr/src/uts/common/io/blkdev/blkdev.c
* none
```
OmniOS r151041  omnios-upstream_merge-2022042301-077dd5595b     April 2022
illumos development build: 2022-Apr-23 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2022042301-077dd5595b i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sat Apr 23 09:24:09 UTC 2022 ====
==== Nightly distributed build completed: Sat Apr 23 10:05:45 UTC 2022 ====
real    0:41:36
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-4f51ac56af i86pc i386 i86pc
number of concurrent jobs = 32
cw version 6.1 …
```
=> Upstream merge/2022042301

usr/src/uts/common/brand/lx/syscall/lx_futex.c
Fixes https://github.com/omniosorg/illumos-omnios/issues/1265
=> LX: FUTEX_WAIT_BITSET should support timeout being NULL

usr/src/cmd/mdb/intel/mdb/mdb_x86util.c, usr/src/uts/i86pc/sys/mach_mmu.h, usr/src/uts/i86pc/vm/hat_i86.c, usr/src/uts/intel/sys/controlregs.h
Reviewed by: Andy Fiddaman <andy@omnios.org>
=> 14041 Dell R650 Xeon Gold 5318Y not booting

usr/src/cmd/boot/bootadm/bootadm_loader.c, usr/src/lib/libc/port/threads/sigaction.c, usr/src/lib/libdladm/Makefile.com, usr/src/lib/libdladm/common/libdliptun.c, usr/src/lib/libdladm/common/libdlsim.c, usr/src/lib/libdladm/common/libdlvnic.c, usr/src/lib/libofmt/common/ofmt.c, usr/src/man/man2/getcontext.2, usr/src/man/man8/sharemgr.8, usr/src/pkg/manifests/system-test-ostest.p5m, usr/src/test/os-tests/runfiles/default.run, usr/src/test/os-tests/tests/Makefile, usr/src/test/os-tests/tests/ucontext.c, usr/src/uts/common/fs/smbsrv/smb_node.c, usr/src/uts/common/fs/smbsrv/smb_server.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c
* [15206 setcontext(2) should not restore %fsbase](https://github.com/omniosorg/illumos-omnios/commit/3f3c90a958c5abf8ec0ed5d1fad2e40bd9905a50)
```
OmniOS r151045  omnios-upstream_merge-2022120801-5199d77d1f     December 2022
illumos development build: 2022-Dec-08 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2022120801-5199d77d1f i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Dec  8 21:25:51 UTC 2022 ====
==== Nightly distributed build completed: Thu Dec  8 22:04:03 UTC 2022 ====
real    0:38:11
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-9c871b379a6 i86pc i386 i86pc
number of concurrent jobs …
```
=> Upstream merge/2022120801

usr/src/common/unicode/u8_textprep.c
Reviewed by: Patrick Mooney <pmooney@pfmooney.com>
Reviewed by: Richard Lowe <richlowe@richlowe.net>
Approved by: Joshua M. Clulow <josh@sysmgr.org>
=> 15286 do_composition() needs sign awareness

usr/src/uts/common/sys/ccompile.h
Reviewed by: Jason King <jason.brian.king+illumos@gmail.com>
=> 14622 want __maybe_unused (r151038)

usr/src/uts/common/sys/ccompile.h
Reviewed by: Jason King <jason.brian.king+illumos@gmail.com>
=> 14622 want __maybe_unused (r151042)

usr/src/data/zoneinfo/africa, usr/src/data/zoneinfo/antarctica, usr/src/data/zoneinfo/asia, usr/src/data/zoneinfo/australasia, usr/src/data/zoneinfo/backward, usr/src/data/zoneinfo/country.tab, usr/src/data/zoneinfo/europe, usr/src/data/zoneinfo/northamerica, usr/src/data/zoneinfo/southamerica, usr/src/data/zoneinfo/zone.tab.txt, usr/src/data/zoneinfo/zone_sun.tab, usr/src/lib/sun_fc/common/FCHBA.cc, usr/src/lib/sun_fc/common/FCHBAPort.cc, usr/src/lib/sun_fc/common/HBANPIVPort.cc, usr/src/lib/sun_fc/common/HBAPort.cc, usr/src/lib/sun_fc/common/Sun_fcGetFcpTargetMapping.cc, usr/src/lib/sun_fc/common/TgtFCHBA.cc, usr/src/pkg/manifests/system-data-zoneinfo.p5m
* [15510 Update tzdata to 2023b](https://github.com/omniosorg/illumos-omnios/commit/af2e290bb42516a18ceaf6aed43dd7e45c108b08)
```
OmniOS r151045  omnios-upstream_merge-2023032401-edb3b70feac    March 2023
illumos development build: 2023-Mar-24 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2023032401-edb3b70feac i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Mar 24 19:36:45 UTC 2023 ====
==== Nightly distributed build completed: Fri Mar 24 20:16:24 UTC 2023 ====
real    0:39:38
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-69de2a5279f i86pc i386 i86pc
cw version 8.0 …
```
=> Upstream merge/2023032401

usr/src/cmd/rsrvrctl/rsrvrctl.c
This is pending an upstream fix as it does not address the problems with
concurrency around vmm's ioctl() API (not everything may be using this
utility to manipulate the reservoir), nor the potential race condition
between retrieving the current reservoir size and setting the new one.
This fixes https://github.com/omniosorg/illumos-omnios/issues/1306
=> Add locking to /usr/lib/rsrvrctl (r151046)

usr/src/cmd/rsrvrctl/rsrvrctl.c
This is pending an upstream fix as it does not address the problems with
concurrency around vmm's ioctl() API (not everything may be using this
utility to manipulate the reservoir), nor the potential race condition
between retrieving the current reservoir size and setting the new one.
This fixes https://github.com/omniosorg/illumos-omnios/issues/1306
=> Add locking to /usr/lib/rsrvrctl

usr/src/boot/common/load_elf.c, usr/src/boot/i386/loader/conf.c, usr/src/boot/include/stdint.h, usr/src/cmd/ctfconvert/ctfconvert.c, usr/src/cmd/ctfmerge/ctfmerge.c, usr/src/cmd/fs.d/autofs/autod_parse.c, usr/src/cmd/ps/ps.c, usr/src/lib/libctf/common/ctf_convert.c, usr/src/lib/libuuid/common/uuid.c, usr/src/man/man4d/Makefile, usr/src/man/man4d/vmxnet3s.4d, usr/src/pkg/manifests/driver-network-vmxnet3s.p5m, usr/src/uts/common/fs/smbsrv/smb2_durable.c, usr/src/uts/common/fs/smbsrv/smb_ofile.c, usr/src/uts/intel/io/scsi/adapters/arcmsr/arcmsr.c
* none
```
OmniOS r151047  omnios-upstream_merge-2023070801-96055a5c90     July 2023
illumos development build: 2023-Jul-08 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2023070801-96055a5c90 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Sat Jul  8 11:28:49 UTC 2023 ====
==== Nightly distributed build completed: Sat Jul  8 12:04:24 UTC 2023 ====
real    0:35:35
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-765ef75fcd i86pc i386 i86pc
cw version 9.0
gcc (OmniOS 151047/10.4.0-il-1) 10.4.0
This …
```
=> Upstream merge/2023070801

.gitignore, usr/src/cmd/diskinfo/diskinfo.c, usr/src/cmd/fs.d/nfs/mountd/mountd.c, usr/src/cmd/idmap/idmapd/idmap_config.c, usr/src/cmd/idmap/idmapd/idmap_config.h, usr/src/cmd/sgs/rtld/Makefile.com, usr/src/cmd/sgs/rtld/common/util.c, usr/src/cmd/smbsrv/smbd/smbd.h, usr/src/cmd/smbsrv/smbd/smbd_join.c, usr/src/cmd/smbsrv/smbstat/smbstat.c, usr/src/lib/libc/port/gen/ttyname.c, usr/src/man/man8/ndd.8, usr/src/man/man9e/mac.9e, usr/src/man/man9e/mac_capab_rings.9e, usr/src/man/man9e/mac_filter.9e, usr/src/man/man9e/mgi_start.9e, usr/src/man/man9e/mr_rget.9e, usr/src/man/man9e/mri_poll.9e, usr/src/man/man9e/mri_stat.9e, usr/src/man/man9f/Intro.9f, usr/src/man/man9f/Makefile, usr/src/man/man9f/mac_register.9f, usr/src/man/man9f/mac_rx.9f, usr/src/man/man9s/mac_intr.9s, usr/src/pkg/manifests/system-kernel.man9f.inc, usr/src/uts/common/fs/smbsrv/smb2_lease.c, usr/src/uts/common/fs/smbsrv/smb2_oplock.c, usr/src/uts/common/fs/smbsrv/smb_oplock.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c
Weekly upstream for upstream_merge/2023072101
None
```
OmniOS r151047 Version omnios-upstream_merge-2023072101-606c1a719b5 64-bit
Copyright (c) 2017-2023 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Tue Jul 11 20:52:40 2023 on console
OmniOS r151047  omnios-upstream_merge-2023072101-606c1a719b5    July 2023
illumos development build: 2023-Jul-21 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2023072101-606c1a719b5 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Jul 21 17:26:06 UTC 2023 ====
==== Nightly distributed build completed: Fri Jul 21 18:36:42 UTC 2023 ====
==== Total build …
```
=> Upstream merge upstream_merge/2023072101

usr/src/uts/common/fs/smbsrv/smb_authenticate.c, usr/src/uts/common/fs/smbsrv/smb_lock.c, usr/src/uts/common/fs/smbsrv/smb_notify.c, usr/src/uts/common/fs/smbsrv/smb_opipe.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c, usr/src/uts/common/smbsrv/smb_ktypes.h
Reviewed by: Jerry Jelinek <gjelinek@racktopsystems.com>
Reviewed by: Matt Barden <mbarden@racktopsystems.com>
=> 15985 SMB cancel functions race with request completion (r151048)

usr/src/uts/common/fs/smbsrv/smb_authenticate.c, usr/src/uts/common/fs/smbsrv/smb_lock.c, usr/src/uts/common/fs/smbsrv/smb_notify.c, usr/src/uts/common/fs/smbsrv/smb_opipe.c, usr/src/uts/common/fs/smbsrv/smb_session.c, usr/src/uts/common/fs/smbsrv/smb_srv_oplock.c, usr/src/uts/common/smbsrv/smb_ktypes.h
Reviewed by: Jerry Jelinek <gjelinek@racktopsystems.com>
Reviewed by: Matt Barden <mbarden@racktopsystems.com>
=> 15985 SMB cancel functions race with request completion (r151046)

usr/src/uts/intel/io/vmm/intel/vmx_support.S, usr/src/uts/intel/ml/retpoline.S, usr/src/uts/intel/os/cpuid.c, usr/src/uts/intel/sys/x86_archext.h
…in HW
Reviewed by: Rich Lowe <richlowe@richlowe.net>
=> 16413 Post-barrier Return Stack Buffer (PBRSB) fixes can be detected … (r151046)

README.OmniOS, usr/src/cmd/cmd-inet/usr.bin/nc/netcat.c, usr/src/cmd/cmd-inet/usr.sbin/snoop/snoop_ip.c, usr/src/cmd/mdb/common/modules/ip/ip.c, usr/src/cmd/svc/common/notify_params.c, usr/src/cmd/svc/svccfg/Makefile, usr/src/cmd/svc/svccfg/svccfg.h, usr/src/cmd/svc/svccfg/svccfg.y, usr/src/cmd/svc/svccfg/svccfg_libscf.c, usr/src/cmd/svc/svccfg/svccfg_main.c, usr/src/lib/libc/port/locale/strftime.c, usr/src/man/man1/nc.1, usr/src/pkg/manifests/system-test-libctest.p5m, usr/src/test/libc-tests/runfiles/default.run, usr/src/test/libc-tests/tests/Makefile, usr/src/test/libc-tests/tests/ascftime.c, usr/src/test/zfs-tests/tests/functional/cli_root/zfs_property/zfs_written_property_001_pos.ksh, usr/src/uts/common/fs/zfs/vdev.c, usr/src/uts/common/fs/zfs/vdev_indirect.c, usr/src/uts/common/fs/zfs/vdev_label.c, usr/src/uts/common/inet/ipf/fil.c, usr/src/uts/common/inet/ipf/ip_proxy.c, usr/src/uts/common/inet/ipf/netinet/ip_compat.h
Weekly upstream for upstream_merge/2024050401
None
```
OmniOS r151049 Version omnios-upstream_merge-2024050401-a13283c04dc 64-bit
Copyright (c) 2017-2024 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Tue Apr 30 16:58:38 2024 on console
OmniOS r151049  omnios-upstream_merge-2024050401-a13283c04dc    May 2024
illumos development build: 2024-May-04 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2024050401-a13283c04dc i86pc i386 i86pc
root@bloody:~#
```
```
==== Nightly distributed build started:   Sat May  4 09:59:29 UTC 2024 ====
==== Nightly distributed build completed: Sat May  4 11:10:52 UTC 2024 ====
==== Total build time …
```
=> Upstream merge upstream_merge/2024050401

usr/src/tools/env/omnios-illumos-gate.sh
=> Do not overwrite GNUC_ROOT in omnios-illumos-gate

usr/src/common/crypto/sha1/sha1.c, usr/src/test/crypto-tests/tests/longhash/longhash.c
=> 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151050)

usr/src/common/crypto/sha1/sha1.c, usr/src/test/crypto-tests/tests/longhash/longhash.c
=> 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151048)

usr/src/common/crypto/sha1/sha1.c, usr/src/test/crypto-tests/tests/longhash/longhash.c
=> 16350 SHA1 may produce incorrect hashes if given a 2^29 byte input (r151046)

usr/src/pkg/manifests/driver-storage-mpt_sas.p5m, usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas.c, usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_impl.c, usr/src/uts/common/io/scsi/adapters/mpt_sas/mptsas_init.c, usr/src/uts/common/sys/scsi/adapters/mpt_sas/mpi/mpi2_cnfg.h, usr/src/uts/common/sys/scsi/adapters/mpt_sas/mptsas_var.h
Reviewed by: Dan McDonald <danmcd@mnx.io>
Reviewed by: Hans Rosenfeld <rosenfeld@grumpf.hope-2000.org>
Reviewed by: Bill Sommerfeld <sommerfeld@hamachi.org>
Reviewed by: Dale Ghent <daleg@elemental.org>
Approved by: Robert Mustacchi <rm@fingolfin.org>
=> 16524 driver for 38xx HBA in illumos (r151046)

README.OmniOS, usr/src/cmd/diskinfo/diskinfo.c, usr/src/lib/libdiskmgt/common/cache.c, usr/src/lib/libdiskmgt/common/disks_private.h, usr/src/lib/libdiskmgt/common/drive.c, usr/src/lib/libdiskmgt/common/findevs.c, usr/src/lib/libdiskmgt/common/libdiskmgt.h, usr/src/uts/common/fs/zfs/sys/simd.h, usr/src/uts/common/io/sata/impl/sata.c
* none
```
OmniOS r151051  omnios-upstream_merge-2024060601-a0c0dbef9ee    June 2024
illumos development build: 2024-Jun-06 [illumos-omnios]
SunOS nemesis 5.11 omnios-upstream_merge-2024060601-a0c0dbef9ee i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Thu Jun  6 17:01:26 UTC 2024 ====
==== Nightly distributed build completed: Thu Jun  6 17:37:50 UTC 2024 ====
real    0:36:24
/usr/bin/uname
SunOS nemesis 5.11 omnios-master-615aba20106 i86pc i386 i86pc
cw version 9.0
gcc (OmniOS 151051/10.5.0-il-1) 10.5.0 …
```
=> Upstream merge/2024060601

usr/src/cmd/krb5/ldap_util/kdb5_ldap_realm.c, usr/src/test/zfs-tests/tests/functional/rootpool/setup.ksh, usr/src/uts/common/io/eventfd.c, usr/src/uts/common/io/usb/hcd/xhci/xhci_command.c, usr/src/uts/intel/io/amdzen/amdzen.c, usr/src/uts/intel/sys/amdzen/df.h
Weekly upstream for upstream_merge/2024081601
None
```
OmniOS r151051 Version omnios-upstream_merge-2024081601-0d4d79e4ae8 64-bit
Copyright (c) 2017-2024 OmniOS Community Edition (OmniOSce) Association.
DEBUG enabled
Password:
Last login: Fri Jul 26 14:21:10 2024 on console
OmniOS r151051  omnios-upstream_merge-2024081601-0d4d79e4ae8    August 2024
illumos development build: 2024-Aug-16 [illumos]
SunOS bloody 5.11 omnios-upstream_merge-2024081601-0d4d79e4ae8 i86pc i386 i86pc
```
```
==== Nightly distributed build started:   Fri Aug 16 17:36:31 UTC 2024 ====
==== Nightly distributed build completed: Fri Aug 16 18:47:49 UTC 2024 ====
==== Total …
```
=> Upstream merge upstream_merge/2024081601

usr/src/lib/libefi/common/rdwr_efi.c
Reviewed by: C Fraire <cfraire@me.com>
Reviewed by: Gergő Mihály Doma <domag02@gmail.com>
=> 14577 ESX offline disk resize prevents growing zpool

usr/src/uts/intel/io/hyperv/vmbus/vmbus.c
=> HYPERV: Task queues are never initialised
